### ISSUE TITLE
Regression: ACL tests failing on iteration and mapping

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#117]
We have a regression somewhere: if I checkout my last commit and run the tests, they are successful, if I do the same on master, the tests do fail:

```
$ git status
HEAD detached at cd6eac9
nothing to commit, working tree clean
$ git checkout master
Previous HEAD position was cd6eac9 Make the test scripts PEP8/flake8 compatible (2)
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
$ tox -e py37
[...]
======================================================================
FAIL: testIterate (__main__.ACLTest)
Test writing several records and then reading them back
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/eas_aclstest.py", line 483, in testIterate
    assert acl1_reread == self.acl1
AssertionError

======================================================================
FAIL: test_acl_mapping (__main__.ACLTest)
Test mapping ACL names
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/eas_aclstest.py", line 600, in test_acl_mapping
    assert get_perms_of_user(out_acl, self.current_user) == 7
AssertionError

----------------------------------------------------------------------
Ran 20 tests in 8.479s

FAILED (failures=2)
ERROR: InvocationError for command '/home/ericl/Comp/rdiff-backup/.tox/py37/bin/python testing/eas_aclstest.py' (exited with code 1)
__________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________
ERROR:   py37: commands failed
```

I won't have time quickly to analyse the issue so if someone could look into it before we change too much the code again.

**Comment by ottok** [comment]
I was under pressure to get Travis-CI active to ensure there is some external thing running the tests, since not all contributors yet know how to run the tests locally.

Therefore I resorted to disabling one failing test, and in another I hardcoded the user and group name since the test was not reading the environment variables for them.

Please see https://github.com/rdiff-backup/rdiff-backup/commit/5954f6059ff49bcb426daa0eed73d81665c99bad

**Comment by ericzolf** [comment]
Commenting out the test is OK, because it doesn't break anything. But breaking local tests to fix something else isn't IMHO.

**Comment by ottok** [comment]
Sorry, but I was under pressure to get the Travis-CI going thus made this trade-off of getting the tests working locally for myself and for Travis-CI (and thus for all our current other contributors). I think this was a slightly better option that commenting out the whole ACL tests as that would have hurt the coverage.

Would you be kind and fix these two things marked `@TODO` now so that they work for everybody?
