### ISSUE TITLE
IOError: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by xHire** [rdiff-backup/rdiff-backup#18]
I’m doing separate backups of several directories to a single medium. The cron task executing the backups recently started sending me the following output for two of those directories:

```
Exception '[Errno 20] Not a directory' raised of class '<type 'exceptions.IOError'>':
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/Main.py", line 306, in error_check_Main
    try: Main(arglist)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/Main.py", line 326, in Main
    take_action(rps)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/Main.py", line 282, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/Main.py", line 345, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/backup.py", line 51, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/backup.py", line 251, in patch_and_increment
    ITR(diff.index, diff)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/rorpiter.py", line 284, in __call__
    branch.start_process(*args)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/backup.py", line 727, in start_process
    inc.fsync_with_dir() # must write inc before rp changed
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/rpath.py", line 1315, in fsync_with_dir
    if Globals.fsync_directories: self.get_parent_rp().fsync()
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/rpath.py", line 1138, in get_parent_rp
    return self.__class__(self.conn, self.base, self.index[:-1])
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/rpath.py", line 884, in __init__
    else: self.setdata()
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/rpath.py", line 909, in setdata
    if self.lstat(): self.conn.rpath.setdata_local(self)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/rpath.py", line 1502, in setdata_local
    if Globals.acls_conn: rpath.data['acl'] = acl_get(rpath)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/eas_acls.py", line 580, in rpath_acl_get
    if not rp.issym(): acl.read_from_rp(rp)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/eas_acls.py", line 366, in read_from_rp
    rp.conn.eas_acls.get_acl_lists_from_rp(rp)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/eas_acls.py", line 399, in get_acl_lists_from_rp
    try: acl = posix1e.ACL(file=rp.path)

Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/rdiff-backup", line 30, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/Main.py", line 306, in error_check_Main
    try: Main(arglist)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/Main.py", line 326, in Main
    take_action(rps)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/Main.py", line 282, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/Main.py", line 345, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/backup.py", line 51, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/backup.py", line 251, in patch_and_increment
    ITR(diff.index, diff)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/rorpiter.py", line 284, in __call__
    branch.start_process(*args)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/backup.py", line 727, in start_process
    inc.fsync_with_dir() # must write inc before rp changed
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/rpath.py", line 1315, in fsync_with_dir
    if Globals.fsync_directories: self.get_parent_rp().fsync()
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/rpath.py", line 1138, in get_parent_rp
    return self.__class__(self.conn, self.base, self.index[:-1])
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/rpath.py", line 884, in __init__
    else: self.setdata()
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/rpath.py", line 909, in setdata
    if self.lstat(): self.conn.rpath.setdata_local(self)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/rpath.py", line 1502, in setdata_local
    if Globals.acls_conn: rpath.data['acl'] = acl_get(rpath)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/eas_acls.py", line 580, in rpath_acl_get
    if not rp.issym(): acl.read_from_rp(rp)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/eas_acls.py", line 366, in read_from_rp
    rp.conn.eas_acls.get_acl_lists_from_rp(rp)
  File "/usr/lib64/python2.7/site-packages/rdiff_backup/eas_acls.py", line 399, in get_acl_lists_from_rp
    try: acl = posix1e.ACL(file=rp.path)
IOError: [Errno 20] Not a directory
```

Or simply such an output without any backtrace:

```
ListError docs/ruby/classes/REXML/Encoding.src/M006539.html/M006540.html [Errno 20] Not a directory
```

The output is always different. If it is the latter one, different files are mentioned each time (I didn’t get this error for the same file twice).

I ran `--check-destination-dir`, but nothing wrong was found in one case, in the other rdiff-backup tried to regress, nonetheless ended up with the error `Not a directory` again (note: trying to run `rdiff-backup-regress.sh` is therefore not of much help – I tried that, because `--verify` didn’t find checksums for many files).

**Comment by ericzolf** [comment]
Can you check if you still have the issue with the version of rdiff-backup from Git (master branch)? We've changed so many things that it doesn't make sense before you've confirmed that the issue still exists. Check DEVELOP.md for how to compile / run from Git.
Else unpack as root the attached file 
[rdiff-backup-1.3.5.linux-x86_64.tar.gz](https://github.com/rdiff-backup/rdiff-backup/files/3774621/rdiff-backup-1.3.5.linux-x86_64.tar.gz)

**Comment by ericzolf** [comment]
Closing as there is no way to reproduce it.
