### ISSUE TITLE
MemoryError exception when remote server does not start

### ISSUE THREAD

**Issue by chrisbainbridge** [rdiff-backup/rdiff-backup#21]
(Note: This bug has been verified on CentOS 7. I have not verified whether it is still present in the github code, but from a quick check the code appears to be the same.)

If rdiff-backup is not installed on remote, ssh returns:

    bash: rdiff-backup: command not found

connection.py LowLevelPipeConnection._get reads that text, interprets the text as a binary long, and then calls _read which tries to allocate a huge amount of memory. 

                           
                header_string = self.inpipe.read(9)                             
                if not len(header_string) == 9:                                 
                        raise ConnectionReadError("Truncated header string (problem "
                                                                          "probably originated remotely)")
                format_string, req_num, length = (header_string[0],             
                                                                                  ord(header_string[1]),
                                                                                  C.str2long(header_string[2:]))

Exception:

    Exception '' raised of class '<type 'exceptions.MemoryError'>':             
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/Main.py", line 304, in error_check_Main
        try: Main(arglist)                                                      
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/Main.py", line 321, in Main
        rps = map(SetConnections.cmdpair2rp, cmdpairs)                          
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/SetConnections.py", line 76, in cmdpair2rp
        if cmd: conn = init_connection(cmd)                                     
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/SetConnections.py", line 150, in init_connection
        check_connection_version(conn, remote_cmd)                              
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/SetConnections.py", line 158, in check_connection_version
        try: remote_version = conn.Globals.get('version')                       
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/connection.py", line 453, in __call__
        return apply(self.connection.reval, (self.name,) + args)                
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/connection.py", line 371, in reval
        result = self.get_response(req_num)                                     
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/connection.py", line 318, in get_response
        try: req_num, object = self._get()                                      
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/connection.py", line 243, in _get
        data = self._read(length)                                               
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/connection.py", line 211, in _read
        try: return self.inpipe.read(length)    

    Traceback (most recent call last):                                          
      File "/usr/bin/rdiff-backup", line 30, in <module>                        
        rdiff_backup.Main.error_check_Main(sys.argv[1:])                        
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/Main.py", line 304, in error_check_Main
        try: Main(arglist)                                                      
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/Main.py", line 321, in Main
        rps = map(SetConnections.cmdpair2rp, cmdpairs)                          
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/SetConnections.py", line 76, in cmdpair2rp
        if cmd: conn = init_connection(cmd)                                     
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/SetConnections.py", line 150, in init_connection
        check_connection_version(conn, remote_cmd)                              
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/SetConnections.py", line 158, in check_connection_version
        try: remote_version = conn.Globals.get('version')                       
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/connection.py", line 453, in __call__
        return apply(self.connection.reval, (self.name,) + args)                
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/connection.py", line 371, in reval
        result = self.get_response(req_num)                                     
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/connection.py", line 318, in get_response
        try: req_num, object = self._get()                                      
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/connection.py", line 243, in _get
        data = self._read(length)                                               
      File "/usr/lib64/python2.7/site-packages/rdiff_backup/connection.py", line 211, in _read
        try: return self.inpipe.read(length)                                    
    MemoryError 

It looks like this is an old bug, previous reports include:
 - [mailing list](https://lists.nongnu.org/archive/html/rdiff-backup-users/2016-06/msg00003.html)
 - [on launchpad](https://bugs.launchpad.net/ubuntu/+source/rdiff-backup/+bug/822594)
 - [savannah](https://savannah.nongnu.org/bugs/?46669)
 - [serverfault](https://serverfault.com/questions/742442/what-do-do-when-rdiff-backup-memoryerror-happens)
 - [mailing list](https://lists.nongnu.org/archive/html/rdiff-backup-users/2011-05/msg00029.html)
 - [redhat bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1026507)

**Comment by whataboutpereira** [comment]
I ran into this today. Both client and server are CentOS 8 machines using rdiff-backup 2.0.

```
Sun May 10 18:15:07 EEST 2020:

Exception '' raised of class '<class 'MemoryError'>':
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 409, in Main
    rps = list(map(SetConnections.cmdpair2rp, cmdpairs))
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/SetConnections.py", line 85, in cmdpair2rp
    conn = init_connection(cmd)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/SetConnections.py", line 191, in init_connection
    check_connection_version(conn, remote_cmd)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/SetConnections.py", line 201, in check_connection_version
    remote_version = conn.Globals.get('version')
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 526, in __call__
    return self.connection.reval(*(self.name, ) + args)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 436, in reval
    result = self.get_response(req_num)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 379, in get_response
    req_num, object = self._get()
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 293, in _get
    data = self._read(length)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 266, in _read
    return self.inpipe.read(length)

Traceback (most recent call last):
  File "/usr/local/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 409, in Main
    rps = list(map(SetConnections.cmdpair2rp, cmdpairs))
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/SetConnections.py", line 85, in cmdpair2rp
    conn = init_connection(cmd)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/SetConnections.py", line 191, in init_connection
    check_connection_version(conn, remote_cmd)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/SetConnections.py", line 201, in check_connection_version
    remote_version = conn.Globals.get('version')
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 526, in __call__
    return self.connection.reval(*(self.name, ) + args)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 436, in reval
    result = self.get_response(req_num)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 379, in get_response
    req_num, object = self._get()
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 293, in _get
    data = self._read(length)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 266, in _read
    return self.inpipe.read(length)
MemoryError
Fatal Error: Lost connection to the remote system
```

I grepped system logs on both ends for "May 10 18:15", but unfortunately nothing stood out there.

**Comment by ericzolf** [comment]
If you have rdiff-backup installed on both sides, it's not the same issue, can you please create a new one, and answer the questions from the bug template?

**Comment by whataboutpereira** [comment]
Thanks, done!
