### ISSUE TITLE
rdiff-backup v1.3 has changed default date format in repos on Windows

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#216]
rdiff-backup on windows is not working when the source and destination is on windows.

Sorry for the french error message. The only Windows I have under my hand is french.
It's failing as follow:
```
C:\Users\vmtest\Desktop>C:\Users\vmtest\Downloads\rdiff-backup-1.4.0b0-win64.exe
 test_base test_destination
Exception '[WinError 123] La syntaxe du nom de fichier, de répertoire ou de volu
me est incorrecte: b'test_destination/rdiff-backup-data/current_mirror.2019-12-1
5T08:36:05-05:00.data'' raised of class '<class 'OSError'>':
  File "rdiff_backup\Main.py", line 384, in error_check_Main
  File "rdiff_backup\Main.py", line 406, in Main
  File "rdiff_backup\Main.py", line 342, in take_action
  File "rdiff_backup\Main.py", line 422, in Backup
  File "rdiff_backup\Main.py", line 609, in backup_final_init
  File "rdiff_backup\Main.py", line 1112, in checkdest_if_necessary
  File "rdiff_backup\Main.py", line 1076, in checkdest_need_check
  File "rdiff_backup\restore.py", line 56, in get_inclist
  File "rdiff_backup\rpath.py", line 1375, in append
  File "rdiff_backup\FilenameMapping.py", line 146, in __init__
  File "rdiff_backup\rpath.py", line 1047, in __init__
  File "rdiff_backup\rpath.py", line 1073, in setdata
  File "rdiff_backup\rpath.py", line 352, in make_file_dict

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 384, in error_check_Main
  File "rdiff_backup\Main.py", line 406, in Main
  File "rdiff_backup\Main.py", line 342, in take_action
  File "rdiff_backup\Main.py", line 422, in Backup
  File "rdiff_backup\Main.py", line 609, in backup_final_init
  File "rdiff_backup\Main.py", line 1112, in checkdest_if_necessary
  File "rdiff_backup\Main.py", line 1076, in checkdest_need_check
  File "rdiff_backup\restore.py", line 56, in get_inclist
  File "rdiff_backup\rpath.py", line 1375, in append
  File "rdiff_backup\FilenameMapping.py", line 146, in __init__
  File "rdiff_backup\rpath.py", line 1047, in __init__
  File "rdiff_backup\rpath.py", line 1073, in setdata
  File "rdiff_backup\rpath.py", line 352, in make_file_dict
OSError: [WinError 123] La syntaxe du nom de fichier, de répertoire ou de volume
 est incorrecte: b'test_destination/rdiff-backup-data/current_mirror.2019-12-15T
08:36:05-05:00.data'
[3504] Failed to execute script rdiff-backup
```

Had a look at the code and I don't find anything obvious about why the "current_mirror.2019-12-15T
08:36:05-05:00.data" is not quoted.

**Comment by ikus060** [comment]
Looking more into this issue, it seams we have a big difference between v1.2.8 repository and v1.4.0b0 repository on Windows.
The file name under rdiff-backup-data are not mangled the same way:
v1.2.8: `current_mirror.2019-12-16T07;05858;05804-05;05800.data`
v1.4.0b0: `current_mirror.2019-12-16T07-57-49-05-00.data`

![image](https://user-images.githubusercontent.com/921251/70909133-cd8b2000-1fda-11ea-86c7-4c39eb65cbec.png)

**Comment by pblahman** [comment]
My experience below may be the same problem.    Being in English it may be helpful?  My initial try was using  "C:\users" as the source.   No joy. 
---------   Start of trace -----------------------
C:\>rdiff-backup-1.4.0b0-win64.exe Windows h:
Found interrupted initial backup. Removing...
Exception 'readlink() argument 1 must be str, not bytes' raised of class '<class 'TypeError'>':
  File "rdiff_backup\Main.py", line 384, in error_check_Main
  File "rdiff_backup\Main.py", line 406, in Main
  File "rdiff_backup\Main.py", line 342, in take_action
  File "rdiff_backup\Main.py", line 418, in Backup
  File "rdiff_backup\fs_abilities.py", line 1052, in backup_set_globals
  File "rdiff_backup\fs_abilities.py", line 170, in init_readwrite
  File "rdiff_backup\fs_abilities.py", line 591, in set_symlink_perms
  File "rdiff_backup\rpath.py", line 1188, in symlink
  File "rdiff_backup\rpath.py", line 1073, in setdata
  File "rdiff_backup\rpath.py", line 374, in make_file_dict

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 384, in error_check_Main
  File "rdiff_backup\Main.py", line 406, in Main
  File "rdiff_backup\Main.py", line 342, in take_action
  File "rdiff_backup\Main.py", line 418, in Backup
  File "rdiff_backup\fs_abilities.py", line 1052, in backup_set_globals
  File "rdiff_backup\fs_abilities.py", line 170, in init_readwrite
  File "rdiff_backup\fs_abilities.py", line 591, in set_symlink_perms
  File "rdiff_backup\rpath.py", line 1188, in symlink
  File "rdiff_backup\rpath.py", line 1073, in setdata
  File "rdiff_backup\rpath.py", line 374, in make_file_dict
TypeError: readlink() argument 1 must be str, not bytes
[2000] Failed to execute script rdiff-backup
--------------   End of trace ------------

**Comment by ericzolf** [comment]
OK, let me have a look. I'm not conscious to have changed anything in this corner, but perhaps I did it unintentionally.

**Comment by frankcrawford** [comment]
@ericzolf This may not be your issue, but a difference between 1.2.8 and 1.3.x.  I noticed while reviewing the upgrade, their was the addition of a variable "use_compatible_timestamps" which has the following comment:

    # If true, the timestamps use the following format: "2008-09-01T04-49-04-07-00"
    # (instead of "2008-09-01T04:49:04-07:00"). This creates timestamps which
    # don't need to be escaped on Windows.

It is in Globals.py around line 366.

**Comment by ericzolf** [comment]
Currently travelling and pre-holiday madness, not sure when I'll find time to look into it. The changes up to 1.3.3 (IIRC) are not mine, but we can look into fixing. My aim remains for 2.0.0: no regression compared to 1.2.8 and, as far as possible, repo compatibility.

**Comment by ericzolf** [comment]
One more question to the crowd: the issue appears only if you try to re-use a repo created by rdiff-backup 1.2.x, _not_ if you start a new repo from scratch with 1.4.0?

**Comment by ikus060** [comment]
@ericzolf Yes, when I start a repo with 1.2.8, then start using v1.4.0b0 it raise the error:
Take a look at the binary used
```
C:\Users\vmtest\Desktop>del test_destination
C:\Users\vmtest\Desktop>C:\Users\vmtest\AppData\Local\minarca\rdiff-backup-1.2.8
\rdiff-backup.exe test_base test_destination

C:\Users\vmtest\Desktop>C:\Users\vmtest\Downloads\rdiff-backup-1.4.0b0-win64.exe
 test_base test_destination
Exception '[WinError 123] La syntaxe du nom de fichier, de répertoire ou de volu
me est incorrecte: b'test_destination/rdiff-backup-data/current_mirror.2019-12-1
9T08:13:20-05:00.data'' raised of class '<class 'OSError'>':
  File "rdiff_backup\Main.py", line 384, in error_check_Main
  File "rdiff_backup\Main.py", line 406, in Main
  File "rdiff_backup\Main.py", line 342, in take_action
  File "rdiff_backup\Main.py", line 422, in Backup
  File "rdiff_backup\Main.py", line 609, in backup_final_init
  File "rdiff_backup\Main.py", line 1112, in checkdest_if_necessary
  File "rdiff_backup\Main.py", line 1076, in checkdest_need_check
  File "rdiff_backup\restore.py", line 56, in get_inclist
  File "rdiff_backup\rpath.py", line 1375, in append
  File "rdiff_backup\FilenameMapping.py", line 146, in __init__
  File "rdiff_backup\rpath.py", line 1047, in __init__
  File "rdiff_backup\rpath.py", line 1073, in setdata
  File "rdiff_backup\rpath.py", line 352, in make_file_dict

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 384, in error_check_Main
  File "rdiff_backup\Main.py", line 406, in Main
  File "rdiff_backup\Main.py", line 342, in take_action
  File "rdiff_backup\Main.py", line 422, in Backup
  File "rdiff_backup\Main.py", line 609, in backup_final_init
  File "rdiff_backup\Main.py", line 1112, in checkdest_if_necessary
  File "rdiff_backup\Main.py", line 1076, in checkdest_need_check
  File "rdiff_backup\restore.py", line 56, in get_inclist
  File "rdiff_backup\rpath.py", line 1375, in append
  File "rdiff_backup\FilenameMapping.py", line 146, in __init__
  File "rdiff_backup\rpath.py", line 1047, in __init__
  File "rdiff_backup\rpath.py", line 1073, in setdata
  File "rdiff_backup\rpath.py", line 352, in make_file_dict
OSError: [WinError 123] La syntaxe du nom de fichier, de répertoire ou de volume
 est incorrecte: b'test_destination/rdiff-backup-data/current_mirror.2019-12-19T
08:13:20-05:00.data'
[2308] Failed to execute script rdiff-backup
```

**Comment by pblahman** [comment]
My use case did not involve using 1.28.    A  local backup from folder  C:\users to an another drive fails as indicated in my earlier message.    This failure is on Windows 10, version 1909.    I have not tried 1.28 yet.

**Comment by ikus060** [comment]
@pblahman I would way it's another defect then.
The exception raised is not the same as mine.  I've created #218 to track it.

**Comment by frankcrawford** [comment]
One other item about the `use_compatibility_timestamps`is that there is an option to turn it on, but nothing to turn it off.
It is automatically enabled on Windows and similar systems, and currently there is nothing you can do about it.
Can you use `-v4` and check if the message `Enabled use_compatible_timestamps` is printed in the log for the v1.4.0b0 version.

**Comment by ericzolf** [comment]
I renamed the ticket to better reflect the actual issue. And because v1.3 has been out there for quite a while even if not officially released, we need to make sure 1.4+ can support <1.3 and ~1.3 repos.

**Comment by ericzolf** [comment]
Checking with `git blame -w -L768,773 src/rdiff_backup/fs_abilities.py`, I found that the issue appeared with `git show f36d332e`. The interesting statement is from the man page:

> It is safe to use this option on one backup, and then not use it on another; rdiff-backup supports the intermingling of different timestamp formats.

It obviously isn't a correct statement, else we wouldn't have this issue, and I think that it's due to the statement `regexp = re.compile('[-:]')`, which doesn't take into account the name quoting happening under Windows with `:` (represented as `;058`). I still haven't completely understood why the "unquoting" doesn't make it work the way it should, but fixing the regexp should solve also the issue.

**Comment by ericzolf** [comment]
Mea culpa, the error was mine: I had tried to be smart about inheriting from RPath to QuotedRPath but oversaw that RPath would try to gather data from the "unquoted" filename before it was quoted. I'm now fixing and testing...

**Comment by ericzolf** [comment]
@ikus060 can you please check that the binary attached to https://github.com/rdiff-backup/rdiff-backup/pull/230#issuecomment-570777451 solves your issue?

**Comment by ikus060** [comment]
I've tested `rdiff-backup-1.4.0b1.dev25+gba3f836` on windows 10. The quoting issue seams to be fixed.
