### ISSUE TITLE
scm_version build problem: pybuild --clean -i python{version} -p "3.8 3.7" returned exit code 13

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#222]
I am unable to build on Debian the latest master branch due to this issue:
```
dh clean --buildsystem=pybuild --with python3 --fail-missing
   dh_auto_clean -O--buildsystem=pybuild -O--fail-missing
I: pybuild base:217: python3.8 setup.py clean 
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from setuptools import setup, Extension, Command
ModuleNotFoundError: No module named 'setuptools'
E: pybuild pybuild:341: clean: plugin distutils failed with: exit code=1: python3.8 setup.py clean 
dh_auto_clean: pybuild --clean -i python{version} -p "3.8 3.7" returned exit code 13
make: *** [debian/rules:4: clean] Error 255
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -I failed
gbp:error: 'debuild -i -I -us -uc' failed: it exited with 29
```

This is due to something in the new scm_version code which I am unable to figure out what is going on. Can somebody give me some pointers please?

Is it at all possible to run setuptools in a repository on a development commit unless I have tagged something special?

Previously (in master branch in August) my Debian test builds passed OK and this step in those build logs looked like this:
```
dh clean --buildsystem=pybuild --with python3 --fail-missing
   dh_auto_clean -O--buildsystem=pybuild -O--fail-missing
I: pybuild base:217: python3.8 setup.py clean 
running clean
removing '/tmp/build/source/.pybuild/cpython3_3.8/build' (and everything under it)
'build/bdist.linux-amd64' does not exist -- can't clean it
'build/scripts-3.8' does not exist -- can't clean it
I: pybuild base:217: python3.7 setup.py clean 
running clean
removing '/tmp/build/source/.pybuild/cpython3_3.7/build' (and everything under it)
'build/bdist.linux-amd64' does not exist -- can't clean it
'build/scripts-3.7' does not exist -- can't clean it
   dh_clean -O--buildsystem=pybuild -O--fail-missing
 dpkg-source -i -I -b .
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building rdiff-backup in rdiff-backup_2.0.0.tar.xz
dpkg-source: info: building rdiff-backup in rdiff-backup_2.0.0.dsc
```

**Comment by ikus060** [comment]
Looking at it, you are simply missing setuptools
```ModuleNotFoundError: No module named 'setuptools'```

**Comment by ikus060** [comment]
Could you take a look at this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839687

> use a more recent dh-python dependency
and depend on python-setuptools-scm explicitely, *and* use

I understand you must add this as a dependencies of rdiff-backup: python-setuptools-scm

**Comment by ericzolf** [comment]
At some point in time we replaced distutils with setuptools, so I agree with @ikus060, that seems to be your issue.

**Comment by ottok** [comment]
Installing the new build dependency `python3-setuptools-scm` solved this.

**Comment by ottok** [comment]
NOTE: This is how it looks like if I try to build a source package and python3-setuptools-scm is missing:
```
 dpkg-buildpackage -rfakeroot -us -uc -ui -i -I -S -d
dpkg-buildpackage: info: source package rdiff-backup
dpkg-buildpackage: info: source version 1.4.0b1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Otto Kekäläinen <otto@debian.org>
 dpkg-source -i -I --before-build rdiff-backup
 fakeroot debian/rules clean
dh clean --buildsystem=pybuild --with python3
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:217: python3.6 setup.py clean 

Note: Bypassing https://pypi.python.org/simple/setuptools_scm/ (disallowed host; see http://bit.ly/2hrImnY for details).


Note: Bypassing https://pypi.python.org/simple/setuptools-scm/ (disallowed host; see http://bit.ly/2hrImnY for details).

Couldn't find index page for 'setuptools_scm' (maybe misspelled?)

Note: Bypassing https://pypi.python.org/simple/ (disallowed host; see http://bit.ly/2hrImnY for details).

No local packages or working download links found for setuptools_scm
Traceback (most recent call last):
  File "setup.py", line 223, in <module>
    setup_requires=['setuptools_scm'],
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 128, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 513, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 580, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 692, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')
E: pybuild pybuild:336: clean: plugin distutils failed with: exit code=1: python3.6 setup.py clean 
dh_auto_clean: pybuild --clean -i python{version} -p 3.6 returned exit code 13
debian/rules:4: recipe for target 'clean' failed
make: *** [clean] Error 13
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui -i -I -S -d failed
gbp:error: 'debuild -i -I -S -d' failed: it exited with 29
```

**Comment by ericzolf** [comment]
But we can close the issue?

**Comment by ottok** [comment]
https://github.com/rdiff-backup/rdiff-backup/pull/224 done, all sorted, closing issue..
