### ISSUE TITLE
Backup hangs - Previous backup seems to have failed, regressing destination now.

### ISSUE THREAD

**Issue by Fischmuetze** [rdiff-backup/rdiff-backup#232]
Backup hangs - 
with message "Previous backup seems to have failed, regressing destination now."

macOS 10.14.6

Using rdiff-backup version 1.2.8

Unable to import module posix1e from pylibacl package.
POSIX ACLs not supported on filesystem at /Users/steffen
Unable to import win32security module. Windows ACLs
not supported by filesystem at /Users/steffen
escape_dos_devices not required by filesystem at /Users/steffen

Detected abilities for source (read only) file system:
  Access control lists                         Off
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             Off
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
----
Unable to import module posix1e from pylibacl package.
POSIX ACLs not supported on filesystem at /Users/steffen/.volumes/.backup_img/rdiff-backup-data/rdiff-backup.tmp.0
Unable to import win32security module. Windows ACLs
not supported by filesystem at /Users/steffen/.volumes/.backup_img/rdiff-backup-data/rdiff-backup.tmp.0
escape_dos_devices not required by filesystem at /Users/steffen/.volumes/.backup_img/rdiff-backup-data/rdiff-backup.tmp.0

Detected abilities for destination (read/write) file system:
  Ownership changing                           Off
  Hard linking                                 On
  fsync() directories                          On
  Directory inc permissions                    On
  High-bit permissions                         On
  Symlink permissions                          On
  Extended filenames                           On
  Windows reserved filenames                   Off
  Access control lists                         Off
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             Off
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                On
  Mac OS X Finder information                  Off

Backup: must_escape_dos_devices = 0
Previous backup seems to have failed, regressing destination now.
Regressing to Sat Jan  4 11:16:51 2020
Warning: Could not restore file Music/iTunes/iTunes Music/Music/Einstürzende Neubauten/Ende neu/02 Stella Maris.m4a!

A regular file was indicated by the metadata, but could not be
constructed from existing increments because last increment had type
None.  Instead of the actual file's data, an empty length file will be
created.  This error is probably caused by data loss in the
rdiff-backup destination directory, or a bug in rdiff-backup
Warning: Could not restore file Music/iTunes/iTunes Music/Music/Herbert Grönemeyer/TUMULT (Deluxe)/01 Sekundenglück.m4a!

A regular file was indicated by the metadata, but could not be
constructed from existing increments because last increment had type
None.  Instead of the actual file's data, an empty length file will be
created.  This error is probably caused by data loss in the
rdiff-backup destination directory, or a bug in rdiff-backup
Warning: Could not restore file Music/iTunes/iTunes Music/Music/Herbert Grönemeyer/Was muss muss - Best of Herbert Grönemeyer (Bonus Track Version)/1-03 Glück.m4a!

A regular file was indicated by the metadata, but could not be
constructed from existing increments because last increment had type
None.  Instead of the actual file's data, an empty length file will be
created.  This error is probably caused by data loss in the
rdiff-backup destination directory, or a bug in rdiff-backup
Exception '[Errno 2] No such file or directory: '/Users/steffen/.volumes/.backup_img/Music/iTunes/iTunes Music/Music/Herbert Gro\xcc\x88nemeyer/Was muss muss - Best of Herbert Gr\xc3\xb6nemeyer (Bonus Track Version)/1-03 Gl\xc3\xbcck.m4a'' raised of class '<type 'exceptions.IOError'>':
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/Main.py", line 337, in Backup
    backup_final_init(rpout)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/Main.py", line 501, in backup_final_init
    checkdest_if_necessary(rpout)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/Main.py", line 920, in checkdest_if_necessary
    dest_rp.conn.regress.Regress(dest_rp)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/regress.py", line 71, in Regress
    for rf in iterate_meta_rfs(mirror_rp, inc_rpath): ITR(rf.index, rf)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/rorpiter.py", line 281, in __call__
    last_branch.fast_process(*args)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/regress.py", line 268, in fast_process
    if rf.metadata_rorp.isreg(): self.restore_orig_regfile(rf)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/regress.py", line 296, in restore_orig_regfile
    rf.mirror_rp.write_from_fileobj(rf.get_restore_fp())
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/rpath.py", line 1194, in write_from_fileobj
    outfp = self.open("wb", compress = compress)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/rpath.py", line 1174, in open
    else: return open(self.path, mode)

Traceback (most recent call last):
  File "/usr/local/bin/rdiff-backup", line 30, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/Main.py", line 337, in Backup
    backup_final_init(rpout)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/Main.py", line 501, in backup_final_init
    checkdest_if_necessary(rpout)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/Main.py", line 920, in checkdest_if_necessary
    dest_rp.conn.regress.Regress(dest_rp)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/regress.py", line 71, in Regress
    for rf in iterate_meta_rfs(mirror_rp, inc_rpath): ITR(rf.index, rf)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/rorpiter.py", line 281, in __call__
    last_branch.fast_process(*args)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/regress.py", line 268, in fast_process
    if rf.metadata_rorp.isreg(): self.restore_orig_regfile(rf)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/regress.py", line 296, in restore_orig_regfile
    rf.mirror_rp.write_from_fileobj(rf.get_restore_fp())
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/rpath.py", line 1194, in write_from_fileobj
    outfp = self.open("wb", compress = compress)
  File "/usr/local/Cellar/rdiff-backup/1.2.8_1/libexec/rdiff_backup/rpath.py", line 1174, in open
    else: return open(self.path, mode)
IOError: [Errno 2] No such file or directory: '/Users/steffen/.volumes/.backup_img/Music/iTunes/iTunes Music/Music/Herbert Gro\xcc\x88nemeyer/Was muss muss - Best of Herbert Gr\xc3\xb6nemeyer (Bonus Track Version)/1-03 Gl\xc3\xbcck.m4a'

**Comment by ericzolf** [comment]
We'll do our best to help you but none of us has MacOS and we're heavily working on the big next release, so fixes for 1.2.8 are unlikely to be an option, but let's have a try:

- Check the log files under /Users/steffen/.volumes/.backup_img/rdiff-backup-data for further hints what happened previously. Attach them to this report if you wish more help.
- Do the files `/Users/steffen/.volumes/.backup_img/Music/iTunes/iTunes Music/Music/Herbert Gro\xcc\x88nemeyer/Was muss muss - Best of Herbert Gr\xc3\xb6nemeyer (Bonus Track Version)/1-03 Gl\xc3\xbcck.m4a` resp. `/Users/steffen/.volumes/.backup_img/Music/iTunes/iTunes Music/Music/Herbert Grönemeyer/Was muss muss - Best of Herbert Grönemeyer (Bonus Track Version)/1-03 Glück.m4a`
- can you copy&paste the output of `ls -la /Users/steffen/.volumes/.backup_img/rdiff-backup-data`?
- how exactly did you call rdiff-backup this time and when it last failed?
- before we proceed further with trying to fix the repo, you should make a copy of it, by fear of making things even worse. The next step would be to call `rdiff-backup -v9 --check-destination-dir /Users/steffen/.volumes/.backup_img` and see if it brings us more information.

Can it be that you changed something recently to the way "Umlaut" are handled, especially at the file system level? OS upgrade, file system change, changes to LANG or LC_??? environment variables, ...?

**Comment by ottok** [comment]
Hello @Fischmuetze !

The code base has been rewritten for Python 3 and there will be no further releases for the 1.x series in Python 2 anymore. Could you please help our efforts and test again with the latest development version (https://github.com/rdiff-backup/rdiff-backup#installing-the-latest-development-version) if you can still reproduce this and provide us with a test case (steps on how to reproduce the issue) that applies for latest development version so if is easier to repeat this problem and try to fix it in the new code base and fix it in upcoming 2.x series releases?

**Comment by ericzolf** [comment]
No feedback, I close the issue. Feel free to re-open if you see fit, with more information.
