### ISSUE TITLE
Backup fails (throws exception) and cannot regress

### ISSUE THREAD

**Issue by BigCroc7** [rdiff-backup/rdiff-backup#250]
I attempted to backup a folder, but two things happened. Firstly, the backup operation threw an exception, and then secondly, check-destination failed to revert it. The folder has previously backed up successfully several times

Here are the traces:

Command: `rdiff-backup /home /backup`
Response:
`Exception '' raised of class '<type 'exceptions.AssertionError'>':`
`  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 306, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 326, in Main
    take_action(rps)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 282, in take_action
    elif action == "backup": Backup(rps[0], rps[1])`
`  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 345, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 51, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 253, in patch_and_increment
    cls.CCPP.close()
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 499, in close
    metadata.ManagerObj.ConvertMetaToDiff()
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/metadata.py", line 640, in ConvertMetaToDiff
    newrp, oldrp = self.check_needs_diff()
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/metadata.py", line 629, in check_needs_diff
    assert newrp.getinctype() == oldrp.getinctype() == 'snapshot'`

`Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 30, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 306, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 326, in Main
    take_action(rps)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 282, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 345, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 51, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 253, in patch_and_increment
    cls.CCPP.close()
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 499, in close
    metadata.ManagerObj.ConvertMetaToDiff()
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/metadata.py", line 640, in ConvertMetaToDiff
    newrp, oldrp = self.check_needs_diff()
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/metadata.py", line 629, in check_needs_diff
    assert newrp.getinctype() == oldrp.getinctype() == 'snapshot'
AssertionError`

Command: `rdiff-backup --check-destination-dir /backup`
Response:
`Fatal Error: No metadata for time Sat Jan 25 11:10:50 2020 (1579950650) found,
cannot regress`

**Comment by BigCroc7** [comment]
Well, I've fixed it for now, but, it doesn't fix the underlying problem... I don't even know what the underlying problem was. (I fixed it by deleting the backup metadata and increment files relating to the last two increments, and then it seemed to go ahead and backup properly. Haven't tried a restore yet though.)

**Comment by ericzolf** [comment]
Sorry for the delay. Without more information, I fear that we won't be able to offer any help (also given the fact that we're working on our new version). Would you mind closing this case?

**Comment by ikus060** [comment]
@BigCroc7 For completeness, could you describe steps or command line you ran in other to workaround your issue ?

**Comment by BigCroc7** [comment]
I ran the following commands, with [last-timestamp] as the time format shown in the filenames:

rm ./increments.[filename].[last-timestamp]    {this command I repeated for every file [filename] in the backup folder that had that timestamp - for me luckily this was only a few files, but could be many more}
rm ./current_mirror.[last-timestamp]
rm ./file_statistics.[last-timestamp]

Then to verify I had deleted everything:

rdiff-backup -l backup-folder
rdiff-backup --check-destination backup-folder

Then I re-ran the backup:

rdiff-backup folder backup-folder

Hope that helps someone!
