### ISSUE TITLE
Debian package version in 1.9.0b0 still shows version 1.4.0b1

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#252]
This was discovered in PR #234 and I have a suspicion that it is due to a mix of pip and apt installed packages, but no time for now to fix it properly. There is a workaround anyway.

**Comment by ericzolf** [comment]
@ottok please have a look at the latest beta release: the version of the Debian packages is wrong and still 1.4.0b1.

**Comment by ottok** [comment]
Indeed the source package version is wrong as is the binary package versions inside:
```
Format: 1.8
Date: Fri, 02 Aug 2019 21:01:40 +0100
Source: rdiff-backup
Binary: rdiff-backup
Architecture: source amd64
Version: 1.4.0b1
Distribution: unstable
Urgency: medium
Maintainer: Otto Kekäläinen <otto@debian.org>
Changed-By: Otto Kekäläinen <otto@debian.org>
Description:
 rdiff-backup - remote incremental backup
Changes:
 rdiff-backup (1.4.0b1) unstable; urgency=medium
 .
   * Initial changelog entry for native rdiff-backup packaging.
Checksums-Sha1:
 ff419f824ba663a1a1b7c627102287068dfbbe64 844 rdiff-backup_1.4.0b1.dsc
 9d98db41c9c2224dda4ab8f09cf9001efae03f96 243028 rdiff-backup_1.4.0b1.tar.xz
 a1cceb459d7486c6754d5118df50451e5f829aaf 28496 rdiff-backup-dbgsym_1.4.0b1_amd64.ddeb
 e260100c7d25cfa9e37d804c6908403484a0b203 7096 rdiff-backup_1.4.0b1_amd64.buildinfo
 a98f5ea08f1f4379c312103a18ac2e32f2228206 191432 rdiff-backup_1.4.0b1_amd64.deb
Checksums-Sha256:
 2863a6f7cb7841615d26ac644658283b5cb5abb58f439870a432ace7e63f9e24 844 rdiff-backup_1.4.0b1.dsc
 d4febc1cb55a2f27eeb4e4acbd85a7f7e9f2fc112b8353984e4f79337df31cf6 243028 rdiff-backup_1.4.0b1.tar.xz
 a8179cd3cfeebf102ac34edf732fadaad77ee7e3751e0cc8edb2cda528efe596 28496 rdiff-backup-dbgsym_1.4.0b1_amd64.ddeb
 af38949d0e711993074902c2715303c5b76ee6a5d52022b9b890a9553b931670 7096 rdiff-backup_1.4.0b1_amd64.buildinfo
 fcc83ecd3613a914188c6fc60cbd9d786a6479a212b8ecdd5f2fbadfe0ed3b81 191432 rdiff-backup_1.4.0b1_amd64.deb
Files:
 9cfec5b04f089110fe86ba2c8dfd612f 844 utils optional rdiff-backup_1.4.0b1.dsc
 7f3f8d5a8a9b5d04fa50232acedc65a8 243028 utils optional rdiff-backup_1.4.0b1.tar.xz
 ef3282cd596ff739e87e74ad4fd18926 28496 debug optional rdiff-backup-dbgsym_1.4.0b1_amd64.ddeb
 28ce4a15b4a51f765205ee168fb1581f 7096 utils optional rdiff-backup_1.4.0b1_amd64.buildinfo
 dda0fd64c2c76576296a08058882b3d3 191432 utils optional rdiff-backup_1.4.0b1_amd64.deb
```

![image](https://user-images.githubusercontent.com/668724/74191884-1e2a9c80-4c5d-11ea-98b1-9683eb95e30c.png)

**Comment by ottok** [comment]
Using `./setup.py --version` did not work reliably, so in `debian/rules` we are reading via proxy what the scm_version says from `src/rdiff_backup.egg-info/PKG-INFO`.


For some reason the build did not update the egg info..
```
$ git status --ignored
HEAD detached at v1.9.0b0
nothing to commit, working tree clean

$ make bdist_deb
...

rdiff-backup$ grep '^Version:' src/rdiff_backup.egg-info/PKG-INFO
Version: 1.4.0b1

rdiff-backup$ ./setup.py --version
your setuptools is too old (<12)
setuptools_scm functionality is degraded
1.9.0b0
```

**Comment by ottok** [comment]
Related, while I should figure out why the debian/rules does not work as intended I will not be able to dynamically ignore the debian/changelog version line in any setup, verified on debian-devel@ mailing list.

Maybe I need to rewrite this to modify debian/changelog before any runs and dismantle the automatic PPA integration after the clean checkout becomes unbuildable by itself..

**Comment by ottok** [comment]
My experiments with `./setup.py --version` on Launchpad seems to fail as it uses an export of git to build and thus the `.git` directory itself is not part of the build, and scm cannot read it:
```
Traceback (most recent call last):
  File "./setup.py", line 224, in <module>
    setup_requires=['setuptools_scm'],
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 448, in __init__
    k: v for k, v in attrs.items()
  File "/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 740, in finalize_options
    ep.load()(self)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 17, in version_keyword
    dist.metadata.version = _get_version(config)
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 147, in _get_version
    parsed_version = _do_parse(config)
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 118, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/<<PKGBUILDDIR>>'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```
