### ISSUE TITLE
Fail to restore file: '<' not supported between instances

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#266]
I'm starting to test the latest version of rdiff-backup with rdiffweb. I have a series of test that play hard with encoding and special character to make sure everything is well supported.

As a start, I have problem to restore file containing '<' in their name. rdiff-backup is failing with an exception.

Here the step to reproduce.
```
$ wget https://git.patrikdufresne.com/pdsl/rdiffweb/raw/master/rdiffweb/tests/testcases.tar.gz
$ tar -zxvf testcases.tar.gz
$ rdiff-backup --version
rdiff-backup 1.9.0b0
$ rdiff-backup --restore-as-of=1414921853 '/testcases/Fichier @ <root>'
Fatal Error: Wrong number of arguments given.
See the rdiff-backup manual page for more information.
root@b94a5e7b3814:/# rdiff-backup --restore-as-of=1414921853 '/testcases/Fichier @ <root>' /tmp
Warning: special_escapes file not found,
will assume need to escape DOS devices and trailing spaces based on file systems.
Exception ''<' not supported between instances of 'QuotedRPath' and 'QuotedRPath'' raised of class '<class 'TypeError'>':
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/Main.py", line 368, in take_action
    Restore(rps[0], rps[1], 1)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/Main.py", line 713, in Restore
    restore_root.new_index(restore_index), inc_rpath, dest_rp, time)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 39, in Restore
    TargetS.patch(target, diff_iter)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 331, in patch
    for diff in rorpiter.FillInIter(diff_iter, target):
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/rorpiter.py", line 191, in FillInIter
    first_rp = next(rpiter)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 279, in get_diffs_from_collated
    diff = cls.get_diff(mir_rorp, target_rorp)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 296, in get_diff
    file_fp = cls.rf_cache.get_fp(expanded_index, mir_rorp)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 391, in get_fp
    self.get_rf(index, mir_rorp), mir_rorp, self.root_rf.mirror_rp)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 371, in get_rf
    if not self.add_rfs(index, mir_rorp):
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 417, in add_rfs
    new_rfs = list(temp_rf.yield_sub_rfs())
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 589, in yield_sub_rfs
    yield self.__class__(mirror_rp, inc_rp, inc_list)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 442, in __init__
    self.set_relevant_incs()
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 468, in set_relevant_incs
    newer_incs = self.get_newer_incs()
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 494, in get_newer_incs
    incpairs.sort()

Traceback (most recent call last):
  File "/usr/local/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/Main.py", line 368, in take_action
    Restore(rps[0], rps[1], 1)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/Main.py", line 713, in Restore
    restore_root.new_index(restore_index), inc_rpath, dest_rp, time)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 39, in Restore
    TargetS.patch(target, diff_iter)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 331, in patch
    for diff in rorpiter.FillInIter(diff_iter, target):
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/rorpiter.py", line 191, in FillInIter
    first_rp = next(rpiter)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 279, in get_diffs_from_collated
    diff = cls.get_diff(mir_rorp, target_rorp)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 296, in get_diff
    file_fp = cls.rf_cache.get_fp(expanded_index, mir_rorp)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 391, in get_fp
    self.get_rf(index, mir_rorp), mir_rorp, self.root_rf.mirror_rp)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 371, in get_rf
    if not self.add_rfs(index, mir_rorp):
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 417, in add_rfs
    new_rfs = list(temp_rf.yield_sub_rfs())
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 589, in yield_sub_rfs
    yield self.__class__(mirror_rp, inc_rp, inc_list)
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 442, in __init__
    self.set_relevant_incs()
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 468, in set_relevant_incs
    newer_incs = self.get_newer_incs()
  File "/usr/local/lib/python3.7/dist-packages/rdiff_backup/restore.py", line 494, in get_newer_incs
    incpairs.sort()
TypeError: '<' not supported between instances of 'QuotedRPath' and 'QuotedRPath'
```

The same steps with rdiff-backup v1.2.8 is working very well without issue and the file get restored.

**Comment by ericzolf** [comment]
Strange, I can reproduce the issue with your steps and testfiles, but I'm not able to create a repo myself, which shows the issue.

**Comment by ikus060** [comment]
Funny! The repository was created using rdiff-backup 1.2.8 back then.

I did not had the chances to check what might be the issue or anything. I just started testing the new release with rdiffweb and that test failed. I also have alot of other test to check the encoding for non utf-8 character and all of them pass properly. Only this test is failing.

**Comment by ericzolf** [comment]
Actually, the `<` seems to have nothing to do with any special character but means that QuotedRPath objects can't be compared, which is a pre-requisite for sorting those objects.

Why does this issue happen with your repo and none other is a different question, for another day...

**Comment by ericzolf** [comment]
I've tried:

```
rdiff-backup -v9 --restore-as-of=5B /var/tmp/testcases /tmp/out5
rdiff-backup -v9 --restore-as-of=6B /var/tmp/testcases /tmp/out6
```

And the first command succeeds while the 2nd one fails. Still doesn't make much sense to me...

**Comment by ericzolf** [comment]
The function `get_newer_incs` sorts a list of tuples with date and QuotedRPath objects. As long as the dates are all different, the QuotedRPath objects don't need to be compared, and everything is fine, but if two dates are the same, then we get the given error during the sort.

The question is now how two versions of the same file with the same date/time come into this list. It seems that there is some confusion between the files `Char ;059090 to quote`, `Char ;090 to quote` and `Char Z to quote` (`;059` is the quote for `;` and `;090` the one for Z).

**Comment by ericzolf** [comment]
A bit of progress to report:

- the function `yield_sub_rfs` in `restore.py` is the one generating the `inc_list` list, which itself leads to the issue when being sorted (indirectly, that's the short story).
- as far as I can see `inc_pair_iter = self.yield_inc_complexes(self.inc_rp)` is already broken, as the iterator generates pairs mismatched between inc_rp and inc_list, but only if the name contains a character being quoted (Z or ; basically), there seems to be one quoting too much being done, or something like that.
- the file `/var/tmp/testcases/rdiff-backup-data/chars_to_quote` contains "Z", which explains why it's being quoted.

As a side note, I created #271 to document a new learning about debugging iterators.

**Comment by ericzolf** [comment]
One step further:
* `yield_sub_rfs` gets a list of mirror with `yield_mirrorrps` and a list of increments with `yield_inc_complexes`, and combines them using `rorpiter.Collate2Iters`. Already the list of increments provided by `yield_inc_complexes` is wrong.
* it appears that the list provided by `get_inc_pairs` is already wrong
* which is due to `rpath.getincbase_bname()` sending back the wrong basename for the increment
* which is due to `self.inc_basestr` being wrong from the beginning...
