### ISSUE TITLE
particular long cyrillic dirname breaks backup

### ISSUE THREAD

**Issue by legolegs** [rdiff-backup/rdiff-backup#295]
I caught an issue on my data. A directory with particular long but correct name being backed up breaks backup.

I have tried both `rdiff-backup 1.9.2rc0` and 1.9.1b0.
System: Fedora 29 x64, filesystem - both ext4 and tmpfs tested, locale ru_RU.UTF-8.

How to reproduce:
```bash
mkdir source backup
touch source/file
rdiff-backup source/ backup/ #fist
mkdir source/'ггггггггг1ггггггггг2ггггггггг3ггггггггг4ггггггггг5ггггггггг6ггггггггг7ггггггггг8ггггггггг9.ггггггггг0._'
rdiff-backup source/ backup/ #second
rdiff-backup --list-increment-sizes backup/
```
Got this:
```
Exception ''ascii' codec can't decode byte 0xd0 in position 1: ordinal not in range(128)' raised of class '<class 'UnicodeDecodeError'>':
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/Main.py", line 362, in take_action
    ListIncrementSizes(rps[0])
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/Main.py", line 917, in ListIncrementSizes
    print(manage.ListIncrementSizes(restore_root, restore_index))
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/manage.py", line 220, in ListIncrementSizes
    time_dict = get_time_dict(get_inc_select())
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/manage.py", line 167, in get_time_dict
    if not inc.isincfile():
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/rpath.py", line 1494, in isincfile
    inc_info = get_incfile_info(basename)
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/rpath.py", line 474, in get_incfile_info
    if Time.bytestotime(timestring) is None:
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/Time.py", line 123, in bytestotime
    return stringtotime(timebytes.decode('ascii'))

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/Main.py", line 362, in take_action
    ListIncrementSizes(rps[0])
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/Main.py", line 917, in ListIncrementSizes
    print(manage.ListIncrementSizes(restore_root, restore_index))
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/manage.py", line 220, in ListIncrementSizes
    time_dict = get_time_dict(get_inc_select())
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/manage.py", line 167, in get_time_dict
    if not inc.isincfile():
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/rpath.py", line 1494, in isincfile
    inc_info = get_incfile_info(basename)
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/rpath.py", line 474, in get_incfile_info
    if Time.bytestotime(timestring) is None:
  File "/usr/lib64/python3.7/site-packages/rdiff_backup/Time.py", line 123, in bytestotime
    return stringtotime(timebytes.decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 1: ordinal not in range(128)
```

`--verify` and `--restore` also stop working too with similar UnicodeDecodeError.

The reproducing is a bit finicky. Above I suggest two-step approach because (as I found out trough experimenting) it works (or rather consistently fails), but on my real data I got this bug from the first (initial) backup of a particular workstation. I think triggering the issue might be affected by the order in which kernel gives names stored in directory (which is unspecified in general).

**Comment by legolegs** [comment]
PS tested with Python 3.7.4 and with Python 3.5.2

**Comment by zjw** [comment]
PR #297 contains a proposed fix for this issue.

**Comment by zjw** [comment]
Thanks, @legolegs, for the bug report.  Being able to reproduce the error was useful.
