### ISSUE TITLE
Exception ''<' not supported between instances of 'RPath' and 'RPath'' at backup

### ISSUE THREAD

**Issue by MarcvdSluys** [rdiff-backup/rdiff-backup#322]
I recently updated from rdiff-backup 1.3 to 2.0 and got the exception below during my first backup since that update. Reverting to 1.3 regressed the backup and worked without further issues.  This sounds very similar to fixed issue #266, which was part of the 2.0.0 milestone.  However, I **am** using v2.0.0.  Is this a bug, on an issue with jumping so many versions (Gentoo Linux jumped from 1.3.3 to 2.0.0)?

`Exception ''<' not supported between instances of 'RPath' and 'RPath'' raised of class '<class 'TypeError'>':
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 434, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 52, in Mirror_and_increment
    DestS.set_rorp_cache(dest_rpath, source_rpiter, 1)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 180, in set_rorp_cache
    dest_iter = cls.get_dest_select(baserp, for_increment)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 165, in get_dest_select
    rorp_iter = metadata.ManagerObj.GetAtTime(Time.prevtime)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 611, in GetAtTime
    cur_iter = self.get_meta_at_time(time, restrict_index)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 770, in get_meta_at_time
    for rp in self.relevant_meta_incs(time)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 780, in relevant_meta_incs
    inclist = self.sorted_prefix_inclist(b'mirror_metadata', min_time=time)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 729, in sorted_prefix_inclist
    sortlist.sort()

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 434, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 52, in Mirror_and_increment
    DestS.set_rorp_cache(dest_rpath, source_rpiter, 1)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 180, in set_rorp_cache
    dest_iter = cls.get_dest_select(baserp, for_increment)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 165, in get_dest_select
    rorp_iter = metadata.ManagerObj.GetAtTime(Time.prevtime)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 611, in GetAtTime
    cur_iter = self.get_meta_at_time(time, restrict_index)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 770, in get_meta_at_time
    for rp in self.relevant_meta_incs(time)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 780, in relevant_meta_incs
    inclist = self.sorted_prefix_inclist(b'mirror_metadata', min_time=time)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 729, in sorted_prefix_inclist
    sortlist.sort()
TypeError: '<' not supported between instances of 'RPath' and 'RPath'
`

**Comment by ericzolf** [comment]
The version jump doesn't matter. Can you please:

1. Call `rdiff-backup -v9` and provide the output?
2. Tell us which command and parameters exactly you used?
3. if you can reproduce the issue, call the same command with highest verbosity and provide the output.

**Comment by MarcvdSluys** [comment]
Thank you for looking into this.  The issue occurs right at the beginning.  Here are the three pieces of information you asked for:

**1. rdiff-backup -v9:**
```
$ rdiff-backup -v9
2020-04-18 10:19:47.608656 +0200  <CLIENT-32369>  Using rdiff-backup version 2.0.0
2020-04-18 10:19:47.608778 +0200  <CLIENT-32369>        with cpython /usr/bin/python3.6 version 3.6.10
2020-04-18 10:19:47.613005 +0200  <CLIENT-32369>        on Linux-4.9.76-gentoo-r1.005-x86_64-Intel-R-_Core-TM-_i7-3520M_CPU_@_2.90GHz-with-gentoo-2.6, fs encoding utf-8
2020-04-18 10:19:47.613128 +0200  <CLIENT-32369>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.
```

**2. command** (normally without the `-v9`):
```
$ rdiff-backup \
    -v9 \
    --print-statistics \
    --exclude '/home/$USER/diverse/OldMail/**' \
    --exclude '/home/$USER/diverse/popular/Hemel_compare' \
    --exclude '/home/$USER/Downloads/**' \
    --exclude '/home/$USER/temp/**' \
    --exclude '/home/$USER/.attach/**' \
    --exclude '/home/$USER/.mozilla/firefox/n2fgt4b0.default/Cache/**' \
    /home/$USER /mnt/Backup/Backup/$HOSTNAME/home/$USER
```

**3. output** of the command above:

```
2020-04-18 10:08:17.245337 +0200  <CLIENT-17303>  Using rdiff-backup version 2.0.0
2020-04-18 10:08:17.245442 +0200  <CLIENT-17303>        with cpython /usr/bin/python3.6 version 3.6.10
2020-04-18 10:08:17.249487 +0200  <CLIENT-17303>        on Linux-4.9.76-gentoo-r1.005-x86_64-Intel-R-_Core-TM-_i7-3520M_CPU_@_2.90GHz-with-gentoo-2.6, fs encoding utf-8
2020-04-18 10:08:17.555455 +0200  <CLIENT-17303>  Unable to import win32security module. Windows ACLs
not supported by filesystem at /home/$USER
2020-04-18 10:08:17.558884 +0200  <CLIENT-17303>    -----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
2020-04-18 10:08:17.558985 +0200  <CLIENT-17303>  Making directory /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0
2020-04-18 10:08:17.581922 +0200  <CLIENT-17303>  Touching /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/5-_ a.snapshot.gz
2020-04-18 10:08:17.582096 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/5-_ a.snapshot.gz
2020-04-18 10:08:17.582212 +0200  <CLIENT-17303>  Touching /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/uniá
2020-04-18 10:08:17.582325 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/uniá
2020-04-18 10:08:17.582427 +0200  <CLIENT-17303>  Touching /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/:\"
2020-04-18 10:08:17.582517 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/:\"
2020-04-18 10:08:17.582609 +0200  <CLIENT-17303>  Touching /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/A
2020-04-18 10:08:17.582722 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/A
2020-04-18 10:08:17.582813 +0200  <CLIENT-17303>  Touching /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/foo
2020-04-18 10:08:17.582930 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/foo
2020-04-18 10:08:17.583044 +0200  <CLIENT-17303>  Making directory /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/hl
2020-04-18 10:08:17.604334 +0200  <CLIENT-17303>  Touching /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/hardlinked_file1
2020-04-18 10:08:17.604533 +0200  <CLIENT-17303>  Hard linking /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/hl/hardlinked_file2 to /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/hardlinked_file1
2020-04-18 10:08:17.605970 +0200  <CLIENT-17303>  Unable to import win32security module. Windows ACLs
not supported by filesystem at /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0
2020-04-18 10:08:17.606085 +0200  <CLIENT-17303>  Touching /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/dir_inc_check
2020-04-18 10:08:17.606235 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/dir_inc_check
2020-04-18 10:08:17.606354 +0200  <CLIENT-17303>  Touching /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/regfile
2020-04-18 10:08:17.606467 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/regfile
2020-04-18 10:08:17.607792 +0200  <CLIENT-17303>  Touching /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_file
2020-04-18 10:08:17.608283 +0200  <CLIENT-17303>  Touching /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir
2020-04-18 10:08:17.608432 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_file
2020-04-18 10:08:17.608505 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir
2020-04-18 10:08:17.608596 +0200  <CLIENT-17303>  Touching /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/symlinked_file1
2020-04-18 10:08:17.608782 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/symlinked_file2
2020-04-18 10:08:17.608841 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/symlinked_file1
2020-04-18 10:08:17.608972 +0200  <CLIENT-17303>  Touching /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/foo
2020-04-18 10:08:17.609063 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0/foo
2020-04-18 10:08:17.609120 +0200  <CLIENT-17303>  Deleting /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0
2020-04-18 10:08:17.609153 +0200  <CLIENT-17303>  Removing directory /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/rdiff-backup.tmp.0
2020-04-18 10:08:17.609449 +0200  <CLIENT-17303>  -----------------------------------------------------------------
Detected abilities for destination (read/write) file system:
  Ownership changing                           Off
  Hard linking                                 On
  fsync() directories                          On
  Directory inc permissions                    On
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   Off
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
2020-04-18 10:08:17.612205 +0200  <CLIENT-17303>  Backup: escape_dos_devices = 0
2020-04-18 10:08:17.612252 +0200  <CLIENT-17303>  Backup: escape_trailing_spaces = 0
2020-04-18 10:08:17.858548 +0200  <CLIENT-17303>  Writing mirror marker /mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/current_mirror.2020-04-18T10:08:17+02:00.data
2020-04-18 10:08:17.891489 +0200  <CLIENT-17303>  Starting increment operation /home/$USER to /mnt/Backup/Backup/$HOSTNAME/home/$USER
2020-04-18 10:08:18.650668 +0200  <CLIENT-17303>  Exception ''<' not supported between instances of 'RPath' and 'RPath'' raised of class '<class 'TypeError'>':
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 434, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 52, in Mirror_and_increment
    DestS.set_rorp_cache(dest_rpath, source_rpiter, 1)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 180, in set_rorp_cache
    dest_iter = cls.get_dest_select(baserp, for_increment)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 165, in get_dest_select
    rorp_iter = metadata.ManagerObj.GetAtTime(Time.prevtime)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 611, in GetAtTime
    cur_iter = self.get_meta_at_time(time, restrict_index)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 770, in get_meta_at_time
    for rp in self.relevant_meta_incs(time)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 780, in relevant_meta_incs
    inclist = self.sorted_prefix_inclist(b'mirror_metadata', min_time=time)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 729, in sorted_prefix_inclist
    sortlist.sort()

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 434, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 52, in Mirror_and_increment
    DestS.set_rorp_cache(dest_rpath, source_rpiter, 1)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 180, in set_rorp_cache
    dest_iter = cls.get_dest_select(baserp, for_increment)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 165, in get_dest_select
    rorp_iter = metadata.ManagerObj.GetAtTime(Time.prevtime)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 611, in GetAtTime
    cur_iter = self.get_meta_at_time(time, restrict_index)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 770, in get_meta_at_time
    for rp in self.relevant_meta_incs(time)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 780, in relevant_meta_incs
    inclist = self.sorted_prefix_inclist(b'mirror_metadata', min_time=time)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/metadata.py", line 729, in sorted_prefix_inclist
    sortlist.sort()
TypeError: '<' not supported between instances of 'RPath' and 'RPath'
```

**Comment by ericzolf** [comment]
Not easy to reproduce... Sorry, I might need a bit more informaton:

1. What are the filesystems of source and target?
2. I understand that the initial repo was created with 1.2/1.3 and you're doing an increment with 2.0, correct?
3. Does it also happen if you do an initial backup with 2.0 to a new directory?
4. Does it appear if you do some changes in the source and do again a backup?

I'll continue to search on my side, but the easiest you make it for me to reproduce the issue, the faster I can be...

**Comment by MarcvdSluys** [comment]
No need to apologise when you're trying to help me :-)

1. Both are ext4
2. I was using 1.3.3 until recently.  However, the original backup was with made 1.0 or earlier (I have incomplete system logs from that time, but I can see I installed v1.0.5 on 2009-07-02).  Anyway everything worked fine until I updated to v2.0.0, and the problems go away when I downgrade to 1.3.3.
3. No, that works fine
4. No, that works fine too.

Note, what I did for 3. and 4. is the backup of a different (and much smaller, for speed) selection of data than normal (which is my home dir with some exceptions).  Hence, for 3. I used different data, to a different target dir (but on the same HD).  For 4., I made some changes in the data files from 3. and made a second backup.  (I have saved the `-v9` output, it case that is useful.)

**Comment by ericzolf** [comment]
OK, the issue probably happens when two increments have the same date stamp, which should be impossible IMHO, but perhaps it was possible in the past... Can you please send me the output of `/mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/mirror_metadata*`?

Background: the sorting happens on a tuple of date + RPath, if the dates are the same, the two RPath corresponding to the files are compared, which then fails, quite correctly actually (I'm not sure what RPath should compare against).

**Comment by MarcvdSluys** [comment]
Do you mean `ls mirror_metadata*` to see all the file names?  There are [769 of them](https://gist.github.com/MarcvdSluys/27c463eb4ab50f8ce1211cca4bb76641)...

**Comment by ericzolf** [comment]
I only needed the list as you provided. Thanks. It indeed shows that the repository contains two entries at the same date, once as diff, once as snapshot:

```
mirror_metadata.2011-07-25T22:14:52+02:00.diff.gz
mirror_metadata.2011-07-25T22:14:52+02:00.snapshot.gz
```
It could be rather easy to fix, but the problem is that the diff could be before or after the snapshot, and I don't think, I have a way to know. Also it seems to me that it is an inconsistency of the repository.

**Comment by MarcvdSluys** [comment]
I apologise for making you search for a bug, which is in reality my crooked repository.  Is there a way of fixing this by renaming one of the files, or changing the repo with v1.3.3?

**Comment by ericzolf** [comment]
That sounds like a plan to me indeed, but I'd like to understand a bit more what's happening and if I could make rdiff-backup slightly more robust for these kind of cases, if you don't mind helping me understand what's going on before you fix your repository.

Can you tell me if `rdiff-backup --list-increments /mnt/Backup/Backup/$HOSTNAME/home/$USER` works with 1.3.3 and 2.0.0 (I expect yes and no), and
1. what do you get for increments around the 25th of July with 1.3.3?
2. I would also expect a list of 768 increments by 1.3.3?
3. which error does rdiff-backup 2.0.0 spit out, if it does?

Regarding the timestamps of the files, they're indeed rather strange because they should be for snapshots aligned with the filename, and for diffs aligned with the filename of the diff or snapshot just after, and this is definitely not the case for the duplicate ones... It's perhaps due to some manual intervention, a regress, or a bug in rdiff-backup at that time, absolutely no clue.

My idea would be to fail on such duplicates by default but allow to overcome the failure in order to be able to regress and prune such duplicates, like you plan to do with 1.3.3. I just want to be sure I don't oversee something before I go in this direction, hopefully with your help.

**Comment by ericzolf** [comment]
And I probably know why 1.3.3 didn't fail, it's most probably because [Python 2 states](https://docs.python.org/2.7/reference/expressions.html#value-comparisons):

> Most other objects of built-in types compare unequal unless they are the same object; the choice whether one object is considered smaller or larger than another one is made arbitrarily but consistently within one execution of a program.

Whereas [Python 3 states](https://docs.python.org/3/reference/expressions.html#value-comparisons):

> A default order comparison (<, >, <=, and >=) is not provided; an attempt raises TypeError. A motivation for this default behaviour is the lack of a similar invariant as for equality.

In other words, rdiff-backup with Python 2 was consistently but arbitrarily comparing RPath objects... \*shudder\*

**Comment by ericzolf** [comment]
And as a side note: you know that you have an issue if the output of the following command is **not** empty: `cd MY_BACKUP_REPO; ls -1 rdiff-backup-data/mirror_metadata.* | sed -e 's/^.*mirror_metadata\.//' -e 's/\.[a-z]*.gz$//' | uniq -cd`. It might help someone else...

**Comment by MarcvdSluys** [comment]
OK, I'll do that before I try to fix things, I owe it to you for all your help :-)  I need to do some other things first, but I'll get back to you here.

**Comment by MarcvdSluys** [comment]
What I did before I started doing the stuff below is to downgrade to v1.3.3 and do a new backup (which takes an hour since it has to regress because the last backup (using v2.0.0) failed).

> Can you tell me if `rdiff-backup --list-increments /mnt/Backup/Backup/$HOSTNAME/home/$USER` works with 1.3.3 and 2.0.0 (I expect yes and no), and

* v1.3.3: works
* v2.0.0: works too.  The two lists are identical

>     1. what do you get for increments around the 25th of July with 1.3.3?
```
    increments.2011-06-09T08:49:23+02:00.dir   Thu Jun  9 08:49:23 2011
    increments.2011-06-12T16:46:04+02:00.dir   Sun Jun 12 16:46:04 2011
    increments.2011-06-13T23:47:21+02:00.dir   Mon Jun 13 23:47:21 2011
    increments.2011-06-20T10:36:47+02:00.dir   Mon Jun 20 10:36:47 2011
    increments.2011-06-29T08:39:39+02:00.dir   Wed Jun 29 08:39:39 2011
    increments.2011-07-21T09:03:49+02:00.dir   Thu Jul 21 09:03:49 2011
    increments.2011-07-25T22:14:52+02:00.dir   Mon Jul 25 22:14:52 2011
    increments.2011-08-03T14:31:03+02:00.dir   Wed Aug  3 14:31:03 2011
    increments.2011-08-19T19:31:11+02:00.dir   Fri Aug 19 19:31:11 2011
    increments.2011-08-27T15:50:22+02:00.dir   Sat Aug 27 15:50:22 2011
    increments.2011-08-27T18:49:34+02:00.dir   Sat Aug 27 18:49:34 2011
```
 
>     2. I would also expect a list of 768 increments by 1.3.3?
Correct: `Found 768 increments:`, confirmed by wc -l (which finds 770 because of the header and footer lines).

>     3. which error does rdiff-backup 2.0.0 spit out, if it does?
It doesn't.

> Regarding the timestamps of the files, they're indeed rather strange because they should be for snapshots aligned with the filename, and for diffs aligned with the filename of the diff or snapshot just after, and this is definitely not the case for the duplicate ones... It's perhaps due to some manual intervention, a regress, or a bug in rdiff-backup at that time, absolutely no clue.

As I said, it is quite possible that I did this manually myself - I wouldn't use this case to see whether rdiff-backup caused it.

> My idea would be to fail on such duplicates by default but allow to overcome the failure in order to be able to regress and prune such duplicates, like you plan to do with 1.3.3. I just want to be sure I don't oversee something before I go in this direction, hopefully with your help.

I'll help you until the issue is closed (if it really takes too much time, I'll let you know ;-)).

**Comment by zjw** [comment]
When rdiff-backup runs, it creates a mirror-metadata file of type 'snapshot' for the current backup.  When the backup is complete, the program decides whether or not to convert the mirror-metadata file for the previous backup from a type 'snapshot' to a type 'diff'.  The criteria used to decide is that there shall never be more that 8 diff files in a row (every 9th file is of type snapshot).  The process of conversion consists of creating and writing a diff file (with a timestamp matching that of the previous backup) which contains the differences between the current mirror-metadata snapshot and the previous mirror-metadata snapshot.  Once that diff file is written, then the snapshot file of the previous backup is deleted (see `oldrp.delete()` in `ConvertMetaToDiff(self)`).

I suspect the problem here is that the diff file was created (mirror_metadata.2011-07-25T22:14:52+02:00.diff.gz), but that the deletion of the snapshot file (mirror_metadata.2011-07-25T22:14:52+02:00.snapshot.gz) failed for unknown reasons, thus leaving two mirror-metadata files with the same timestamp.

It should be possible to confirm my theory.  Running `ls -l mirror_metadata.2011-07-25T22:14:52+02:00*` will show when the 2 files were last modified.  In all likelihood, the diff file will have been modified at about 2011-08-03T14:31:03+02:00 (or shortly thereafter, depending how long the backup took), and the snapshot file will have been modified 9 days earlier at about 2011-07-25T22:14:52+02:00.

It should also be possible to compare the files (using bash):
```
diff -u <(zcat mirror_metadata.2011-07-25T22:14:52+02:00.diff.gz) <(zcat mirror_metadata.2011-07-25T22:14:52+02:00.snapshot.gz)
```
For the most part, everything in the diff file should exist in the snapshot file, so the output of the above command should not have any lines that begin with '-', with the notable exception that new files created after the 2011-07-25 backup will appear in the output like this:
```
-File <filename>
-  Type None
```

If what I suggest above checks out, then it should be okay to delete the mirror_metadata.2011-07-25T22:14:52+02:00.diff.gz file.  (However, for safety I suggest renaming it or moving it rather than deleting it.)  Your repository should then be okay.

**Comment by ericzolf** [comment]
Marc provided the "timestamps for these and adjacent files" in a previous comment and the dates don't fully fit your theory. I would nevertheless not rule out that you're right and that there isn't another effect changing the dates afterwards, given that python2 can't sort properly between diff and snapshot when the date/time is the same.

And I learnt a new bash-construct :wink: (zdiff works as well).

**Comment by ericzolf** [comment]
I created a fix for this issue in #328 . I still need to properly test and document it, but it should already be functional. if you could give it a try on a copy of your repo, that would be much appreciated, else wait until I'm finished.

**Comment by MarcvdSluys** [comment]
I'm quite busy at the moment, but this is on my to-do list and will do (probably some time next week).

**Comment by MarcvdSluys** [comment]
@zjw  Thanks for thinking along!

[https://gist.github.com/MarcvdSluys/509888efae11208f5ff8fb57c88282ca](Here) is a list of diffs and snapshot with file sizes and timestamps around the time of interest.  As @ericzolf said, it doesn't quite add up.  I did a `zdiff` between the snapshot and both the previous and the next diff, but about 1% and 10% respectively of lines are removals (starting with -).

I also looked at normal cases, which seem to follow the pattern:
1. **diff** with filename as timestamp of previous diff
2. **diff** with filename as timestamp of previous diff
3. **snapshot** with filename as timestamp of previous diff **and itself**, half a minute younger than previous diff
4. **diff** with filename as timestamp of **NO OTHER FILE**, between timestamp of last snapshot/diff and timestamp of self
5. **diff** with filename as timestamp of previous diff
6. **diff** with filename as timestamp of previous diff

Also, (zipped) diffs tend to have sizes of 10's to 100's of kb, snapshots of ~7-8Mb.

In my weird case, 1., 2. and 6. are the same, but 3.-5. are different:

3. **snapshot** with filename as timestamp of **TWO DIFFS AGO**, **BUT NOT itself**, **AND IDENTICAL TO PREVIOUS DIFF** and **2 HOURS** younger than the **NEXT DIFF**
4. **diff** with filename as timestamp of **NO OTHER FILE**, between timestamp of last snapshot/diff and timestamp of self
5. **diff** with filename as timestamp of **TWO DIFFS AGO**, **UNUSUALLY LARGE FILE SIZE** (more like snapshot than diff)

I don't know what the unusual file size of the diff means, but perhaps this could mean a backup went wrong on 2011-08-19, was regressed ~2 hours later, but the issue wasn't fully resolved.

**Comment by MarcvdSluys** [comment]
Great, this works and I'm on v2.0 now :-).  There's one small issue - after I regressed my last failed backup using `--check-destination-dir --allow-duplicate-timestamps` and tried to do a normal backup, I got

```Fatal Error: Metadata file '/mnt/Backup/Backup/$HOSTNAME/home/$USER/rdiff-backup-data/mirror_metadata.2011-07-25T22:14:52+02:00.snapshot.gz' has a duplicate timestamp date, you might not be able to recover files on or earlier than this date. Check the man page on how to clean up your repository using the '--allow-duplicate-timestamps' option.```

as designed.  However, it **also** tried to do an actual backup, changing and corrrupting the repo again, since it couldn't really do a backup.  Hence I had to reregress.  I'm not sure whether *this* is intended.

After a regress, `--list-increments` and `--remove-older-than` work (I got a bit of a shock at the "Fatal error" when invoking `--remove-older-than` without `--force`; should that be a warning?), after which I could do a normal backup with your new "v2.0.1" from git (and then again succesfully with v2.0.0 still provided by Gentoo).  Thank you so much for your help!

**Comment by ericzolf** [comment]
The regress can't be avoided without more major changes to the code, which I think aren't worth it (at least not before I've found the time to restructure the code and simplify it).

The fatal error on trying to remove more than one backup at once is a bit harsh, I admit :smile: but it's not a regression, it existed before I took over the code, a warning would be too soft, and the code doesn't know anything in-between, so same answer as above: once I've simplified the code, we can think about adding new features (and hence new complexity).

**Comment by MarcvdSluys** [comment]
Fair enough.  Good luck with your very useful code and thanks again for your help!
