### ISSUE TITLE
[BUG] Two instances of rdiff-backup cannot run at the same time

### ISSUE THREAD

**Issue by glsubri** [rdiff-backup/rdiff-backup#334]
## Bug summary
I installed rdiff-backup via pip on a Synology NAS. Turns out that if I start to backup and then my wife does, my instance of rdiff-backup will be stopped.

### My OS
I'm running Gentoo GNU/Linux, my kernel version is 5.4.28.
```
2020-04-27 10:59:42.368553 +0200  <CLIENT-20171>  Using rdiff-backup version 2.0.0
2020-04-27 10:59:42.368671 +0200  <CLIENT-20171>  	with cpython /usr/bin/python3.7 version 3.7.7
2020-04-27 10:59:42.386051 +0200  <CLIENT-20171>  	on Linux-5.4.28-gentoo-x86_64-Intel-R-_Core-TM-_i5-8350U_CPU_@_1.70GHz-with-gentoo-2.6, fs encoding utf-8
```

### My wife's OS
She's running Elementary OS.
```
2020-04-27 11:02:55.966112 +0200  <CLIENT-13002>  Using rdiff-backup version 2.0.0
2020-04-27 11:02:55.966220 +0200  <CLIENT-13002>    with cpython /usr/bin/python3 version 3.6.9
2020-04-27 11:02:55.969707 +0200  <CLIENT-13002>    on Linux-5.3.0-46-generic-x86_64-with-elementary-5.1.3-hera, fs encoding utf-8
```

### Synology NAS
```
2020-04-27 11:18:50.696935 +0200  <CLIENT-12239>  Using rdiff-backup version 2.0.0
2020-04-27 11:18:50.697155 +0200  <CLIENT-12239>  	with cpython /usr/local/bin/python3 version 3.5.1
2020-04-27 11:18:50.712178 +0200  <CLIENT-12239>  	on Linux-4.4.59+-x86_64-with-glibc2.3.4, fs encoding utf-8
```

## rdiff-backup call

I made a simple script. In it, the call to rdiff-backend looks like this:
```
sshpass -p "${pass}" rdiff-backup \
    --verbosity 5 \
    --exclude-globbing-filelist ${user_dir}/bin/backups/user.txt \
    ${user_dir} \
    "${dest_user}@${dest_ip}::${dest_dir}${name}"
```

## What happened and what did you expect?

If I start the script on any of the computers, it works without any problem. The issue is only when the two scripts are run at the same time: the first instance of rdiff-backup is stopped.

## More information

Modifying my script to launch with `-v9` here's the output I have when my backup is being interrupted
```
2020-04-27 11:33:26.165543 +0200  <SERVER-12740>  Getting signature of .config/R/lib/isoband/Meta/package.rds with blocksize 64
2020-04-27 11:33:26.167107 +0200  <SERVER-12740>  Getting signature of .config/R/lib/isoband/Meta/vignette.rds with blocksize 64
2020-04-27 11:33:26.168661 +0200  <SERVER-12740>  Getting signature of .config/R/lib/isoband/NAMESPACE with blocksize 64
2020-04-27 11:33:26.170239 +0200  <SERVER-12740>  Getting signature of .config/R/lib/isoband/NEWS.md with blocksize 64
2020-04-27 11:33:26.172790 +0200  <SERVER-12740>  Getting signature of .config/R/lib/isoband/R/isoband with blocksize 64
2020-04-27 11:33:26.174522 +0200  <SERVER-12740>  Getting signature of .config/R/lib/isoband/R/isoband.rdb with blocksize 96
2020-04-27 11:33:26.176391 +0200  <SERVER-12740>  Getting signature of .config/R/lib/isoband/R/isoband.rdx with blocksize 64
2020-04-27 11:33:26.178830 +0200  <SERVER-12740>  Getting signature of .config/R/lib/isoband/doc/index.html with blocksize 64
2020-04-27 11:33:26.180570 +0200  <SERVER-12740>  Getting signature of .config/R/lib/isoband/doc/isoband1.R with blocksize 64
2020-04-27 11:33:26.182159 +0200  <SERVER-12740>  Getting signature of .config/R/lib/isoband/doc/isoband1.Rmd with blocksize 64
2020-04-27 11:33:26.183957 +0200  <SERVER-12740>  Getting signature of .config/R/lib/isoband/doc/isoband1.html with blocksize 288
2020-04-27 11:33:26.186264 +0200  <SERVER-12740>  Getting signature of .config/R/lib/isoband/doc/isoband2.R with blocksize 64
2020-04-27 11:32:04.114822 +0200  <CLIENT-18149>  Client received (225): 'xattr'
2020-04-27 11:32:04.117974 +0200  <CLIENT-18149>  Client sending (226): ConnectionRequest: log.Log.log_to_file with 1 arguments
2020-04-27 11:32:04.118334 +0200  <CLIENT-18149>  Client sending (226): Sending back exception 'xattr' of type <class 'KeyError'>:
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 400, in answer_request
    result = eval(request.function_string)(*argument_list)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 568, in readfromid
    return cls.vfiles[id].read()
  File "/usr/lib/python3.7/site-packages/rdiff_backup/iterfile.py", line 322, in read
    if not self.addtobuffer():
  File "/usr/lib/python3.7/site-packages/rdiff_backup/iterfile.py", line 349, in addtobuffer
    currentobj = next(self.iter)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/backup.py", line 114, in get_diffs
    for dest_sig in dest_sigiter:
  File "/usr/lib/python3.7/site-packages/rdiff_backup/iterfile.py", line 412, in __next__
    type, data = self._get()
  File "/usr/lib/python3.7/site-packages/rdiff_backup/iterfile.py", line 450, in _get
    self.buf += self.file.read()
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 606, in read
    return self.connection.VirtualFile.readfromid(self.id, length)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 526, in __call__
    return self.connection.reval(*(self.name, ) + args)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 439, in reval
    raise result

2020-04-27 11:32:04.138627 +0200  <CLIENT-18149>  Client received (226): None
2020-04-27 11:32:04.138771 +0200  <CLIENT-18149>  Sending back exception 'xattr' of type <class 'KeyError'>:
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 400, in answer_request
    result = eval(request.function_string)(*argument_list)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 568, in readfromid
    return cls.vfiles[id].read()
  File "/usr/lib/python3.7/site-packages/rdiff_backup/iterfile.py", line 322, in read
    if not self.addtobuffer():
  File "/usr/lib/python3.7/site-packages/rdiff_backup/iterfile.py", line 349, in addtobuffer
    currentobj = next(self.iter)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/backup.py", line 114, in get_diffs
    for dest_sig in dest_sigiter:
  File "/usr/lib/python3.7/site-packages/rdiff_backup/iterfile.py", line 412, in __next__
    type, data = self._get()
  File "/usr/lib/python3.7/site-packages/rdiff_backup/iterfile.py", line 450, in _get
    self.buf += self.file.read()
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 606, in read
    return self.connection.VirtualFile.readfromid(self.id, length)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 526, in __call__
    return self.connection.reval(*(self.name, ) + args)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 439, in reval
    raise result

2020-04-27 11:32:04.138846 +0200  <CLIENT-18149>  Client sending (0): 'xattr'
2020-04-27 11:32:04.141863 +0200  <CLIENT-18149>  Client received (64): 'xattr'
2020-04-27 11:32:04.143457 +0200  <CLIENT-18149>  Exception ''xattr'' raised of class '<class 'KeyError'>':
  File "/usr/lib/python3.7/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3.7/site-packages/rdiff_backup/Main.py", line 437, in Backup
    backup.Mirror(rpin, rpout)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/backup.py", line 39, in Mirror
    DestS.patch(dest_rpath, source_diffiter)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 526, in __call__
    return self.connection.reval(*(self.name, ) + args)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 439, in reval
    raise result

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python3.7/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3.7/site-packages/rdiff_backup/Main.py", line 437, in Backup
    backup.Mirror(rpin, rpout)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/backup.py", line 39, in Mirror
    DestS.patch(dest_rpath, source_diffiter)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 526, in __call__
    return self.connection.reval(*(self.name, ) + args)
  File "/usr/lib/python3.7/site-packages/rdiff_backup/connection.py", line 439, in reval
    raise result
KeyError: 'xattr'
```

If more information is needed, please let me know.

## Questions
Is this the expected behaviour ? If so, I suggest that we'd make it clearer in the documentation ?
If not, does anybody know how to fix it ?

**Comment by ericzolf** [comment]
I doubt I'll find time to look into it this week, but the pattern is strange and nothing I'd expect if the target directories are different. Could it be perhaps that the Synology SSH daemon is too much stripped down and creates chaos? Are you sure it's due to 2 parallel backups and no coincidence?

**Comment by ericzolf** [comment]
Could it be more simply that the xattr python library is installed on one side and not on the other? A package called `python3-pyxattr` or similar. The same applies to `pylibacl`, and as they are optional, they need to be installed manually.

**Comment by glsubri** [comment]
@ericzolf Testing a bit more, it appears that you are right. Since I didn't manage to install `pyxattr` on my NAS (it needed gcc installed or to do some cross-compiling...), I uninstalled it from my own computer and now, it seems I can backup correcty.

Thanks !
