### ISSUE TITLE
Accentuated letters in glob patterns trigger index out of bound error

### ISSUE THREAD

**Issue by sleveque** [rdiff-backup/rdiff-backup#340]
Hello

Since upgrading Debian packages from 1.3.3 to 2.0.0, I have an issue related to accentuated letters in my excluded directory names.

Here is an example:
```
$ apt policy rdiff-backup
rdiff-backup:
  Installed: 2.0.0-1+b1
  Candidate: 2.0.0-1+b1
  Version table:
 *** 2.0.0-1+b1 990
        990 http://ftp.fr.debian.org/debian testing/main armel Packages
         50 http://ftp.fr.debian.org/debian sid/main armel Packages
        100 /var/lib/dpkg/status
$ mkdir -p test/e test/é
$ rdiff-backup test backup
$ rdiff-backup --exclude 'test/é' test backup2
$ rdiff-backup --exclude '*/é' test backup3
Exception 'string index out of range' raised of class '<class 'IndexError'>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 429, in Backup
    backup_set_select(rpin)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 456, in backup_set_select
    rpin.conn.backup.SourceStruct.set_source_select(rpin, select_opts,
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 76, in set_source_select
    sel.ParseArgs(tuplelist, filelists)
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 255, in ParseArgs
    self.add_selection_func(self.glob_get_sf(arg, 0))
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 612, in glob_get_sf
    sel_func = self.glob_get_normal_sf(glob_str, include)
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 679, in glob_get_normal_sf
    glob_comp_re = re_comp(b"^%b($|/)" % self.glob_to_re(glob_str))
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 749, in glob_to_re
    c, s = str_pat[i], str_pat[i:i + 2]

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 429, in Backup
    backup_set_select(rpin)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 456, in backup_set_select
    rpin.conn.backup.SourceStruct.set_source_select(rpin, select_opts,
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 76, in set_source_select
    sel.ParseArgs(tuplelist, filelists)
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 255, in ParseArgs
    self.add_selection_func(self.glob_get_sf(arg, 0))
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 612, in glob_get_sf
    sel_func = self.glob_get_normal_sf(glob_str, include)
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 679, in glob_get_normal_sf
    glob_comp_re = re_comp(b"^%b($|/)" % self.glob_to_re(glob_str))
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 749, in glob_to_re
    c, s = str_pat[i], str_pat[i:i + 2]
IndexError: string index out of range

```

This had been working for years. My workaround for now is to replace accentuated letters with * after checking that the pattern would still specifically match what I wanted to exclude.

**Comment by ericzolf** [comment]
Thanks for reporting this and happy to hear that you could find a workaround.
I've been able to reproduce your issue and the use case will be part of our test pipeline in the future.

If you're curious, you might follow branch ericzolf-fix-accents-glob-to-re-340 (there is only the currently failing test, welcome to test driven development).
