### ISSUE TITLE
[BUG] KeyError: 'version' when backing up via ssh

### ISSUE THREAD

**Issue by felixwortmann** [rdiff-backup/rdiff-backup#348]
## Bug summary

I am trying to backup to a remote server via ssh. It throws an error and does not work.

## Version, Python, Operating System
Ubuntu Server 18.04(updated all) (local)
Ubuntu Server 20.04 / raspi (remote)

Call `rdiff-backup -v9` and paste the output between the backquotes below, repeat for each environment impacted:

```
Sun May  3 19:29:27 2020  Using rdiff-backup version 1.2.8
Sun May  3 19:29:27 2020  Executing ssh -C ubuntu@ubuntu rdiff-backup --server
Sun May  3 19:29:27 2020  Client sending (0): ConnectionRequest: Globals.get with 1 arguments
Sun May  3 19:29:27 2020  Client sending (0): 'version'
Sun May  3 19:29:35 2020  Client received (0): 'version'
Sun May  3 19:29:35 2020  Exception ''version'' raised of class '<type 'exceptions.KeyError'>':
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 321, in Main
    rps = map(SetConnections.cmdpair2rp, cmdpairs)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py", line 76, in cmdpair2rp
    if cmd: conn = init_connection(cmd)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py", line 152, in init_connection
    check_connection_version(conn, remote_cmd)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py", line 160, in check_connection_version
    try: remote_version = conn.Globals.get('version')
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 450, in __call__
    return apply(self.connection.reval, (self.name,) + args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 370, in reval
    if isinstance(result, Exception): raise result

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 30, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 321, in Main
    rps = map(SetConnections.cmdpair2rp, cmdpairs)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py", line 76, in cmdpair2rp
    if cmd: conn = init_connection(cmd)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py", line 152, in init_connection
    check_connection_version(conn, remote_cmd)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/SetConnections.py", line 160, in check_connection_version
    try: remote_version = conn.Globals.get('version')
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 450, in __call__
    return apply(self.connection.reval, (self.name,) + args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 370, in reval
    if isinstance(result, Exception): raise result
KeyError: 'version'
Fatal Error: Lost connection to the remote system
```

## rdiff-backup call
```
rdiff-backup -v9 /home/user ubuntu@ubuntu::/backupdrive/user-ubuntu-server/
```
If I just ssh ```ubuntu@ubuntu```, it works

## What happened and what did you expect?
It should not throw an error and just backup my stuff to the remote server. 

## More information
Because of the ```KeyError: 'version``` I think this might be a problem of Ubuntu 20.04/Ubuntu18.04

**Comment by ericzolf** [comment]
Yep, you probably have rdiff-backup 1.2.8 on one side and 2.0.0 and they don't work together. You need to upgrade both sides to the same version.

**Comment by ericzolf** [comment]
OK, to be clearer perhaps: you didn't send the output of `rdiff-backup -v9` on _both_ sides but I guess that you have rdiff-backup 2.0.0 on the Raspi side. Hence you need to upgrade rdiff-backup on the 18.04 side. Check https://github.com/rdiff-backup/rdiff-backup#ubuntu-backports-for-older-versions-needs-a-backported-20 on how to do this.

Please close the issue if it solves your issue, else let us know and we'll see what we can do.

**Comment by felixwortmann** [comment]
> OK, to be clearer perhaps: you didn't send the output of `rdiff-backup -v9` on _both_ sides but I guess that you have rdiff-backup 2.0.0 on the Raspi side. Hence you need to upgrade rdiff-backup on the 18.04 side. Check https://github.com/rdiff-backup/rdiff-backup#ubuntu-backports-for-older-versions-needs-a-backported-20 on how to do this.
> 
> Please close the issue if this solves your problem, else let us know and we'll see what we can do.

This fixes it. Thanks.

Could this be documented better? Maybe you could catch the error and print something like: ```"This could occur because you are using different versions of rdiff-backup"```
