### ISSUE TITLE
[BUG] charset conversion error on logging when non-UTF-8 locale is active

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#356]
## Bug summary

rdiff-backup version 2.0.0 or 2.0.1rc0 on centos7 with python3.6 is failing to restore files with special characters.

## Version, Python, Operating System

Call `rdiff-backup -v9` and paste the output between the backquotes below, repeat for each environment impacted:

```
2020-05-11 21:04:14.547611 +0000  <CLIENT-286>  Using rdiff-backup version 2.0.1rc0
2020-05-11 21:04:14.547685 +0000  <CLIENT-286>  	with cpython /usr/bin/python3 version 3.6.8
2020-05-11 21:04:14.550694 +0000  <CLIENT-286>  	on Linux-4.19.37-x86_64-with-centos-7.8.2003-Core, fs encoding ascii
2020-05-11 21:04:14.552330 +0000  <CLIENT-286>  Using mirror root directory /testcases
2020-05-11 21:04:14.552817 +0000  <CLIENT-286>  Unable to import win32security module. Windows ACLs
not supported by filesystem at /testcases/rdiff-backup-data
2020-05-11 21:04:14.553562 +0000  <CLIENT-286>  -----------------------------------------------------------------
Detected abilities for rdiff-backup repository (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
2020-05-11 21:04:14.553638 +0000  <CLIENT-286>  Making directory /tmp/coucou/rdiff-backup.tmp.0
2020-05-11 21:04:14.553802 +0000  <CLIENT-286>  Touching /tmp/coucou/rdiff-backup.tmp.0/5-_ a.snapshot.gz
2020-05-11 21:04:14.553948 +0000  <CLIENT-286>  Deleting /tmp/coucou/rdiff-backup.tmp.0/5-_ a.snapshot.gz
2020-05-11 21:04:14.554872 +0000  <CLIENT-286>  Exception ''ascii' codec can't encode characters in position 91-93: ordinal not in range(128)' raised of class '<class 'UnicodeEncodeError'>':
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 393, in error_check_Main
    Main(arglist)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 415, in Main
    take_action(rps)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 371, in take_action
    Restore(rps[0], rps[1], 1)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 697, in Restore
    dest_rp.conn.fs_abilities.restore_set_globals(dest_rp)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/fs_abilities.py", line 1072, in restore_set_globals
    dest_fsa = FSAbilities('restore target').init_readwrite(rpout)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/fs_abilities.py", line 157, in init_readwrite
    self.set_extended_filenames(subdir)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/fs_abilities.py", line 241, in set_extended_filenames
    ext_rp.touch()
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/rpath.py", line 1248, in touch
    log.Log("Touching %s" % self.get_safepath(), 7)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/log.py", line 150, in __call__
    self.log_to_term(message, verbosity)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/log.py", line 173, in log_to_term
    termfp.write(tmpstr)

Traceback (most recent call last):
  File "/usr/local/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 393, in error_check_Main
    Main(arglist)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 415, in Main
    take_action(rps)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 371, in take_action
    Restore(rps[0], rps[1], 1)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 697, in Restore
    dest_rp.conn.fs_abilities.restore_set_globals(dest_rp)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/fs_abilities.py", line 1072, in restore_set_globals
    dest_fsa = FSAbilities('restore target').init_readwrite(rpout)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/fs_abilities.py", line 157, in init_readwrite
    self.set_extended_filenames(subdir)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/fs_abilities.py", line 241, in set_extended_filenames
    ext_rp.touch()
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/rpath.py", line 1248, in touch
    log.Log("Touching %s" % self.get_safepath(), 7)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/log.py", line 150, in __call__
    self.log_to_term(message, verbosity)
  File "/usr/local/lib64/python3.6/site-packages/rdiff_backup/log.py", line 173, in log_to_term
    termfp.write(tmpstr)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 91-93: ordinal not in range(128)
```

## rdiff-backup call

```
docker run -it centos:7
yum install -y epel-release
yum install -y python-devel openldap-devel rdiff-backup gcc git
curl https://gitlab.com/ikus-soft/rdiffweb/-/raw/master/rdiffweb/tests/testcases.tar.gz?inline=false -o testcases.tar.gz
tar -zxvf testcases.tar.gz
/usr/bin/rdiff-backup -v 9 --restore-as-of=1414871387 /testcases /tmp/coucou
```

**Comment by ikus060** [comment]
Found this using rdiffweb pipeline: https://gitlab.com/ikus-soft/rdiffweb/-/jobs/547518130

**Comment by ericzolf** [comment]
It looks like your terminal encoding is ASCII. What are your ANG

**Comment by ikus060** [comment]
This is the first thing I check. I don't have any. But it should not matter since on debian stretch doing the same test it's working perfectly fine and I don't have "LANG" or "LC_" either.

I just notice the log is missing something when I run it with `-v 9`. 

```
/usr/bin/rdiff-backup -v 5 --force --restore-as-of=1414871387 /testcases /tmp/coucou
Using rdiff-backup version 2.0.0
	with cpython /usr/bin/python3 version 3.6.8
	on Linux-4.19.37-x86_64-with-centos-7.8.2003-Core, fs encoding ascii
Unable to import win32security module. Windows ACLs
not supported by filesystem at /testcases/rdiff-backup-data
-----------------------------------------------------------------
Detected abilities for rdiff-backup repository (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Unable to import win32security module. Windows ACLs
not supported by filesystem at /tmp/coucou/rdiff-backup.tmp.1
-----------------------------------------------------------------
Detected abilities for restore target (read/write) file system:
  Ownership changing                           On
  Hard linking                                 On
  fsync() directories                          On
  Directory inc permissions                    On
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   Off
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Warning: special_escapes file not found,
will assume need to escape DOS devices and trailing spaces based on file systems.
Backup: escape_dos_devices = 0
Backup: escape_trailing_spaces = 0
Starting restore of /testcases to /tmp/coucou as it was as of Sat Nov  1 19:49:47 2014.
Processing changed file .
Exception ''ascii' codec can't encode character '\ufffd' in position 84: ordinal not in range(128)' raised of class '<class 'UnicodeEncodeError'>':
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 368, in take_action
    Restore(rps[0], rps[1], 1)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 716, in Restore
    restore_root.new_index(restore_index), inc_rpath, dest_rp, time)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 42, in Restore
    TargetS.patch(target, diff_iter)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 334, in patch
    for diff in rorpiter.FillInIter(diff_iter, target):
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rorpiter.py", line 202, in FillInIter
    for rp in rpiter:
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 282, in get_diffs_from_collated
    diff = cls.get_diff(mir_rorp, target_rorp)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 299, in get_diff
    file_fp = cls.rf_cache.get_fp(expanded_index, mir_rorp)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 394, in get_fp
    self.get_rf(index, mir_rorp), mir_rorp, self.root_rf.mirror_rp)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 374, in get_rf
    if not self.add_rfs(index, mir_rorp):
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 420, in add_rfs
    new_rfs = list(temp_rf.yield_sub_rfs())
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 589, in yield_sub_rfs
    for mirror_rp, inc_pair in collated:
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rorpiter.py", line 105, in Collate2Iters
    relem2 = next(riter2)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 645, in yield_inc_complexes
    items = get_inc_pairs()
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 633, in get_inc_pairs
    add_to_dict(filename)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 624, in add_to_dict
    rp = inc_rpath.append(filename)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rpath.py", line 1410, in append
    return self.__class__(self.conn, self.base, self.index + ext)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/FilenameMapping.py", line 165, in __init__
    self.setdata()
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rpath.py", line 1110, in setdata
    self.conn.rpath.setdata_local(self)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rpath.py", line 1821, in setdata_local
    rpath.data['acl'] = acl_get(rpath)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/eas_acls.py", line 690, in rpath_acl_get
    acl.read_from_rp(rp)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/eas_acls.py", line 435, in read_from_rp
    rp.conn.eas_acls.get_acl_lists_from_rp(rp)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/eas_acls.py", line 491, in get_acl_lists_from_rp
    (rp.get_safepath(), exc), 3)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/log.py", line 140, in __call__
    self.log_to_file(message)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/log.py", line 151, in log_to_file
    self.logfp.write(tmpstr)

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/eas_acls.py", line 487, in get_acl_lists_from_rp
    def_acl = posix1e.ACL(filedef=os.fsdecode(rp.path))
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 43-45: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 368, in take_action
    Restore(rps[0], rps[1], 1)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 716, in Restore
    restore_root.new_index(restore_index), inc_rpath, dest_rp, time)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 42, in Restore
    TargetS.patch(target, diff_iter)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 334, in patch
    for diff in rorpiter.FillInIter(diff_iter, target):
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rorpiter.py", line 202, in FillInIter
    for rp in rpiter:
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 282, in get_diffs_from_collated
    diff = cls.get_diff(mir_rorp, target_rorp)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 299, in get_diff
    file_fp = cls.rf_cache.get_fp(expanded_index, mir_rorp)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 394, in get_fp
    self.get_rf(index, mir_rorp), mir_rorp, self.root_rf.mirror_rp)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 374, in get_rf
    if not self.add_rfs(index, mir_rorp):
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 420, in add_rfs
    new_rfs = list(temp_rf.yield_sub_rfs())
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 589, in yield_sub_rfs
    for mirror_rp, inc_pair in collated:
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rorpiter.py", line 105, in Collate2Iters
    relem2 = next(riter2)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 645, in yield_inc_complexes
    items = get_inc_pairs()
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 633, in get_inc_pairs
    add_to_dict(filename)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/restore.py", line 624, in add_to_dict
    rp = inc_rpath.append(filename)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rpath.py", line 1410, in append
    return self.__class__(self.conn, self.base, self.index + ext)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/FilenameMapping.py", line 165, in __init__
    self.setdata()
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rpath.py", line 1110, in setdata
    self.conn.rpath.setdata_local(self)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rpath.py", line 1821, in setdata_local
    rpath.data['acl'] = acl_get(rpath)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/eas_acls.py", line 690, in rpath_acl_get
    acl.read_from_rp(rp)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/eas_acls.py", line 435, in read_from_rp
    rp.conn.eas_acls.get_acl_lists_from_rp(rp)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/eas_acls.py", line 491, in get_acl_lists_from_rp
    (rp.get_safepath(), exc), 3)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/log.py", line 140, in __call__
    self.log_to_file(message)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/log.py", line 151, in log_to_file
    self.logfp.write(tmpstr)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 84: ordinal not in range(128)
```
I could take a deeper look into this problem tomorrow. I think the log file is open as unicode.

**Comment by ericzolf** [comment]
Ok, let me try to reproduce, let's see if it's a local issue or something in CentOS 7.

**Comment by ericzolf** [comment]
I can reproduce it but it has something to do with the locale: `LANG=en_US.UTF-8 /usr/bin/rdiff-backup -v 9 --restore-as-of=1414871387 /root/testcases /tmp/coucou2` doesn't fail whereas your command fails.

This said under Fedora, I'm not able to reproduce the error by changing LC_ALL and LANG, so there seems to be another parameter to tweak...

**Comment by ericzolf** [comment]
It seems to all depend from what Python returns:

```
>>> import locale
>>> locale.getpreferredencoding()
'ANSI_X3.4-1968'
```

(ANSI something is just another name for ASCII)

**Comment by ericzolf** [comment]
After some thoughts, I would like to keep this bug open for now:

- the "simple" solution in code would be like for Windows, where we patch the library on the fly, this is ugly.
- in difference to Windows, there is a workaround, i.e. define properly LANG, and not a generic issue (the default codeset is normally UTF-8, only in very limited environments is it ASCII).
- I would fix it properly once we have a cleaner code base

What do you think?

**Comment by ikus060** [comment]
I wish I could call you to understand where is the issue in the code. I don't understand why the "preferedencoding" would have an impact on rdiff-backup.
1. We read and write files as bytes.
2. We write logs from unicode to as utf-8

I don't get where we are messing with the wrong encoding here.

**Comment by ikus060** [comment]
Also, side note, this is working fine with rdiff-backup v1.2.8

**Comment by ericzolf** [comment]
Your point 2 is incorrect, we write strings in Unicode format to logfiles but the file itself has it's own encoding, and we are using the default encoding. Check https://docs.python.org/3/library/functions.html#open, encoding and/or errors are the parameters we should set explicitly but it should happen in rpath.py, where the code is less than obvious and common to logs and saved files, so dangerous to touch.

So the error is a conversion error between Unicode and ASCII, not between strings and bytes.

And 1.2.8 is all strings, and didn't care about conversions of encodings, as Python 2 didn't care much either.

**Comment by ikus060** [comment]
I'm not done with my testing... But I want to keep this as a reference for now.

Changing log file to use binary. That should also help for Windows. ;)
`rpath.open("ab")`

Then change the encoding to write bytes to the log file. I would recommend to use backslash replace or something to avoid losing the real value... We should also use the defult encoding and not encode utf8
```
    def log_to_file(self, message):
        """Write the message to the log file, if possible"""
        if self.log_file_open:
            if self.log_file_local:
                tmpstr = self.format(message, self.verbosity)
                # transform string to bytes using the proper encoding
                if type(tmpstr) == str:
                    tmpstr = tmpstr.encode(encoding='utf-8', errors='replace')
                self.logfp.write(tmpstr)
                self.logfp.flush()
            else:
                self.log_file_conn.log.Log.log_to_file(message)

    def log_to_term(self, message, verbosity):
        """Write message to stdout/stderr"""
        if verbosity <= 2 or Globals.server:
            termfp = sys.stderr.buffer
        else:
            termfp = sys.stdout.buffer
        tmpstr = self.format(message, self.term_verbosity)
        if type(tmpstr) == str:
            tmpstr = tmpstr.encode(encoding='utf-8', errors='replace')
        termfp.write(tmpstr)
```

**Comment by ericzolf** [comment]
I'm fine with keeping the bug open, I would just not fix the issue now.

**Comment by ikus060** [comment]
Ye, I will work on a PR later next week.

**Comment by ericzolf** [comment]
I shouldn't try to answer e-mails so late in the evening: I wanted to express that the bug shouldn't be fixed before the upcoming bugfix release because it adds more risks than it solves problems, and if you can agree with this?

The solution to switch the mode from text to bytes and do our own encoding with lenient error handling seems indeed easier than my initial approach to add the lenient error handling directly into the 'open' call. It still adds a certain risk because rpath.open still does some magic with the opening mode. And because the use case is so obscure, I am not sure it's worth doing the fix right now for the bugfix release.

**Comment by ikus060** [comment]
I could some testing in a different branches and tag this as a dev version,but I will continue working on a fix for this. This is causing a mess in my rdiffweb testing.

The impact seams to be minimal and will actually help the case of windows. I would removed this:
```
# FIXME Dirty hack in order to make sure that log files are written in Unicode
# format because else they are written as cp1252 under Windows
# Influences program-wide all writing in text mode, not binary.
if os.name == "nt":
    import _locale
    _locale._gdl_bak = _locale._getdefaultlocale
    _locale._getdefaultlocale = (lambda *args: (_locale._gdl_bak()[0], 'utf8'))
```

I just don't know what is preferable for default encoding for logging. Should we enforce UTF-8? or should be use the "_getdefaultlocale" encoding. My feeling tell me to use UTF-8 on all platform for logging.
On the terminal, I would need to keep the default encoding most likely.

**Comment by ericzolf** [comment]
I'll think about it, but in the meantime, you just need to define `export LANG=en_US.utf8` in your container(s) and the issue is solved.
