### ISSUE TITLE
[BUG] Test failures in eas_aclstest on recent ArchLinux

### ISSUE THREAD

**Issue by felixonmars** [rdiff-backup/rdiff-backup#370]
## Bug summary

These test failures are newly introduces with librsync 2.3.x:

```
..
======================================================================
FAIL: test_acl_mapping (__main__.ACLTest)
Test mapping ACL names
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/eas_aclstest.py", line 597, in test_acl_mapping
    assert get_perms_of_user(out_acl, 'root') == 4
AssertionError

======================================================================
FAIL: testBasic (__main__.EATest)
Test basic writing and reading of extended attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/eas_aclstest.py", line 78, in testBasic
    assert new_ea.attr_dict == self.sample_ea.attr_dict, \
AssertionError: ({}, {b'user.empty': b'', b'user.not_empty': b'foobar', b'user.third': b'hello', b'user.binary': b'\x00\x01\x02\x8c/="', b'user.multiline': b'This is a fairly long extended attribute.\n                Encoding it will require several lines of\n                base64.\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1'})

======================================================================
FAIL: testIterate (__main__.EATest)
Test writing several records and then reading them back
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/eas_aclstest.py", line 201, in testIterate
    assert sample_ea_reread == self.sample_ea, "Re-read EAs %s are different from %s" % \
AssertionError: Re-read EAs {} are different from {b'user.empty': b'', b'user.not_empty': b'foobar', b'user.third': b'hello', b'user.binary': b'\x00\x01\x02\x8c/="', b'user.multiline': b'This is a fairly long extended attribute.\n                Encoding it will require several lines of\n                base64.\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1'}

----------------------------------------------------------------------
Ran 20 tests in 15.870s

FAILED (failures=3)
Comparing /build/rdiff-backup/src/rdiff-backup/build/testfiles/ea_test2 and /build/rdiff-backup/src/rdiff-backup/build/testfiles/output, hardlinks 1, eas 1, acls 0
Comparing /build/rdiff-backup/src/rdiff-backup/build/testfiles/ea_empty and /build/rdiff-backup/src/rdiff-backup/build/testfiles/output, hardlinks 1, eas 1, acls 0
Comparing /build/rdiff-backup/src/rdiff-backup/build/testfiles/ea_test1 and /build/rdiff-backup/src/rdiff-backup/build/testfiles/output, hardlinks 1, eas 1, acls 0
Comparing /build/rdiff-backup/src/rdiff-backup/build/testfiles/ea_test1 and /build/rdiff-backup/src/rdiff-backup/build/testfiles/restore, hardlinks 1, eas 1, acls 0
Comparing /build/rdiff-backup/src/rdiff-backup/build/testfiles/ea_test2 and /build/rdiff-backup/src/rdiff-backup/build/testfiles/restore, hardlinks 1, eas 1, acls 0
Comparing /build/rdiff-backup/src/rdiff-backup/build/testfiles/ea_empty and /build/rdiff-backup/src/rdiff-backup/build/testfiles/restore, hardlinks 1, eas 1, acls 0
Executing:  b'/build/rdiff-backup/src/rdiff-backup/build/scripts-3.8/rdiff-backup  --current-time 10000 /build/rdiff-backup/src/rdiff-backup/build/testfiles/ea_test1 /build/rdiff-backup/src/rdiff-backup/build/testfiles/output'
Comparing /build/rdiff-backup/src/rdiff-backup/build/testfiles/ea_test1 and /build/rdiff-backup/src/rdiff-backup/build/testfiles/output, hardlinks 1, eas 1, acls 0
Executing:  b'/build/rdiff-backup/src/rdiff-backup/build/scripts-3.8/rdiff-backup  --current-time 20000 /build/rdiff-backup/src/rdiff-backup/build/testfiles/ea_test2 /build/rdiff-backup/src/rdiff-backup/build/testfiles/output'
Comparing /build/rdiff-backup/src/rdiff-backup/build/testfiles/ea_test2 and /build/rdiff-backup/src/rdiff-backup/build/testfiles/output, hardlinks 1, eas 1, acls 0
Executing:  b'/build/rdiff-backup/src/rdiff-backup/build/scripts-3.8/rdiff-backup -r 10000 /build/rdiff-backup/src/rdiff-backup/build/testfiles/output /build/rdiff-backup/src/rdiff-backup/build/testfiles/restore'
Comparing /build/rdiff-backup/src/rdiff-backup/build/testfiles/ea_test1 and /build/rdiff-backup/src/rdiff-backup/build/testfiles/restore, hardlinks 1, eas 1, acls 0
```

## Version, Python, Operating System
rdiff-backup 2.0.0 or 2.0.3
librsync 2.3.1
Python 3.8.3

Call `rdiff-backup -v9` and paste the output between the backquotes below, repeat for each environment impacted:

```
2020-05-22 01:53:45.314363 +0800  <CLIENT-1927212>  Using rdiff-backup version 2.0.0
2020-05-22 01:53:45.314435 +0800  <CLIENT-1927212>      with cpython /usr/bin/python version 3.8.3
2020-05-22 01:53:45.316980 +0800  <CLIENT-1927212>      on Linux-5.6.13-arch1-1-x86_64-with-glibc2.2.5, fs encoding utf-8
2020-05-22 01:53:45.317173 +0800  <CLIENT-1927212>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.
```

**Comment by felixonmars** [comment]
One more failure:

fs_abilitiestest:
```
.Fs
======================================================================
FAIL: testReadWrite (__main__.FSAbilitiesTest)
Test basic querying read/write
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/fs_abilitiestest.py", line 75, in testReadWrite
    assert fsa.eas == self.eas, fsa.eas
AssertionError: 0

----------------------------------------------------------------------
Ran 3 tests in 0.004s

FAILED (failures=1, skipped=1)
-----------------------------------------------------------------
Detected abilities for read-only (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Time elapsed =  0.0018966197967529297
-----------------------------------------------------------------
Detected abilities for read/write (read/write) file system:
  Ownership changing                           Off
  Hard linking                                 On
  fsync() directories                          On
  Directory inc permissions                    On
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   Off
  Access control lists                         On
  Extended attributes                          Off
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
```

**Comment by ericzolf** [comment]
I haven't yet tried but I also don't see the link to librsync. Are you running the tests on a specific file system? Any unusual Mount parameter? All the errors hint at writing EAs and reading then back.
You are on ArchLinux, right?

**Comment by felixonmars** [comment]
I am on Arch, it's in the same clean build chroot for Arch which has latest versions of repo packages at the time, so it should be on the same file system.

Attaching a full diff of build env package version differences, hope this helps: https://paste.xinu.at/zfbQ/

**Comment by ericzolf** [comment]
OK, I've got myself a container with ArchLinux and I can reproduce the issue, but it is independent AFAICJ from the version of librsync: I've downgraded down to 2.0.2 (my version on Fedora 32) and I still get the same errors, so it must be something different, perhaps a difference in the xattr/libacl libraries, but I don't see any relevant difference:

```
$ rpm -qa python3-pylibacl python3-pyxattr
python3-pylibacl-0.5.4-2.fc32.x86_64
python3-pyxattr-0.7.1-3.fc32.x86_64
```

vs.

```
# pacman -Q python-pylibacl python-pyxattr
python-pylibacl 0.5.4-2
python-pyxattr 0.7.1-1
```
It looks like, I need to debug this more closely. Don't hold you breath...

**Comment by ericzolf** [comment]
I have the suspicion that something is broken with the ACL library under ArchLinux:

```
$ getfacl .
# file: .
# owner: admin
# group: admin
user::rwx
group::r-x
other::r-x
$ python
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import posix1e
>>> p = posix1e.ACL(file='.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 95] Operation not supported
```

Same thing under Fedora 32:

```
$ getfacl .
# file: .
# owner: ericl
# group: ericl
user::rwx
group::rwx
other::r-x
$ python
Python 3.8.2 (default, Feb 28 2020, 00:00:00) 
[GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import posix1e
>>> p = posix1e.ACL(file='.')
>>> p.valid()
True
>>> p.to_any_text()
b'user::rwx\ngroup::rwx\nother::r-x'
```

Please validate this with your distro and come back to this issue if you need help or the underlying issue with Python/ACL is solved/explained.

**Comment by felixonmars** [comment]
I cannot reproduce it here. Does it require any specific path?

This is what I got for /:

```
$ getfacl .
# file: .
# owner: root
# group: root
user::rwx
group::r-x
other::r-x

$ python -c "import posix1e; p = posix1e.ACL(file='.'); print(p.to_any_text())"
b'user::rwx\ngroup::r-x\nother::r-x'
```

**Comment by ericzolf** [comment]
I did it in the home directory of a normal user, as normal user.

**Comment by felixonmars** [comment]
Still cannot reproduce. Could it be related to your container technique?

**Comment by ericzolf** [comment]
Possibly. Let me check in a VM. What is strange is that I get exactly the same errors in the tests as you do...

**Comment by ericzolf** [comment]
Test in VM was successful and confusing... In the sense that I don't have the error neither directly in python, nor the one you initially reported. Could it be that your packaging environment uses some kind of containerized environment?

**Comment by ericzolf** [comment]
Results of eas_aclstests in the container:

```
======================================================================
ERROR: test_acl_mapping (__main__.ACLTest)
Test mapping ACL names
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/eas_aclstest.py", line 597, in test_acl_mapping
    assert get_perms_of_user(out_acl, 'root') == 4
  File "testing/eas_aclstest.py", line 577, in get_perms_of_user
    for typechar, owner_pair, perms in acl.entry_list:
TypeError: 'NoneType' object is not iterable

======================================================================
FAIL: testBasic (__main__.ACLTest)
Test basic writing and reading of ACLs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/eas_aclstest.py", line 342, in testBasic
    assert str(new_acl) == str(self.sample_acl), \
AssertionError: ('', 'user::rwx\nuser:root:rwx\ngroup::r-x\ngroup:root:r-x\nmask::r-x\nother::---')

======================================================================
FAIL: testBasicDir (__main__.ACLTest)
Test reading and writing of ACL w/ defaults to directory
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/eas_aclstest.py", line 356, in testBasicDir
    assert not new_acl.is_basic()
AssertionError

======================================================================
FAIL: testIterate (__main__.ACLTest)
Test writing several records and then reading them back
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/eas_aclstest.py", line 479, in testIterate
    assert dir_acl_reread == self.dir_acl
AssertionError

----------------------------------------------------------------------
Ran 20 tests in 12.947s
```
and results of fs_abilitiestest:
```
$ PATH=$PWD/build/scripts-3.8:$PATH PYTHONPATH=$PWD/build/lib.linux-x86_64-3.8 python testing/fs_abilitiestest.py 
-----------------------------------------------------------------
Detected abilities for read-only (read only) file system:
  Access control lists                         Off
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
FTime elapsed =  0.022533416748046875
-----------------------------------------------------------------
Detected abilities for read/write (read/write) file system:
  Ownership changing                           Off
  Hard linking                                 On
  fsync() directories                          On
  Directory inc permissions                    On
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   Off
  Access control lists                         Off
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Fs
======================================================================
FAIL: testReadOnly (__main__.FSAbilitiesTest)
Test basic querying read only
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/fs_abilitiestest.py", line 57, in testReadOnly
    assert fsa.acls == self.acls, fsa.acls
AssertionError: 0

======================================================================
FAIL: testReadWrite (__main__.FSAbilitiesTest)
Test basic querying read/write
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/fs_abilitiestest.py", line 76, in testReadWrite
    assert fsa.acls == self.acls, fsa.acls
AssertionError: 0

----------------------------------------------------------------------
Ran 3 tests in 0.028s

FAILED (failures=2, skipped=1)
```

**Comment by felixonmars** [comment]
I guess I figured it out. The failed chroot is on a tmpfs instead and I overlooked it. Sorry!
