### ISSUE TITLE
[BUG] Exception when trying to log an error

### ISSUE THREAD

**Issue by intra2net** [rdiff-backup/rdiff-backup#380]
## Bug summary

When rdiff-backup tries to log an error to the logfile, the exception "'a bytes-like object is required, not 'str''" is thrown and the program aborts.

## Version, Python, Operating System

rdiff-backup 2.0.0, running on python 3.6.8 on CentOS 7.8
(Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core, fs encoding utf-8)

## rdiff-backup call
```
rdiff-backup --force --no-compression --print-statistics --exclude-fifos --exclude-sockets /data /mnt/backup
```

## What happened and what did you expect?

A file on the partition to be backed up changed while rdiff-backup was running. This is expected in this setup. It should log an error about this and continue.

But instead:
```
UpdateError: 'data/some/sub/dir/changed-file/rdiff-backup.tmp.266' does not match source
Exception 'a bytes-like object is required, not 'str'' raised of class '<class 'TypeError'>':
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 434, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 55, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 281, in patch_and_increment
    ITR(diff.index, diff)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rorpiter.py", line 313, in __call__
    last_branch.fast_process(*args)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 781, in fast_process
    if self.patch_to_temp(mirror_rp, diff_rorp, tf):
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 637, in patch_to_temp
    return self.matches_cached_rorp(diff_rorp, new)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 691, in matches_cached_rorp
    "temp file '%s' does not match source" % new_rp.get_safepath())
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/log.py", line 313, in write_if_open
    cls.write(error_type, rp, exc)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/log.py", line 293, in write
    cls._log_fileobj.write(logstr)

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 434, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 55, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 281, in patch_and_increment
    ITR(diff.index, diff)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rorpiter.py", line 313, in __call__
    last_branch.fast_process(*args)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 781, in fast_process
    if self.patch_to_temp(mirror_rp, diff_rorp, tf):
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 637, in patch_to_temp
    return self.matches_cached_rorp(diff_rorp, new)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 691, in matches_cached_rorp
    "temp file '%s' does not match source" % new_rp.get_safepath())
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/log.py", line 313, in write_if_open
    cls.write(error_type, rp, exc)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/log.py", line 293, in write
    cls._log_fileobj.write(logstr)
TypeError: a bytes-like object is required, not 'str'
```

## More information

In the Logger-class you recently introduced a call to encode() for str-types. It looks like this should also be added to the write() function of the ErrorLog-class.

**Comment by ikus060** [comment]
> In the Logger-class you recently introduced a call to encode() for str-types. It looks like this should also be added to the write() function of the ErrorLog-class.

Exactly the issue. The error log is open as bytes and we try to write str. Will prepare a PR.
