### ISSUE TITLE
[BUG] Problems with german umlaut in filenames

### ISSUE THREAD

**Issue by ASDBigmac** [rdiff-backup/rdiff-backup#382]
Hi there,

I just migrated from the old 1.x branch which worked flawlessly for years but is not supported on my system anymore.

Command-Line: rdiff-backup --remote-tempdir /mnt/video/tmp/ -v 7 --print-statistics --exclude-filelist /home/asdbigmac/.backuplist /home/asdbigmac taz::/mnt/backup/backup/speedygonzales

Version: 2.0.0 as well as 2.0.3 (both with the same error)

Originally I thought I encounter a bug which is already known, but after some investigation this seems to be something else. Already tried the suggestion with LANG=en_US.utf8 which did not work. The default of my system is:

LC_MEASUREMENT=de_DE.UTF-8
LC_PAPER=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LANG=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_NUMERIC=de_DE.UTF-8
LANGUAGE=
LC_TELEPHONE=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_TIME=de_DE.UTF-8

The server just export the LANG=de_DE.UTF-8 without all the LCs

Client:
2020-05-27 22:38:08.706582 +0200  <CLIENT-13481>  Using rdiff-backup version 2.0.3
2020-05-27 22:38:08.706676 +0200  <CLIENT-13481>        with cpython /usr/bin/python3.6 version 3.6.10
2020-05-27 22:38:08.723473 +0200  <CLIENT-13481>        on Linux-5.4.0-sabayon-x86_64-Intel-R-_Core-TM-_i5_CPU_760_@_2.80GHz-with-gentoo-2.6, fs encoding utf-8
2020-05-27 22:38:08.723579 +0200  <CLIENT-13481>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.

Server:
2020-05-27 22:37:48.732570 +0200  <CLIENT-214925>  Using rdiff-backup version 2.0.3
2020-05-27 22:37:48.732723 +0200  <CLIENT-214925>       with cpython /usr/bin/python3.6 version 3.6.9
2020-05-27 22:37:48.757078 +0200  <CLIENT-214925>       on Linux-5.3.0-sabayon-x86_64-Intel-R-_Core-TM-_i3_CPU_530_@_2.93GHz-with-gentoo-2.6, fs encoding utf-8
2020-05-27 22:37:48.757348 +0200  <CLIENT-214925>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.

I get a crash as soon as a ä/ö/ü in file or directory name is hit. If I remove that file and restart it continues until the next one is reached.

Exception ''ascii' codec can't encode character '\xe4' in position 77: ordinal not in range(128)' raised of class '<class 'UnicodeEncodeError'>':
File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 393, in error_check_Main
Main(arglist)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 415, in Main
take_action(rps)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 351, in take_action
Backup(rps[0], rps[1])
File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 440, in Backup
backup.Mirror(rpin, rpout)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 39, in Mirror
DestS.patch(dest_rpath, source_diffiter)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 526, in call
return self.connection.reval(*(self.name, ) + args)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 439, in reval
raise result

Traceback (most recent call last):
File "/usr/lib/python-exec/python3.6/rdiff-backup", line 32, in
rdiff_backup.Main.error_check_Main(sys.argv[1:])
File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 393, in error_check_Main
Main(arglist)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 415, in Main
take_action(rps)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 351, in take_action
Backup(rps[0], rps[1])
File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 440, in Backup
backup.Mirror(rpin, rpout)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 39, in Mirror
DestS.patch(dest_rpath, source_diffiter)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 526, in call
return self.connection.reval(*(self.name, ) + args)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 439, in reval
raise result
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 77: ordinal not in range(128)
Setting time of /mnt/backup/backup/speedygonzales/.kde4/share/apps/kmix/profiles/rdiff-backup.tmp.18762 to 1337256527
Renaming /mnt/backup/backup/speedygonzales/.kde4/share/apps/kmix/profiles/rdiff-backup.tmp.18762 to /mnt/backup/backup/speedygonzales/.kde4/share/apps/kmix/profiles/ALSA.USB_Speaker.1.default.xml
Sending back exception 'ascii' codec can't encode character '\xe4' in position 77: ordinal not in range(128) of type <class 'UnicodeEncodeError'>:
File "/usr/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 400, in answer_request
result = eval(request.function_string)(*argument_list)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 268, in patch
log.Log("Processing changed file %s" % diff.get_safeindexpath(), 5)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/log.py", line 148, in call
self.log_to_file(message)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/log.py", line 159, in log_to_file
self.logfp.write(tmpstr)

Exception 'Truncated header string (problem probably originated remotely)' raised of class '<class 'rdiff_backup.connection.ConnectionReadError'>':
File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 393, in error_check_Main
Main(arglist)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 415, in Main
take_action(rps)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 348, in take_action
connection.PipeConnection(sys.stdin.buffer, sys.stdout.buffer).Server()
File "/usr/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 422, in Server
self.get_response(-1)
File "/usr/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 379, in get_response
req_num, object = self._get()
File "/usr/lib64/python3.6/site-packages/rdiff_backup/connection.py", line 284, in _get
raise ConnectionReadError("Truncated header string (problem "

Fatal Error: Lost connection to the remote system

**Comment by ericzolf** [comment]
It still looks very much like the bug we've already encountered and fixed...

What's the output of `python -c 'import locale; print(locale.getpreferredencoding())'` on both sides?

**Comment by ASDBigmac** [comment]
Hi there,

Client:

asdbigmac@speedygonzales /tmp $ python -c 'import locale; print(locale.getpreferredencoding())'
UTF-8


Server: 

asdbigmac@Taz ~ $ python -c 'import locale; print(locale.getpreferredencoding())'
UTF-8

**Comment by ASDBigmac** [comment]
OK, after exchanging the log.py on both systems into the master one it started working. So I am closing this one as fixed by that patch released some days ago.
