### ISSUE TITLE
Backup from Windows to Windows share fails with KeyError inode

### ISSUE THREAD

**Issue by Infralin** [rdiff-backup/rdiff-backup#386]
## Bug summary

Backup from Windows to Windows share on another server fails with KeyError inode

## Version, Python, Operating System
Using rdiff-backup version 2.0.3 on Windows 7

```
C:\>c:\rdiff-backup\rdiff-backup.exe -v7 --override-chars-to-quote --no-eas --no-acls --no-compression --no-compare-inode --no-hard-links --terminal-v
erbosity 9 --print-statistics --exclude F:/$RECYCLE.BIN --exclude F:/"System Volume Information" F:/ X:/Data
2020-05-28 16:04:51.468517 +0200  <CLIENT-10952>  Using rdiff-backup version 2.0.3
2020-05-28 16:04:51.470517 +0200  <CLIENT-10952>        with cpython c:\rdiff-backup\rdiff-backup.exe version 3.7.5
2020-05-28 16:04:51.472518 +0200  <CLIENT-10952>        on Windows-7-6.1.7601-SP1, fs encoding utf-8
2020-05-28 16:04:51.490519 +0200  <CLIENT-10952>  Making directory X:/Data/rdiff-backup-data
2020-05-28 16:04:51.499520 +0200  <CLIENT-10952>  Hardlinks disabled by default on Windows
2020-05-28 16:04:51.501521 +0200  <CLIENT-10952>  Unable to import module (py)xattr.
Extended attributes not supported on filesystem at F:/
2020-05-28 16:04:51.504521 +0200  <CLIENT-10952>  POSIX ACLs test skipped. rdiff-backup run with --no-acls option.
2020-05-28 16:04:51.507521 +0200  <CLIENT-10952>  Windows ACLs test skipped. rdiff-backup run with --no-acls option.
2020-05-28 16:04:51.511522 +0200  <CLIENT-10952>  -----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         Off
  Extended attributes                          Off
  Windows access control lists                 Off
  Case sensitivity                             Off
  Escape DOS devices                           On
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
2020-05-28 16:04:51.543525 +0200  <CLIENT-10952>  Making directory X:/Data/rdiff-backup-data/rdiff-backup.tmp.0
2020-05-28 16:04:51.553526 +0200  <CLIENT-10952>  Touching X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/5-_ a.snapshot.gz
2020-05-28 16:04:51.562527 +0200  <CLIENT-10952>  Deleting X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/5-_ a.snapshot.gz
2020-05-28 16:04:51.582529 +0200  <CLIENT-10952>  Touching X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/uniá??
2020-05-28 16:04:51.590529 +0200  <CLIENT-10952>  Deleting X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/uniá??
2020-05-28 16:04:51.610531 +0200  <CLIENT-10952>  Touching X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/A
2020-05-28 16:04:51.621533 +0200  <CLIENT-10952>  Deleting X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/a
2020-05-28 16:04:51.642535 +0200  <CLIENT-10952>  Touching X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/foo
2020-05-28 16:04:51.651536 +0200  <CLIENT-10952>  Deleting X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/foo
2020-05-28 16:04:51.676538 +0200  <CLIENT-10952>  Making directory X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/hl
2020-05-28 16:04:51.686539 +0200  <CLIENT-10952>  Touching X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/hardlinked_file1
2020-05-28 16:04:51.695540 +0200  <CLIENT-10952>  Hard linking X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/hl/hardlinked_file2 to X:/Data/rdiff-backu
p-data/rdiff-backup.tmp.0/hardlinked_file1
2020-05-28 16:04:51.703541 +0200  <CLIENT-10952>  Exception ''inode'' raised of class '<class 'KeyError'>':
  File "rdiff_backup\Main.py", line 393, in error_check_Main
  File "rdiff_backup\Main.py", line 415, in Main
  File "rdiff_backup\Main.py", line 351, in take_action
  File "rdiff_backup\Main.py", line 427, in Backup
  File "rdiff_backup\fs_abilities.py", line 1044, in backup_set_globals
  File "rdiff_backup\fs_abilities.py", line 161, in init_readwrite
  File "rdiff_backup\fs_abilities.py", line 200, in set_hardlinks
  File "rdiff_backup\rpath.py", line 836, in getinode

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 393, in error_check_Main
  File "rdiff_backup\Main.py", line 415, in Main
  File "rdiff_backup\Main.py", line 351, in take_action
  File "rdiff_backup\Main.py", line 427, in Backup
  File "rdiff_backup\fs_abilities.py", line 1044, in backup_set_globals
  File "rdiff_backup\fs_abilities.py", line 161, in init_readwrite
  File "rdiff_backup\fs_abilities.py", line 200, in set_hardlinks
  File "rdiff_backup\rpath.py", line 836, in getinode
KeyError: 'inode'
[10952] Failed to execute script rdiff-backup
```

## rdiff-backup call

How did you call rdiff-backup, with which parameter:

```
C:\>c:\rdiff-backup\rdiff-backup.exe -v9 --override-chars-to-quote --no-eas --no-acls --no-compression --no-compare-inode --no-hard-links --terminal-verbosity 9 --print-statistics --exclude F:/$RECYCLE.BIN --exclude F:/"System Volume Information" F:/ X:/Data
```

## What happened and what did you expect?
Running rdiff-backup with the target (X:) pointing to a local disk (including an USB external disk) runs fine. When X: points to a share on the same computer rdiff-backup runs on, things work fine as well. When X: points to a share on another compter, either a Windows server or a Samba share on a Synology diskstation, things fail as reported.

I also performed the test without all the additional options.

The source directory (F:/) is a local disk.

## More information

If you can, please repeat the action leading to the error, adding the option `-v9` and attach the output to this bug report.

**Comment by ericzolf** [comment]
We'll look into it but it might take a bit of time to reproduce.

**Comment by ericzolf** [comment]
Trying to repeat your use case, I noticed that you use `--override-chars-to-quote` without parameter containing the characters to quote. You probably don't want to use this parameter, unless you know what you're doing.

Could you repeat the command without this parameter and attach here the result?

This said, I wasn't able yet to repeat your issue, at least not towards a Samba drive and not on Windows Server 2019 aka Windows 10:

```
> net use X: \\samba\readwriteshare
> rdiff-backup.exe -v9 --no-eas --no-acls --no-compression --no-compare-inode --no-hard-links --terminal-verbosity 9 --print-statistics C:\temp X:/Data
2020-06-04 07:44:55.809004 +0000  <CLIENT-4912>  Using rdiff-backup version 2.0.4.dev5+gbacfa9a 
2020-06-04 07:44:55.809004 +0000  <CLIENT-4912>         with cpython C:\Python37\Scripts\rdiff-backup.exe version 3.7.7
2020-06-04 07:44:55.809004 +0000  <CLIENT-4912>         on Windows-10-10.0.17763, fs encoding utf-8
2020-06-04 07:44:55.824708 +0000  <CLIENT-4912>  Deleting X:/Data/rdiff-backup-data/chars_to_quote
2020-06-04 07:44:55.840222 +0000  <CLIENT-4912>  Hardlinks disabled by default on Windows
[...]
2020-06-04 07:44:55.887094 +0000  <CLIENT-4912>  Making directory X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/hl     
2020-06-04 07:44:55.887094 +0000  <CLIENT-4912>  Touching X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/hardlinked_file1
2020-06-04 07:44:55.887094 +0000  <CLIENT-4912>  Hard linking X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/hl/hardlinked_file2 to X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/hardlinked_file1
2020-06-04 07:44:55.902747 +0000  <CLIENT-4912>  Directories on file system at X:/Data/rdiff-backup-data/rdiff-backup.tmp.0 are not fsyncable.
Assuming it's unnecessary.
2020-06-04 07:44:55.902747 +0000  <CLIENT-4912>  Extended attributes test skipped. rdiff-backup run with --no-eas option.
2020-06-04 07:44:55.902747 +0000  <CLIENT-4912>  POSIX ACLs test skipped. rdiff-backup run with --no-acls option.     
2020-06-04 07:44:55.902747 +0000  <CLIENT-4912>  Windows ACLs test skipped. rdiff-backup run with --no-acls option.   
2020-06-04 07:44:55.902747 +0000  <CLIENT-4912>  Touching X:/Data/rdiff-backup-data/rdiff-backup.tmp.0/dir_inc_check  
[...]
```

I'm unsure how to proceed from here as the issue could be the Windows version, the Samba setup or something completely different...

**Comment by ericzolf** [comment]
The last issue is most probably related to #371 and I'll ignore it. So your initial issue seems a difference between Windows 7 and 10... Windows 7 is out of support, I guess you're out of luck with this one. Why don't you upgrade to Windows 10, I read everywhere that it's still possible for free?

**Comment by ericzolf** [comment]
I've closed the issue, feel free to re-open if you can reproduce the issue under Windows 10.
