### ISSUE TITLE
[BUG] Writing to log file fails

### ISSUE THREAD

**Issue by user655362020** [rdiff-backup/rdiff-backup#391]
## Bug summary

Writing to log with -v9 fails. Worked with -v4

## Version, Python, Operating System
Binary downloaded from github, Windows 10
```
[4336] Failed to execute script rdiff-backup
2020-06-05 09:56:07.009867 +0530  <CLIENT-4336>  Using rdiff-backup version 2.0.3
2020-06-05 09:56:07.009867 +0530  <CLIENT-4336>  	with cpython C:\Users\User1\Downloads\rdiff\rdiff-backup.exe version 3.7.5
2020-06-05 09:56:07.009867 +0530  <CLIENT-4336>  	on Windows-10-10.0.18362, fs encoding utf-8
2020-06-05 09:56:07.009867 +0530  <CLIENT-4336>  Making directory H:/rdiff/D-Data/rdiff-backup-data
2020-06-05 09:56:07.009867 +0530  <CLIENT-4336>  Hardlinks disabled by default on Windows
2020-06-05 09:56:07.009867 +0530  <CLIENT-4336>  Unable to import module (py)xattr.
Extended attributes not supported on filesystem at D:/
2020-06-05 09:56:07.009867 +0530  <CLIENT-4336>  Unable to import module posix1e from pylibacl package.
POSIX ACLs not supported on filesystem at D:/
2020-06-05 09:56:07.025402 +0530  <CLIENT-4336>  -----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         Off
  Extended attributes                          Off
  Windows access control lists                 On
  Case sensitivity                             Off
  Escape DOS devices                           On
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
2020-06-05 09:56:07.025402 +0530  <CLIENT-4336>  Making directory H:/rdiff/D-Data/rdiff-backup-data/rdiff-backup.tmp.0
2020-06-05 09:56:07.025402 +0530  <CLIENT-4336>  Touching H:/rdiff/D-Data/rdiff-backup-data/rdiff-backup.tmp.0/5-_ a.snapshot.gz
2020-06-05 09:56:07.025402 +0530  <CLIENT-4336>  Deleting H:/rdiff/D-Data/rdiff-backup-data/rdiff-backup.tmp.0/5-_ a.snapshot.gz
2020-06-05 09:56:07.025402 +0530  <CLIENT-4336>  Exception ''charmap' codec can't encode characters in position 115-116: character maps to <undefined>' raised of class '<class 'UnicodeEncodeError'>':
  File "rdiff_backup\Main.py", line 393, in error_check_Main
  File "rdiff_backup\Main.py", line 415, in Main
  File "rdiff_backup\Main.py", line 351, in take_action
  File "rdiff_backup\Main.py", line 427, in Backup
  File "rdiff_backup\fs_abilities.py", line 1044, in backup_set_globals
  File "rdiff_backup\fs_abilities.py", line 157, in init_readwrite
  File "rdiff_backup\fs_abilities.py", line 241, in set_extended_filenames
  File "rdiff_backup\rpath.py", line 1248, in touch
  File "rdiff_backup\log.py", line 150, in __call__
  File "rdiff_backup\log.py", line 173, in log_to_term
  File "c:\users\travis\.pyenv\pyenv-win\versions\3.7.5\lib\encodings\cp1252.py", line 19, in encode

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 393, in error_check_Main
  File "rdiff_backup\Main.py", line 415, in Main
  File "rdiff_backup\Main.py", line 351, in take_action
  File "rdiff_backup\Main.py", line 427, in Backup
  File "rdiff_backup\fs_abilities.py", line 1044, in backup_set_globals
  File "rdiff_backup\fs_abilities.py", line 157, in init_readwrite
  File "rdiff_backup\fs_abilities.py", line 241, in set_extended_filenames
  File "rdiff_backup\rpath.py", line 1248, in touch
  File "rdiff_backup\log.py", line 150, in __call__
  File "rdiff_backup\log.py", line 173, in log_to_term
  File "c:\users\travis\.pyenv\pyenv-win\versions\3.7.5\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 115-116: character maps to <undefined>

```

## rdiff-backup call

How did you call rdiff-backup, with which parameter:

```
rdiff-backup -v9 --exclude-if-present ".nobackup" --exclude-if-present ".archive" --exclude "**/Downloads" --exclude "**/downloads" --exclude "**/System Volume Information" --exclude "**/$RECYCLE.BIN" --exclude-other-filesystems --no-compression-regexp --verify "D:/" "H:/rdiff/D-Data" > v9.txt 2>&1
```
It works when I remove ```> v9.txt 2>&1```

**Comment by ericzolf** [comment]
Windows always surprises me... But I think that we've already fixed your issue in PR #371 
Can you have a check?

**Comment by user655362020** [comment]
Is there any place from where I can get windows binary built against master branch ? I have no experience coding or building binaries.

**Comment by ericzolf** [comment]
OK, no problem, sorry for letting you wait. I'm quite confident that we've fixed it so I close the issue, we'll release soon a new version and you can then test it. Feel free to re-open the bug if you see the necessity.
