### ISSUE TITLE
[BUG] Backslash in end of path on Windows

### ISSUE THREAD

**Issue by seihtam** [rdiff-backup/rdiff-backup#395]
## Bug summary
rdiff-backup crashes if there is a backslash at the end of a folder name on Windows. This issue is an inconvenience since when you autocomplete a folder name in Windows Command Prompt it will include the backslash.

## Version, Python, Operating System
```
2020-06-07 15:01:17.983568 +0200  <CLIENT-13984>  Using rdiff-backup version 2.0.3
2020-06-07 15:01:17.983568 +0200  <CLIENT-13984>        with cpython C:\rdiff-backup.exe version 3.7.5
2020-06-07 15:01:17.984569 +0200  <CLIENT-13984>        on Windows-10-10.0.18362, fs encoding utf-8
2020-06-07 15:01:17.984569 +0200  <CLIENT-13984>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.
```

## rdiff-backup call
```
>rdiff-backup.exe a\ b\
Exception 'Unexpected end to file description b'a\\'' raised of class '<class 'rdiff_backup.SetConnections.SetConnectionsException'>':
  File "rdiff_backup\Main.py", line 393, in error_check_Main
  File "rdiff_backup\Main.py", line 410, in Main
  File "rdiff_backup\SetConnections.py", line 66, in get_cmd_pairs
  File "rdiff_backup\SetConnections.py", line 128, in parse_file_desc
  File "rdiff_backup\SetConnections.py", line 113, in check_len

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 393, in error_check_Main
  File "rdiff_backup\Main.py", line 410, in Main
  File "rdiff_backup\SetConnections.py", line 66, in get_cmd_pairs
  File "rdiff_backup\SetConnections.py", line 128, in parse_file_desc
  File "rdiff_backup\SetConnections.py", line 113, in check_len
rdiff_backup.SetConnections.SetConnectionsException: Unexpected end to file description b'a\\'
[14104] Failed to execute script rdiff-backup
```

## What happened and what did you expect?
It should backup as normal as it's a valid path on Windows.

**Comment by ericzolf** [comment]
Small bug, there is a workaround, we'll fix it in due time. Thanks for reporting.
