### ISSUE TITLE
[BUG] Exception when trying to remove a directory

### ISSUE THREAD

**Issue by g-v-egidy** [rdiff-backup/rdiff-backup#403]
## Bug summary
I got the exception shown below during a regular backup run. It seems rdiff-backup tries to delete a non-empty directory

## Version, Python, Operating System

rdiff-backup-2.0.3 on CentOS 7 x86_64, python 3.6.8

## rdiff-backup call

How did you call rdiff-backup, with which parameter:

```
rdiff-backup --force --no-compression --print-statistics --exclude-fifos --exclude-sockets / /mnt/backup
```

## What happened and what did you expect?
This was a regular backup run, some files have changed since the last execution of rdiff-backup. 

The directory /usr/lib/modules/3.10.0-1062.4.3.el7.x86_64 was removed from the filesystem since the last run.

The backup run aborted with this exception:
```
Exception '[Errno 39] Directory not empty: b'/mnt/backup/usr/lib/modules/3.10.0-1062.4.3.el7.x86_64/weak-updates'' raised of class '<class 'OSError'>':
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 393, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 415, in Main
    take_action(rps)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 351, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 437, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 55, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 281, in patch_and_increment
    ITR(diff.index, diff)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rorpiter.py", line 309, in __call__
    if self.finish_branches(index) is None:
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rorpiter.py", line 256, in finish_branches
    to_be_finished.end_process()
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 760, in end_process
    self.base_rp.rmdir()
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rpath.py", line 1212, in rmdir
    self.conn.os.rmdir(self.path)

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 393, in error_check_Main
    Main(arglist)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 415, in Main
    take_action(rps)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 351, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/Main.py", line 437, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 55, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 281, in patch_and_increment
    ITR(diff.index, diff)
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rorpiter.py", line 309, in __call__
    if self.finish_branches(index) is None:
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rorpiter.py", line 256, in finish_branches
    to_be_finished.end_process()
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/backup.py", line 760, in end_process
    self.base_rp.rmdir()
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/rpath.py", line 1212, in rmdir
    self.conn.os.rmdir(self.path)
OSError: [Errno 39] Directory not empty: b'/mnt/backup/usr/lib/modules/3.10.0-1062.4.3.el7.x86_64/weak-updates'
```

After the exception the directory /mnt/backup/usr/lib/modules/3.10.0-1062.4.3.el7.x86_64/weak-updates was empty and I was able to manually delete it with rmdir on the commandline without problems.

The system did not log any filesystem or disk errors and a subsequent filesystem check of the backup disk came up with no errors. Both the source filesystem and backup filesystem are ext4, but on different disks.

This is the first time I have seen this, and a lot of directories were deleted over the last weeks. I was not able to reproduce it. So I think this is some kind of race condition.

**Comment by ericzolf** [comment]
Thanks for the feedback, there is just very (too) little to start with. If you can find more specifics, let us know.

**Comment by g-v-egidy** [comment]
One thing that might be of interest is that the "weak-updates" directory usually does not contain files, but just more subdirectories.

But other than that I don't have any more info. As I can't reproduce it in a test environment, I'll just have to let the system continue to run as it is and see when it happens the next time. But I fear that I'll then just get a similar backtrace and not anything more you can work with.

Do you have any suggestions for adding debug output to this code path, so that I can provide you with more helpful info when it happens the next time?

**Comment by ericzolf** [comment]
Call rdiff-backup with -v9 to get more info.

**Comment by g-v-egidy** [comment]
As I can't reproduce it on purpose, I'd have to run it with -v9 in the production environment for weeks or months until it happens again. This produces waay too much output to be a workable solution for me.

Do you have an option to get just errors and warnings on stdout/stderr like before, but store the full -v9 output into a separate file? Then I could always run it with -v9 and ignore and overwrite the file for all cases but these exceptions.

**Comment by ericzolf** [comment]
Yes, there is: just set `--terminal-verbosity` to whatever you want (3 is the default) and the terminal will stop using the verbosity from `-v/--verbosity`.

**Comment by ericzolf** [comment]
This bug is more than one year old, closing.
