### ISSUE TITLE
Exception '' raised of class '<type 'exceptions.AssertionError'>'

### ISSUE THREAD

**Issue by erwannr** [rdiff-backup/rdiff-backup#43]
I am trying `rdiff-backup` for the first time. It seems buggy:
```
~$ uname -a
Linux laptop 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
~ $ rdiff-backup --version
rdiff-backup 1.2.8
~ $ rdiff-backup Documents/Inbox /media/er/Vol2/backup/laptop
Exception '' raised of class '<type 'exceptions.AssertionError'>':
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 334, in Backup
    rpout.conn.fs_abilities.backup_set_globals(rpin, force)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py", line 922, in backup_set_globals
    dest_fsa = FSAbilities('destination').init_readwrite(Globals.rbdir)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py", line 156, in init_readwrite
    self.set_case_sensitive_readwrite(subdir)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py", line 304, in set_case_sensitive_readwrite
    assert not upper_a.lstat()

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 30, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 334, in Backup
    rpout.conn.fs_abilities.backup_set_globals(rpin, force)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py", line 922, in backup_set_globals
    dest_fsa = FSAbilities('destination').init_readwrite(Globals.rbdir)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py", line 156, in init_readwrite
    self.set_case_sensitive_readwrite(subdir)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/fs_abilities.py", line 304, in set_case_sensitive_readwrite
    assert not upper_a.lstat()
AssertionError

/media/er/Vol2/backup/laptop $ ls -R
.:
rdiff-backup-data

./rdiff-backup-data:
rdiff-backup.tmp.0

./rdiff-backup-data/rdiff-backup.tmp.0:

```

**Comment by ericzolf** [comment]
It would be good if you could retry the issue with a recent version from Git on master branch (see DEVELOP.md for details on how to do it) or unpack as root the attached 
[rdiff-backup-1.3.5.linux-x86_64.tar.gz](https://github.com/rdiff-backup/rdiff-backup/files/3774626/rdiff-backup-1.3.5.linux-x86_64.tar.gz).

Can it be that the media where the backup was, was formatted as vfat or similar? I suspect another form of #11 #38 #45

**Comment by ericzolf** [comment]
Yep, looks definitely like #38 (I oversaw the `assert not upper_a.lstat()`). Just tell me the media's file system format, probably no need to re-test, we'll fix all together.

**Comment by erwannr** [comment]
I'm confused about the attachment: the files in /usr/local/bin seems to be
python but have no py extension. I expected sh. That's what I'd get if I
installed using apt install, but the version would be older. I also tried
installing from a cloned repo and it did not work. As for the fs format of
the destination folder in the  #43 it is ntfs a.k.a fuse.

**Comment by erwannr** [comment]
PS: I take back the first two sentences. Regardless, the binary you gave as
an attachment also fails.

**Comment by ericzolf** [comment]
OK, NTFS is also kind of case insensitive but not really, so I consider your issue as duplicate, Follow up on issue #11 - but don't expect miracles, it could take a while to fix.
