### ISSUE TITLE
Fail with MemoryError on Windows 64 bits using stattest

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#453]
It has even nothing to do with the testcase, I can reproduce the issue with the following snippet under Windows:

```
rdiff-backup ..\rdiff-backup_testfiles\stattest1 \temp\bla
rdiff-backup ..\rdiff-backup_testfiles\stattest2 \temp\bla
```

Or vice-versa, no difference: the first call succeeds, the 2nd one fails.

_Originally posted by @ericzolf in https://github.com/rdiff-backup/rdiff-backup/issues/347#issuecomment-674368766_

```
vagrant@WIN-4SPEID5E7R8 C:\Users\vagrant\Develop\rdiff-backup>rmdir /s /q \temp\bla

vagrant@WIN-4SPEID5E7R8 C:\Users\vagrant\Develop\rdiff-backup>rdiff-backup ..\rdiff-backup_testfiles\stattest1 \temp\bla

vagrant@WIN-4SPEID5E7R8 C:\Users\vagrant\Develop\rdiff-backup>rdiff-backup ..\rdiff-backup_testfiles\stattest2 \temp\bla
Exception '' raised of class '<class 'MemoryError'>':
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\robust.py", line 35, in check_common_error    
    return function(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Rdiff.py", line 98, in patch_local
    return outrp.write_from_fileobj(patchfile)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rpath.py", line 1462, in write_from_fileobj   
    copyfileobj(fp, outfp)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rpath.py", line 79, in copyfileobj
    inbuf = inputfp.read(blocksize)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\librsync.py", line 69, in read
    self._add_to_outbuf_once()
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\librsync.py", line 98, in _add_to_outbuf_once 
    self.eof, len_inbuf_read, cycle_out = self.maker.cycle(self.inbuf)

Exception '' raised of class '<class 'MemoryError'>':
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 399, in error_check_Main
    _Main(arglist)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 421, in _Main
    return_val = _take_action(rps)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 358, in _take_action
    action_result = _action_backup(rps[0], rps[1])
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 445, in _action_backup
    backup.Mirror_and_increment(rpin, rpout, _incdir)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 55, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 281, in patch_and_increment
    ITR(diff.index, diff)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rorpiter.py", line 313, in __call__
    last_branch.fast_process(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 781, in fast_process
    if self._patch_to_temp(mirror_rp, diff_rorp, tf):
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 617, in _patch_to_temp
    elif not self._patch_diff_to_temp(basis_rp, diff_rorp, new):
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 669, in _patch_diff_to_temp
    self.error_handler, Rdiff.patch_local, (basis_rp, diff_rorp, new))
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\robust.py", line 35, in check_common_error
    return function(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Rdiff.py", line 98, in patch_local
    return outrp.write_from_fileobj(patchfile)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rpath.py", line 1462, in write_from_fileobj
    copyfileobj(fp, outfp)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rpath.py", line 79, in copyfileobj
    inbuf = inputfp.read(blocksize)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\librsync.py", line 69, in read
    self._add_to_outbuf_once()
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\librsync.py", line 98, in _add_to_outbuf_once
    self.eof, len_inbuf_read, cycle_out = self.maker.cycle(self.inbuf)

Traceback (most recent call last):
  File "C:\Users\vagrant\Develop\rdiff-backup\build\scripts-3.7\rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 399, in error_check_Main
    _Main(arglist)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 421, in _Main
    return_val = _take_action(rps)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 358, in _take_action
    action_result = _action_backup(rps[0], rps[1])
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 445, in _action_backup
    backup.Mirror_and_increment(rpin, rpout, _incdir)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 55, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 281, in patch_and_increment
    ITR(diff.index, diff)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rorpiter.py", line 313, in __call__
    last_branch.fast_process(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 781, in fast_process
    if self._patch_to_temp(mirror_rp, diff_rorp, tf):
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 617, in _patch_to_temp
    elif not self._patch_diff_to_temp(basis_rp, diff_rorp, new):
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 669, in _patch_diff_to_temp
    self.error_handler, Rdiff.patch_local, (basis_rp, diff_rorp, new))
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\robust.py", line 35, in check_common_error
    return function(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Rdiff.py", line 98, in patch_local
    return outrp.write_from_fileobj(patchfile)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rpath.py", line 1462, in write_from_fileobj
    copyfileobj(fp, outfp)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rpath.py", line 79, in copyfileobj
    inbuf = inputfp.read(blocksize)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\librsync.py", line 69, in read
    self._add_to_outbuf_once()
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\librsync.py", line 98, in _add_to_outbuf_once
    self.eof, len_inbuf_read, cycle_out = self.maker.cycle(self.inbuf)
MemoryError
```

**Comment by ericzolf** [comment]
The issue is already in v2.0.5 so the recent changes didn't introduce it.
@t9t can you reproduce the issue or you don't have it? I could imagine that it has to do with the version of librsync or of the compiler. Which versions are you exactly using?

**Comment by t9t** [comment]
@ericzolf Yes, sorry I have encountered this one too but forgot to create an issue for it yet as I've been pretty occupied with other things over the past week.

 I did a lot of searching on the internet, but most of the results only indicate that a `MemoryError` occurs when running out of memory, which is definitely not the case here. It happens on a line where the C module is called, so I believe it has something to do with,... let's call it "memory corruption" because I don't really understand what's really going on. I had tried debugging the C code and the Python code, but it's really difficult to pinpoint exactly where it goes wrong. From just analyzing the C code I don't see anything strange going on (like memory being freed before returning objects or something like that) but then again I don't know enough about Python C modules to really say much about that.

I'm running a 64 bit Windows, and when using a 64 bit Python and compiling librsync for `x64` I got this error. However, when using a 32 bit Python and compiling librsync for `Win32` (still on a 64 bit Windows) I did not get this error. So that is what I've been using since to avoid this issue.

**Comment by ericzolf** [comment]
No issue, it looks like we have time to fix this issue as long as we continue to provide only 32 bits binaries (I was wondering why the issue didn't appear at users).

Regarding the error itself, you can also get a memory error if you read too much bytes because something went wrong with the calculation of the buffer length (in the present case, I would guess `len_inbuf_read`). Based on your description, I could imagine that we have a size/integer manipulation error somewhere, probably in the C code, which appears only under 64 bits, either because 32 bits are small enough (~4GB) that it doesn't give enough reason for a MemoryError or because some assumptions are made on the number of bits. Why the issue appears under Windows and not Linux, another mystery, possibly different handling of types and overflows by different compilers and systems...

@dbaarda I trust more your C knowledge than mine, if you have a hint for us?! Nothing urgent, as written above, just if you have time.

**Comment by dbaarda** [comment]
So this happens with 64 bit windows but not 64 bit linux?

If yes, then it must be subtle compiler differences, possibly in the size of int, or maybe signed-ness of size_t or something.

It's not impossible that it's in librsync itself, but I feel like it's more likely in your python c-module calling it. I'll try to have a look tomorrow.

**Comment by ericzolf** [comment]
> So this happens with 64 bit windows but not 64 bit linux?

Correct. Exactly the same test doesn't fail under Linux.

> If yes, then it must be subtle compiler differences, possibly in the size of int, or maybe signed-ness of size_t or something.
> 
> It's not impossible that it's in librsync itself, but I feel like it's more likely in your python c-module calling it. I'll try to have a look tomorrow.

I would tend to agree, and really take your time. Thanks for your kind offer.
