### ISSUE TITLE
[BUG] Unexpected MemoryError on increment

### ISSUE THREAD

**Issue by xastor** [rdiff-backup/rdiff-backup#496]
## Bug summary

In some cases a backup increment over ssh fails unexpectedly with a MemoryError.  Subsequent backups have the same error.

## Version, Python, Operating System

Call `rdiff-backup --version --api-version 201` or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```yaml
PS C:\Users\Pieter.Bonne> D:\repos\backup_manager\rdiff-backup-test\rdiff-backup.exe -v9
2020-12-21 21:25:03.230011 +0100  <CLIENT-19452>  Using rdiff-backup version 2.0.5
2020-12-21 21:25:03.230011 +0100  <CLIENT-19452>        with cpython D:\repos\backup_manager\rdiff-backup-test\rdiff-backup.exe version 3.7.7
2020-12-21 21:25:03.230011 +0100  <CLIENT-19452>        on Windows-10-10.0.18362, fs encoding utf-8
2020-12-21 21:25:03.231011 +0100  <CLIENT-19452>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
D:\repos\backup_manager\rdiff-backup-test\rdiff-backup.exe -v5 --exclude-symbolic-links --remote-schema "C:\Windows\System32\OpenSSH\ssh.exe %s /usr/local/bin/rdiff-backup --server" --include "/root/db_dumps**" --include "/etc/apache2**" --include "/var/www**"  --exclude "**" --print-statistics "root@1.2.3.4::/" "D:\Backups\product-test"
```

## What happened and what did you expect?

I expected a successful backup increment.  

## More information

I'm backing up from a remote server to a local disk.

- The initial backup was successful.
- After that, I updated one of the database dump files on the server (166Mb)
- Any backups after this have the MemoryError error.

Below is a log where the MemoryError occurs : 

```
PS C:\Users\Pieter.Bonne> D:\repos\backup_manager\rdiff-backup-test\rdiff-backup.exe -v5 --exclude-symbolic-links --remote-schema "C:\Windows\System32\OpenSSH\ssh.exe %s /usr/local/bin/rdiff-backup --server" --include "/root/db_dumps**" --include "/etc/apache2**" --include "/var/www**"  --exclude "**" --print-statistics "root@1.2.3.4::/" "D:\Backups\product-test"
Exception '' raised of class '<class 'MemoryError'>':
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\increment.py", line 45, in Increment
  File "rdiff_backup\increment.py", line 105, in makediff
  File "rdiff_backup\Rdiff.py", line 77, in write_delta
  File "rdiff_backup\librsync.py", line 150, in __init__
  File "rdiff_backup\librsync.py", line 74, in read
  File "rdiff_backup\librsync.py", line 90, in _add_to_outbuf_once

Exception '' raised of class '<class 'MemoryError'>':
  File "rdiff_backup\Main.py", line 395, in error_check_Main
  File "rdiff_backup\Main.py", line 417, in Main
  File "rdiff_backup\Main.py", line 353, in take_action
  File "rdiff_backup\Main.py", line 439, in Backup
  File "rdiff_backup\backup.py", line 55, in Mirror_and_increment
  File "rdiff_backup\backup.py", line 281, in patch_and_increment
  File "rdiff_backup\rorpiter.py", line 313, in __call__
  File "rdiff_backup\backup.py", line 784, in fast_process
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\increment.py", line 45, in Increment
  File "rdiff_backup\increment.py", line 105, in makediff
  File "rdiff_backup\Rdiff.py", line 77, in write_delta
  File "rdiff_backup\librsync.py", line 150, in __init__
  File "rdiff_backup\librsync.py", line 74, in read
  File "rdiff_backup\librsync.py", line 90, in _add_to_outbuf_once

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 395, in error_check_Main
  File "rdiff_backup\Main.py", line 417, in Main
  File "rdiff_backup\Main.py", line 353, in take_action
  File "rdiff_backup\Main.py", line 439, in Backup
  File "rdiff_backup\backup.py", line 55, in Mirror_and_increment
  File "rdiff_backup\backup.py", line 281, in patch_and_increment
  File "rdiff_backup\rorpiter.py", line 313, in __call__
  File "rdiff_backup\backup.py", line 784, in fast_process
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\increment.py", line 45, in Increment
  File "rdiff_backup\increment.py", line 105, in makediff
  File "rdiff_backup\Rdiff.py", line 77, in write_delta
  File "rdiff_backup\librsync.py", line 150, in __init__
  File "rdiff_backup\librsync.py", line 74, in read
  File "rdiff_backup\librsync.py", line 90, in _add_to_outbuf_once
MemoryError
[16920] Failed to execute script rdiff-backup
Using rdiff-backup version 2.0.5
        with cpython D:\repos\backup_manager\rdiff-backup-test\rdiff-backup.exe version 3.7.7
        on Windows-10-10.0.18362, fs encoding utf-8
Executing C:\Windows\System32\OpenSSH\ssh.exe root@1.2.3.4 /usr/local/bin/rdiff-backup --server
-----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Directories on file system at D:/Backups/product-test/rdiff-backup-data/rdiff-backup.tmp.0 are not fsyncable.
Assuming it's unnecessary.
Unable to import module (py)xattr.
Extended attributes not supported on filesystem at D:/Backups/product-test/rdiff-backup-data/rdiff-backup.tmp.0
Unable to import module posix1e from pylibacl package.
POSIX ACLs not supported on filesystem at D:/Backups/product-test/rdiff-backup-data/rdiff-backup.tmp.0
Unable to load a Windows ACL.
Windows ACLs not supported by filesystem at D:/Backups/product-test/rdiff-backup-data/rdiff-backup.tmp.0
-----------------------------------------------------------------
Detected abilities for destination (read/write) file system:
  Ownership changing                           Off
  Hard linking                                 On
  fsync() directories                          Off
  Directory inc permissions                    Off
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   On
  Access control lists                         Off
  Extended attributes                          Off
  Windows access control lists                 Off
  Case sensitivity                             Off
  Escape DOS devices                           On
  Escape trailing spaces                       On
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Backup: escape_dos_devices = 1
Backup: escape_trailing_spaces = 1
Enabled use_compatible_timestamps
Starting increment operation / to D:/Backups/product-test
Processing changed file .
Incrementing mirror file D:/Backups/product-test
Processing changed file root
Incrementing mirror file D:/Backups/product-test/root
Processing changed file root/db_dumps
Incrementing mirror file D:/Backups/product-test/root/db_dumps
Processing changed file root/db_dumps/db_company_product.sql
Incrementing mirror file D:/Backups/product-test/root/db_dumps/db_company_product.sql
Unable to import win32security module. Windows ACLs
not supported by filesystem at /
Fatal Error: Lost connection to the remote system
```

If I try to backup again after this failure, rdiff-backup starts regressing (seemingly iterating over all files) and then has the same problem again.  Below is a -v9 log of such an error (right after the regression part) : 

```
2020-12-21 21:24:46.767301 +0100  <CLIENT-18548>  Previous backup seems to have failed, regressing destination now.
2020-12-21 21:28:30.923569 +0100  <CLIENT-18548>  Exception '' raised of class '<class 'MemoryError'>':
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\increment.py", line 45, in Increment
  File "rdiff_backup\increment.py", line 105, in makediff
  File "rdiff_backup\Rdiff.py", line 77, in write_delta
  File "rdiff_backup\librsync.py", line 150, in __init__
  File "rdiff_backup\librsync.py", line 74, in read
  File "rdiff_backup\librsync.py", line 90, in _add_to_outbuf_once

2020-12-21 21:28:30.924570 +0100  <CLIENT-18548>  Exception '' raised of class '<class 'MemoryError'>':
  File "rdiff_backup\Main.py", line 395, in error_check_Main
  File "rdiff_backup\Main.py", line 417, in Main
  File "rdiff_backup\Main.py", line 353, in take_action
  File "rdiff_backup\Main.py", line 439, in Backup
  File "rdiff_backup\backup.py", line 55, in Mirror_and_increment
  File "rdiff_backup\backup.py", line 281, in patch_and_increment
  File "rdiff_backup\rorpiter.py", line 313, in __call__
  File "rdiff_backup\backup.py", line 784, in fast_process
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\increment.py", line 45, in Increment
  File "rdiff_backup\increment.py", line 105, in makediff
  File "rdiff_backup\Rdiff.py", line 77, in write_delta
  File "rdiff_backup\librsync.py", line 150, in __init__
  File "rdiff_backup\librsync.py", line 74, in read
  File "rdiff_backup\librsync.py", line 90, in _add_to_outbuf_once

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 395, in error_check_Main
  File "rdiff_backup\Main.py", line 417, in Main
  File "rdiff_backup\Main.py", line 353, in take_action
  File "rdiff_backup\Main.py", line 439, in Backup
  File "rdiff_backup\backup.py", line 55, in Mirror_and_increment
  File "rdiff_backup\backup.py", line 281, in patch_and_increment
  File "rdiff_backup\rorpiter.py", line 313, in __call__
  File "rdiff_backup\backup.py", line 784, in fast_process
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\increment.py", line 45, in Increment
  File "rdiff_backup\increment.py", line 105, in makediff
  File "rdiff_backup\Rdiff.py", line 77, in write_delta
  File "rdiff_backup\librsync.py", line 150, in __init__
  File "rdiff_backup\librsync.py", line 74, in read
  File "rdiff_backup\librsync.py", line 90, in _add_to_outbuf_once
MemoryError
[18548] Failed to execute script rdiff-backup
2020-12-21 21:28:30.737781 +0100  <CLIENT-18548>  Processing changed file .
2020-12-21 21:28:30.738820 +0100  <CLIENT-18548>  Incrementing mirror file D:/Backups/product-test
2020-12-21 21:28:30.738820 +0100  <CLIENT-18548>  Touching D:/Backups/product-test/rdiff-backup-data/increments.2020-12-21;08421-14-13+01-00.dir
2020-12-21 21:28:30.738820 +0100  <CLIENT-18548>  Copying inc attrs from () to D:/Backups/product-test/rdiff-backup-data/increments.2020-12-21;08421-14-13+01-00.dir
2020-12-21 21:28:30.739811 +0100  <CLIENT-18548>  Setting time of D:/Backups/product-test/rdiff-backup-data/increments.2020-12-21;08421-14-13+01-00.dir to 1606891878
2020-12-21 21:28:30.752598 +0100  <CLIENT-18548>  Processing changed file root
2020-12-21 21:28:30.753572 +0100  <CLIENT-18548>  Incrementing mirror file D:/Backups/product-test/root
2020-12-21 21:28:30.753572 +0100  <CLIENT-18548>  Touching D:/Backups/product-test/rdiff-backup-data/increments/root.2020-12-21;08421-14-13+01-00.dir
2020-12-21 21:28:30.754572 +0100  <CLIENT-18548>  Copying inc attrs from (b'root',) to D:/Backups/product-test/rdiff-backup-data/increments/root.2020-12-21;08421-14-13+01-00.dir
2020-12-21 21:28:30.754572 +0100  <CLIENT-18548>  Setting time of D:/Backups/product-test/rdiff-backup-data/increments/root.2020-12-21;08421-14-13+01-00.dir to 1591088207
2020-12-21 21:28:30.756581 +0100  <CLIENT-18548>  Processing changed file root/db_dumps
2020-12-21 21:28:30.757584 +0100  <CLIENT-18548>  Incrementing mirror file D:/Backups/product-test/root/db_dumps
2020-12-21 21:28:30.757584 +0100  <CLIENT-18548>  Touching D:/Backups/product-test/rdiff-backup-data/increments/root/db_dumps.2020-12-21;08421-14-13+01-00.dir
2020-12-21 21:28:30.757584 +0100  <CLIENT-18548>  Copying inc attrs from (b'root', b'db_dumps') to D:/Backups/product-test/rdiff-backup-data/increments/root/db_dumps.2020-12-21;08421-14-13+01-00.dir
2020-12-21 21:28:30.758572 +0100  <CLIENT-18548>  Setting time of D:/Backups/product-test/rdiff-backup-data/increments/root/db_dumps.2020-12-21;08421-14-13+01-00.dir to 1494928490
2020-12-21 21:28:30.760576 +0100  <CLIENT-18548>  Processing changed file root/db_dumps/db_company_product.sql
2020-12-21 21:28:30.761573 +0100  <CLIENT-18548>  Writing file object to D:/Backups/product-test/root/db_dumps/rdiff-backup.tmp.23723
2020-12-21 21:28:30.920575 +0100  <CLIENT-18548>  Copying attributes from (b'root', b'db_dumps', b'db_company_product.sql') to D:/Backups/product-test/root/db_dumps/rdiff-backup.tmp.23723
2020-12-21 21:28:30.921567 +0100  <CLIENT-18548>  Setting time of D:/Backups/product-test/root/db_dumps/rdiff-backup.tmp.23723 to 1608581763
2020-12-21 21:28:30.921567 +0100  <CLIENT-18548>  Incrementing mirror file D:/Backups/product-test/root/db_dumps/db_company_product.sql
2020-12-21 21:28:30.921567 +0100  <CLIENT-18548>  Writing delta D:/Backups/product-test/root/db_dumps/rdiff-backup.tmp.23723 from D:/Backups/product-test/root/db_dumps/db_company_product.sql -> D:/Backups/product-test/rdiff-backup-data/increments/root/db_dumps/db_company_product.sql.2020-12-21;08421-14-13+01-00.diff.gz
2020-12-21 21:28:30.921567 +0100  <CLIENT-18548>  Getting signature of root/db_dumps/rdiff-backup.tmp.23723 with blocksize 13184
2020-12-21 20:28:30.957487 +0000  <SERVER-117201>  Exception 'Truncated header string (problem probably originated remotely)' raised of class '<class 'rdiff_backup.connection.ConnectionReadError'>':
  File "/usr/local/lib/python3.5/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
    Main(arglist)
  File "/usr/local/lib/python3.5/dist-packages/rdiff_backup/Main.py", line 417, in Main
    take_action(rps)
  File "/usr/local/lib/python3.5/dist-packages/rdiff_backup/Main.py", line 350, in take_action
    connection.PipeConnection(sys.stdin.buffer, sys.stdout.buffer).Server()
  File "/usr/local/lib/python3.5/dist-packages/rdiff_backup/connection.py", line 422, in Server
    self.get_response(-1)
  File "/usr/local/lib/python3.5/dist-packages/rdiff_backup/connection.py", line 379, in get_response
    req_num, object = self._get()
  File "/usr/local/lib/python3.5/dist-packages/rdiff_backup/connection.py", line 284, in _get
    raise ConnectionReadError("Truncated header string (problem "

2020-12-21 20:28:30.957560 +0000  <SERVER-117201>  Fatal Error: Lost connection to the remote system
```

- When I remove the database dump sql file from the server, the backup completes successfully again.
- When I add the database dump sql file again, the backup initially completes successfully again.
- When I update the database dump sql file, the backup fails again!

It seems that changes to a big file cause this issue, but that may be just an impression.

Thank you for any insights you may have!

**Comment by ericzolf** [comment]
I assume you're using the version I provided to you, could you try again with the official version? I'm also doing back-ups of bigger files so I don't expect that it is the issue by itself but I currently don't have a clue what's going on.

**Comment by xastor** [comment]
Hi, I'm indeed using the test version you provided.

I can't try this with the official 2.0.5 build because I can't get the remote-schema to work with that version.  When I try just 'ssh.exe' as you suggested before, I get the same problem.

**Comment by ericzolf** [comment]
Your statement confused me a bit, which same problem did you get with official build + ssh.exe? The previous SSH or the current big file issue?

On my side, I've done some tests and I guess that your issue with the inofficial build is due to the fact that I've built it with 64 bits, and you're hitting #453

My recommendation, given that you shouldn't need to use the full path to SSH.exe (I'm not even sure why you would need to define the schema in your case, assuming /usr/local/bin is in your path), would be to stick to the official version (32 bits exe).

**Comment by xastor** [comment]
Hi, I was referring to your comment here: https://github.com/rdiff-backup/rdiff-backup/issues/494#issuecomment-748473571

> Just replacing C:\Windows\System32\OpenSSH\ssh.exe with ssh.exe works.

When I make this replacement I still get the same error, so I can't provide you with a log using the official build.  Maybe I missed something?  Also, I'm running in windows on the client-side, so I have no `/usr/local/bin`, but `C:\Windows\System32\OpenSSH` is in my path.

I'll use the official 2.0.5 32-bit version for more testing.

**Comment by xastor** [comment]
Hi, I was able to work around this problem by using the 32-bit rdiff-backup-2.0.5 and putty's plink.exe utility.  This does seem to confirm the 64-version has problems incrementing on big files!

What I don't understand yet is why `ssh.exe` for the remote schema does not work on my end, while `plink.exe` does, as they are both available from `$PATH`.

```
D:\repos\backup_manager\rdiff-backup-2.0.5\rdiff-backup.exe -v5 --force --exclude-symbolic-links --remote-schema "plink.exe -i D:\backup-key.ppk -batch %s /usr/local/bin/rdiff-backup --server" --include "/root/db_dumps**" --include "/etc/apache2**" --include "/var/www**"  --exclude "**" --print-statistics "root@1.2.3.4::/" "D:\Backups\product-test"
```

This is the command I'm using uccessfully now.
- `-batch` avoids you from having to press enter to open the session
- `-i` lets you specify a puttygen-generated private key.

**Comment by ericzolf** [comment]
Would you mind testing the build attached to: https://github.com/rdiff-backup/rdiff-backup/pull/498#issuecomment-749572698 - it should fix both issues at once. Please let me know the result!

**Comment by xastor** [comment]
The build you attached works for me!  I get a successful increment and no crash, great!!
