### ISSUE TITLE
[BUG] Invalid cross-device link on os.rename

### ISSUE THREAD

**Issue by ikus060** [rdiff-backup/rdiff-backup#519]
## Bug summary

While doing regular backup with rdiff-backup v1.2.8, the backup fail with 

```
OSError while renaming kalo/home/nagios/bin/rdiff-backup.tmp.33 to kalo/home/nagios/bin/check_debsecan
....
OSError: [Errno 18] Invalid cross-device link
```

## Version, Python, Operating System

rdiffbackup v1.2.8
Python 2.7.16
Debien Buster

## rdiff-backup call

With a very long argument list generated by minarca.
```
/usr/bin/rdiff-backup -v 9^C-remote-schema /usr/bin/ssh -oBatchMode=yes -oPreferredAuthentications=publickey -oUserKnownHostsFile='/etc/minarca/known_hosts' -oIdentitiesOnly=yes -i '/etc/minarca/id_rsa' ^C kalo --exclude-sockets --no-compression --include /root/.ssh --include /var/www --include /var/backups --include /home --include /etc --include /srv --exclude **/*~ --exclude /dev --exclude /proc --exclude /sys --exclude /tmp --exclude /run --exclude /mnt --exclude /media --exclude **/lost+found --exclude /* / minarca@www.minarca.net::kalo
```

## What happened and what did you expect?

```
Processing changed file home/nagios/bin/check_debsecan
Incrementing mirror file kalo/home/nagios/bin/check_debsecan
OSError while renaming kalo/home/nagios/bin/rdiff-backup.tmp.33 to kalo/home/nagios/bin/check_debsecan
Exception '[Errno 18] Invalid cross-device link' raised of class '<type 'exceptions.OSError'>':
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/robust.py", line 32, in check_common_error
    try: return function(*args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rpath.py", line 260, in rename
    rp_source.conn.os.rename(rp_source.path, rp_dest.path)
Sending back exception [Errno 18] Invalid cross-device link of type <type 'exceptions.OSError'>: 
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 335, in answer_request
    result = apply(eval(request.function_string), argument_list)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 243, in patch_and_increment
    ITR(diff.index, diff)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rorpiter.py", line 281, in __call__
    last_branch.fast_process(*args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 701, in fast_process
    rpath.rename, (tf, mirror_rp)) is None:
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/robust.py", line 32, in check_common_error
    try: return function(*args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rpath.py", line 260, in rename
    rp_source.conn.os.rename(rp_source.path, rp_dest.path)
Exception '[Errno 18] Invalid cross-device link' raised of class '<type 'exceptions.OSError'>':
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 343, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 51, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 450, in __call__
    return apply(self.connection.reval, (self.name,) + args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 370, in reval
    if isinstance(result, Exception): raise result
Using rdiff-backup version 1.2.8
Executing /usr/bin/ssh -oBatchMode=yes -oPreferredAuthentications=publickey -oUserKnownHostsFile='/etc/minarca/known_hosts' -oIdentitiesOnly=yes -i '/etc/minarca/id_rsa' minarca@www.minarca.net kalo
Unable to import win32security module. Windows ACLs
not supported by filesystem at /
escape_dos_devices not required by filesystem at /
Starting increment operation / to kalo
Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 30, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 343, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 51, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 450, in __call__
    return apply(self.connection.reval, (self.name,) + args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/connection.py", line 370, in reval
    if isinstance(result, Exception): raise result
OSError: [Errno 18] Invalid cross-device link
Fatal Error: Lost connection to the remote system
```

## More information

I can reproduce this error directly on the remove host using.
```
python2
Python 2.7.13 (default, Aug 22 2020, 10:03:02) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.rename('kalo/home/nagios/bin/rdiff-backup.tmp.33', 'kalo/home/nagios/bin/check_debsecan')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 18] Invalid cross-device link
```
I'm not sure what is special with this file and why the OS complain like this on a simple rename. 
Only special fact, `kalo/home/nagios/bin/rdiff-backup.tmp.33` is a symlink to `/usr/lib/nagios/plugins/check_debsecan`

I've compare our rename operation with `mv` commandline. `mv` is handling that just fine like this:
```
rename("kalo/home/nagios/bin/rdiff-backup.tmp.33", "kalo/home/nagios/bin/check_debsecan") = -1 EXDEV (Invalid cross-device link)
unlink("kalo/home/nagios/bin/check_debsecan") = -1 ENOENT (No such file or directory)
readlink("kalo/home/nagios/bin/rdiff-backup.tmp.33", "/usr/lib/nagios/plugins/check_de"..., 39) = 38
symlink("/usr/lib/nagios/plugins/check_debsecan", "kalo/home/nagios/bin/check_debsecan") = 0
lchown("kalo/home/nagios/bin/check_debsecan", 110, 10003) = 0
utimensat(AT_FDCWD, "kalo/home/nagios/bin/check_debsecan", [{tv_sec=1611938796, tv_nsec=509850880}, {tv_sec=1611938796, tv_nsec=509850880}], AT_SYMLINK_NOFOLLOW) = 0
llistxattr("kalo/home/nagios/bin/rdiff-backup.tmp.33", NULL, 0) = 0
llistxattr("kalo/home/nagios/bin/rdiff-backup.tmp.33", 0x7ffc56433440, 0) = 0
lstat("/", {st_mode=S_IFDIR|0755, st_size=23, ...}) = 0
newfstatat(AT_FDCWD, "kalo/home/nagios/bin/rdiff-backup.tmp.33", {st_mode=S_IFLNK|0777, st_size=38, ...}, AT_SYMLINK_NOFOLLOW) = 0
unlinkat(AT_FDCWD, "kalo/home/nagios/bin/rdiff-backup.tmp.33", 0) = 0
```

Looking at the code, we need to handle this specific type of exception in a similar way.

@ericzolf Your input on this subject would be appreciated. I will gladly work on a patch for this.

**Comment by ericzolf** [comment]
I'm missing the initial situation in your description. Can it be that `/usr/lib/nagios/bin/check_debsecan` is an _absolute_ soft link to `/usr/lib/nagios/plugins/check_debsecan` and you are doing a back-up from `/usr/lib/nagios` to `kalo/home/nagios`?

I'm asking because it might not be the rename the issue, but a step before and the way we arrive to the rename necessity.

**Comment by ericzolf** [comment]
I can't reproduce this error unless I cross some file system border in my rename. Could it be that an "exotic" file system is involved? Anyway, os.rename should not fail as long as the file remains in the same folder, because it must be the same file system (unless it's very exotic, e.g. one which doesn't properly support renaming of soft links pointing to a file outside of the current file system and/or pointing to a non-existing file).

This said, you could try to use `shutil.move` instead of `os.rename`, but the function apparently falls back to `os.rename` if it thinks it's safe to do so, which sounds like your case. I just realize that the code of `mv` doesn't even copy&delete the soft-link, it completely re-creates it before it removes it. That's rather crazy!

Buut, `shutil.move` might do it right for you; from the help it does the same thing (but will it properly recognize the need to re-create instead of renaming?):

> If the destination is on our current filesystem, then rename() is used. Otherwise, src is copied to the destination and then removed. Symlinks are recreated under the new name if os.rename() fails because of cross filesystem renames.

Let me know, though I still suspect something strange with your file system...

**Comment by ikus060** [comment]
I've made more test to narrow down the culprit. It seams related to ZFS and project quota.
I made a backup to the same system, on the same ZFS dataset. The only different is the project quota. I've enabled for some folder.

Soon as I enable project quota on the folder. The backup fail.
```
rdiff-backup -v 5 /home/nagios/ minarca@veras.ikus-soft.com::/backups/test
WORKING
...
lsattr -p test
chattr -p 3 test
...
rdiff-backup -v 5 /home/nagios/ minarca@veras.ikus-soft.com::/backups/test
FAIL
```

**Comment by ikus060** [comment]
`shutil.move` is not working. The symbolic link get lost...

**Comment by ikus060** [comment]
Something like this seams to get it fixed.
```
                        try:
                            rp_source.conn.os.rename(rp_source.path, rp_dest.path)
                        except OSError, error:
                                if error.errno == errno.EXDEV:
                                  # On Linux with ZFS and quota project, errno.EXDEV Invalid cross-device link get raised
                                  copy(rp_source, rp_dest)
                                  rp_source.delete()
                                # XXX errno.EINVAL and len(rp_dest.path) >= 260 indicates
                                # pathname too long on Windows
                                elif error.errno != errno.EEXIST:
                                  # On Windows, files can't be renamed on top of an existing file
                                  rp_source.conn.os.chmod(rp_dest.path, 0o700)
                                  rp_source.conn.os.unlink(rp_dest.path)
                                  rp_source.conn.os.rename(rp_source.path, rp_dest.path)
                                else:
                                    log.Log("OSError while renaming %s to %s"
                                                        % (rp_source.path, rp_dest.path), 1)
                                    raise
```

I've choose to call `copy()` since I'm not sure what I'm dealing with at this point. I would not expect anything then a symbolic link, but you never know. @ericzolf  What do you think of this change ?

**Comment by ericzolf** [comment]
In case it was not obvious, I added my comments directly to the commit https://github.com/rdiff-backup/rdiff-backup/commit/bd96d4fcd42ae0947a955802d1cd498140425ea6

Another thought is that you might want to ask if someone knows what's happening with ZFS and quotas, I don't like having a fix for something I don't fully understand, that's often calling for trouble later on (not that I didn't do it in the past, but just as a general direction).

**Comment by ikus060** [comment]
I'm raise a bug in ZFS project. https://github.com/openzfs/zfs/issues/11570

**Comment by ericzolf** [comment]
Commented, looks almost good to me.
