### ISSUE TITLE
[BUG] --tempdir causes crash on Windows

### ISSUE THREAD

**Issue by rstarkov** [rdiff-backup/rdiff-backup#540]
## Bug summary

On Windows, using `--tempdir` results in a crash due to `Exception 'Can't mix strings and bytes in path components'`.

In my case this occurred when a `--check-destination-dir` command needed to do some cleanup.

This crash goes away if I change `tempfile.tempdir = os.fsencode(arglist.tempdir)` to `tempfile.tempdir = arglist.tempdir` in Main.py but I don't know if that's a good fix.

## Version, Python, Operating System

Call `rdiff-backup info` (version >= 2.1) or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```
Using rdiff-backup version 2.0.5
      with cpython I:\Backups\OVH\RdiffBackups\rdiff-backup.exe version 3.7.7
      on Windows-10-10.0.18362, fs encoding utf-8
```

## rdiff-backup call

```
rdiff-backup.exe --force -v5 --tempdir C:/My/Temp/ --check-destination-dir C:/My/Path/
```

## What happened and what did you expect?

```
Exception 'Can't mix strings and bytes in path components' raised of class '<class 'TypeError'>':
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\restore.py", line 534, in get_fp
  File "tempfile.py", line 547, in NamedTemporaryFile
  File "tempfile.py", line 256, in _mkstemp_inner
  File "ntpath.py", line 115, in join
  File "genericpath.py", line 155, in _check_arg_types

Exception 'Can't mix strings and bytes in path components' raised of class '<class 'TypeError'>':
  File "rdiff_backup\Main.py", line 395, in error_check_Main
  File "rdiff_backup\Main.py", line 417, in Main
  File "rdiff_backup\Main.py", line 357, in take_action
  File "rdiff_backup\Main.py", line 1075, in CheckDest
  File "rdiff_backup\regress.py", line 71, in Regress
  File "rdiff_backup\rorpiter.py", line 313, in __call__
  File "rdiff_backup\regress.py", line 295, in fast_process
  File "rdiff_backup\regress.py", line 319, in restore_orig_regfile
  File "rdiff_backup\restore.py", line 558, in get_restore_fp
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\restore.py", line 534, in get_fp
  File "tempfile.py", line 547, in NamedTemporaryFile
  File "tempfile.py", line 256, in _mkstemp_inner
  File "ntpath.py", line 115, in join
  File "genericpath.py", line 155, in _check_arg_types

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 395, in error_check_Main
  File "rdiff_backup\Main.py", line 417, in Main
  File "rdiff_backup\Main.py", line 357, in take_action
  File "rdiff_backup\Main.py", line 1075, in CheckDest
  File "rdiff_backup\regress.py", line 71, in Regress
  File "rdiff_backup\rorpiter.py", line 313, in __call__
  File "rdiff_backup\regress.py", line 295, in fast_process
  File "rdiff_backup\regress.py", line 319, in restore_orig_regfile
  File "rdiff_backup\restore.py", line 558, in get_restore_fp
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\restore.py", line 534, in get_fp
  File "tempfile.py", line 547, in NamedTemporaryFile
  File "tempfile.py", line 256, in _mkstemp_inner
  File "ntpath.py", line 115, in join
  File "genericpath.py", line 155, in _check_arg_types
TypeError: Can't mix strings and bytes in path components
[23420] Failed to execute script rdiff-backup
```

**Comment by ericzolf** [comment]
No, it's not a good idea because we want to have consistently paths as bytes (long story, we have a lot of discussions about this topic). Python has improved path as bytes in 3.8 resp. 3.9 and the error looks like a limitation in the standard tempfile library. Would you mind trying again with Python 3.9 which is the new standard version?

**Comment by ericzolf** [comment]
I'm slightly confused because I can't reproduce the issue with the official v2.0.5 version of rdiff-backup, which is built with Python 3.7, so I'm not sure what's happening...

**Comment by ericzolf** [comment]
I realise that the error message refers to a function `tempfile.NamedTemporaryFile` which is _not_ used in the original code. Have you done changes to the code? If this is the case, it would have been nice to tell so, so that I don't lose time trying to reproduce the issue.

**Comment by rstarkov** [comment]
I don't know why python does this, but the stack trace is kind of messed up. Try it:

    import tempfile, os
    tempfile.tempdir = os.fsencode('foobar')
    tempfile.TemporaryFile()

Using latest python 3.9:

    P:\rdiff-backup>python test.py
    Traceback (most recent call last):
      File "P:\rdiff-backup\test.py", line 4, in <module>
        tempfile.TemporaryFile()
      File "C:\Apps\Python39\lib\tempfile.py", line 541, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "C:\Apps\Python39\lib\tempfile.py", line 248, in _mkstemp_inner
        file = _os.path.join(dir, pre + name + suf)
      File "C:\Apps\Python39\lib\ntpath.py", line 117, in join
        genericpath._check_arg_types('join', path, *paths)
      File "C:\Apps\Python39\lib\genericpath.py", line 155, in _check_arg_types
        raise TypeError("Can't mix strings and bytes in path components") from None
    TypeError: Can't mix strings and bytes in path components

Observe the NamedTemporaryFile in the stack trace instead of the actual function called. Sorry but looks like it's python's fault.

P.S. I can't reproduce the issue either right now. The directory got into this state by aborting a sync, and nothing would fix it short of cloning and modifying the code. If I get into this state again I will be sure to update this issue.

**Comment by ericzolf** [comment]
OK, thanks for the explanation, I can even reproduce the issue under Linux: TemporaryFile works, NamedTemporaryFile doesn't:

```python
$ python
Python 3.9.1 (default, Jan 20 2021, 00:00:00) 
[GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> tempfile.tempdir = os.fsencode('/tmp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'os' is not defined
>>> import os
>>> tempfile.tempdir = os.fsencode('/tmp')
>>> tempfile.TemporaryFile()
<_io.BufferedRandom name=4>
>>> tempfile.NamedTemporaryFile()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.9/tempfile.py", line 541, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib64/python3.9/tempfile.py", line 248, in _mkstemp_inner
    file = _os.path.join(dir, pre + name + suf)
  File "/usr/lib64/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.9/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```
I already had [an issue with tempdir regarding bytes](https://bugs.python.org/issue40701) but this is a new one.

Last but not least, yes, you can do so to reproduce the issue. One other option is to create a file `rdiff-backup-data/current_mirror.{datetime}.data` with "{datetime}" being the date and time of the _previous_ backup (not the last one, which already has a current_mirror). This said, with this method, I wasn't able to reproduce your issue.

**Comment by ericzolf** [comment]
Looking again at [my PR](https://github.com/python/cpython/pull/20442), I am the opinion that it would also fix your problem.

**Comment by ericzolf** [comment]
OK, looking into the rdiff-backup code, the solution can indeed be to:

1. remove the os.fsencode in `src/rdiff_backup/Main.py:234:            tempfile.tempdir = os.fsencode(arg)`
2. add an `os.fsencode` to the following lines:

```
src/rdiff_backup/Security.py:110:            rdir = tempfile.gettempdir()
src/rdiff_backup/Security.py:121:            rdir = tempfile.gettempdir()
src/rdiff_backup/Security.py:137:            rdir = tempfile.gettempdir()
src/rdiff_backup/Security.py:152:        rdir = tempfile.gettempdir()
```
I'm not sure I want to do this in the main code line, but that should solve your issue at least... Let me think about it.

**Comment by gpshead** [comment]
FWIW from a CPython standard library perspective, your code will be better off not assigning a bytes value to `tempfile.tempdir`.  So step 1 of your solution sounds good to me.

I can't offer a _practical_ input on what type you should be treating paths as internally everywhere.  bytes seems surprising me, i'd hope surrogateescape'd str values as `os.fsdecode()` returns would be enough? Consider looking at what the [Mercurial](https://www.mercurial-scm.org/) project and [Tahoe-LAFS](https://github.com/tahoe-lafs/tahoe-lafs) project have learned in that regard. They're both Python based and need to deal with all possible path names existing on real world mojibake-or-worse filled filesystems. IIRC Tahoe-LAFS was an early Python 3 porter that ran into many bumps along the way that in large part led to us making sure bytes APIs as well as a round-trippable fsencode/fsdecode story existed in the PY3 stdlib.

**Comment by ericzolf** [comment]
One of [our testfiles](https://github.com/rdiff-backup/rdiff-backup-filesrepo) didn't go through the surrogate-escape decoding (under `various_file_types` in the archive). I started the migration from Python 2 to 3 as you said, by using strings instead of bytes, but I got quickly the requirement from our users to support even "broken" filenames. The round-trippable ability between Windows and Linux was also a requirement, as well as the compatibility of old backup repos.

I'm not saying that I absolutely took the right decision, but I didn't take it without reasons.

Personally, I find it a bit irritating to read that bytes are the native form of paths under Linux, and at the same read and experience by using the libraries that bytes are 2nd class citizen. cf. https://docs.python.org/3/library/os.path.html

> Unfortunately, some file names may not be representable as strings on Unix, so applications that need to support arbitrary file names on Unix should use bytes objects to represent path names. Vice versa, using bytes objects cannot represent all file names on Windows (in the standard mbcs encoding), hence Windows applications should use string objects to access all files.

(I strongly assumed that the Windows statement is bollocks, anything can be represented as bytes! Hence also my decision)

Anyway, I'd personally like to have the Path object extended in such a way that it doesn't really matter, it'll be round-trippable and OS-agnostic, but I'm not sure this is really possible.

**Comment by gpshead** [comment]
https://bugs.python.org/issue43403 filed to address that odd claim in the docs.

As for Path objects... I wouldn't rule that out as infeasible. It sounds like a good idea. Someone would need to describe the desired behavior in a bugs.python.org issue and drive an implementation and tests.

pathlib is still fairly new to Python, a lot of parts of the standard library still do not yet support Path objects.

**Comment by ericzolf** [comment]
Sorry @gpshead I was slightly faster than you to create https://bugs.python.org/issue43395 but Eryk noticed, so we're back to normal.
