### ISSUE TITLE
Create a PPA for Ubuntu testing

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#55]
We should have a PPA on Launchpad for rdiff-backup so it would be easy for people to test the latest version.

I am assigning this myself, the issue is just a reminder.

I have contacted the Launchpad user @hstock to grant me access to https://launchpad.net/rdiff-backup so I can publish there an official PPA (instead of just using https://launchpad.net/~otto/+archive/ubuntu/ppa/+builds?build_text=&build_state=all)

**Comment by ottok** [comment]
Sent a reminder to @hstock about this.

We are also waiting for Ubuntu to sync [librsync](https://launchpad.net/ubuntu/+source/librsync) v2 to Eoan. For that I have contacted @rbalint.

**Comment by ottok** [comment]
Seems Travis-CI has Launchpad integration, se we could automatically push to a PPA on each master branch build in the future: https://docs.travis-ci.com/user/deployment/launchpad/

**Comment by rbalint** [comment]
@ottok librsync 2 is in eoan-proposed, being on time to be released in Eoan. rdiff-backup can migrate to release pocket, after the duplicity FTBFS on ppc64el is fixed https://people.canonical.com/~ubuntu-archive/proposed-migration/eoan/update_excuses.html#duplicity .

**Comment by ottok** [comment]
Ack. Duplicity seems to be a slight mess, has a [huge delta](https://patches.ubuntu.com/d/duplicity/duplicity_0.7.18.2-1ubuntu3.1.patch) between Ubuntu and Debian so I will personally not get involved in Duplicity packaging ATM.

**Comment by ikus060** [comment]
Personnaly, I'm not a big fan of ppa

We should focus on delivering rdiff-backup on less channel but do it
properly. Since the projet is a python project, a good place to start is
pypi. For Debian, Ubuntu, RedHat, OSx, Windows, etc. question is do we have
the man power to do it now ? Again, I would focus on delivering a stable
and working rdiff-backup version on a single channel.

--
Patrik Dufresne Service Logiciel inc.
http://www.patrikdufresne.com <http://patrikdufresne.com/>/
514-971-6442
130 rue Doris
St-Colomban, QC J5K 1T9

**Comment by ottok** [comment]
@ikus060: 

We should focus on delivering a rdiff-backup that is well tested. A PPA that offers the nightly build in an easy to install format will increase the number of people who contribute to testing.

The PyPi releases are also in the works. Do you want to participate in setting up the PyPi? I am not that terribly familiar with PyPi. For example I am not aware of any way to publish nightly development versions on PyPi. If you know the PyPi process well, you should maybe take care of  #58 ? :)

**Comment by ikus060** [comment]
@Otto Kekäläinen <otto@seravo.com>

I could take care of publishing to Pypi. No issue here. I've done this
recently for another project with C++ extensions. But I will be waiting for
Travis CI to pass first. Cause here I still can't make it work.

--
Patrik Dufresne

**Comment by ottok** [comment]
[librsync v2](https://tracker.debian.org/pkg/librsync) migrated to Ubuntu yesterday. This means that I can now proceed to setting up an automatic PPA integration and hopefully attract some new testers to our project.

**Comment by ottok** [comment]
You can test this now at:
```
sudo add-apt-repository ppa:rdiff-backup/rdiff-backup-development
sudo apt-get update
```

Based on work in #224 and recipe at https://code.launchpad.net/~rdiff-backup/+recipe/rdiff-backup-daily

**Comment by ottok** [comment]
The PPA references the master branch now and everything seems to be working and running as it should.

I've also updated the metadata for https://launchpad.net/rdiff-backup, so all on Launchpad is now in order.

**Comment by rbalint** [comment]
@ottok Thanks!

**Comment by ottok** [comment]
Reopening since the automation did not eventually work as intended.
Current status: https://code.launchpad.net/~rdiff-backup/+recipe/rdiff-backup-git-master

Will work on this later. The #265 needs to merged first.

**Comment by ottok** [comment]
New version drafted in #265. To finalize it I need to figure out how Travis-CI could safely be allowed to commit and force push on branch 'ubuntu-ppa'. Or figure out some other approach on how to deliver the sources with an custom made temporary debian/changelog for Launchpad to build.

**Comment by ottok** [comment]
Builds work fine when initialized manually:
![image](https://user-images.githubusercontent.com/668724/75099012-7058af80-55c5-11ea-87d9-1634d500a11a.png)

**Comment by ikus060** [comment]
@ottok 
Regarding this point, is this PPA compatible with Debian ? or only Ubuntu ?
Cause I tried to make it work on "debian:buster".
```
docker run -it --rm debian:buster
apt update && apt install software-properties-common gpg
add-apt-repository ppa:rdiff-backup/rdiff-backup-development
```
I get this
```
 Built from git master at https://github.com/rdiff-backup/rdiff-backup/
 More info: https://launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-development
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpwh8a5dr8/pubring.gpg' created
gpg: /tmp/tmpwh8a5dr8/trustdb.gpg: trustdb created
gpg: key C9D4B7CF393BF0C5: public key "Launchpad PPA for Rdiff-backup maintainers" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.7/shutil.py", line 491, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.7/shutil.py", line 449, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.7/shutil.py", line 447, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.ssh'
```
Usually, I'm not running into trouble to add a PPA to debian... Need some help.

**Comment by ottok** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.ssh'

I have not seen this error before, I don't know what it is.

In general, the compatibility of PPAs are guaranteed only for the
Ubuntu release they target. Debian versions can be compatible with
some luck.  Debian Buster was released on July 2019, so it is pretty
close to Ubuntu 19.04 or 19.10.

Currently Ubuntu Focal is identical to Debian unstable.

**Comment by ericzolf** [comment]
Is this issue still current or can we close it?

**Comment by ottok** [comment]
The goal of this issue has not yet been achieved and it would be useful, so
don't close the issue.

**Comment by ericzolf** [comment]
@ottok were the recent changes what you expected to do for this issue?

**Comment by ottok** [comment]
For the record - this is still not automated, but I did run it manually so https://code.launchpad.net/~rdiff-backup/rdiff-backup/+git/trunk saw new code, and builds at https://launchpad.net/~rdiff-backup/+archive/ubuntu/rdiff-backup-development/+builds?build_text=&build_state=all passed and new binaries published at https://code.launchpad.net/~rdiff-backup/+recipe/rdiff-backup-git-master.
