### ISSUE TITLE
[BUG] My 2.1.0a1 client can't talk to 2.1.0a1 server (Win10)

### ISSUE THREAD

**Issue by rstarkov** [rdiff-backup/rdiff-backup#565]
## Bug summary

Trying out 2.1.0a1 and I can't get it to work if I upgrade both ends. But 2.1.0a1 client is able to talk to a 2.0.5 server.

## Version, Python, Operating System

```yaml
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - C:\Path\To\rdiff-backup.exe
  - info
  version: 2.1.0a1
python:
  executable: C:\Path\To\rdiff-backup.exe
  name: cpython
  version: 3.9.1
system:
  fs_encoding: utf-8
  platform: Windows-10-10.0.18362-SP0
```

## rdiff-backup call

This fails (error message below):
```
rdiff-backup-21.exe --remote-schema "C:\Path\To\plink.exe %s -P 1234 -l Roman -C C:\Remote\Path\rdiff-backup-21.exe server" backup "11.22.33.44::C:/Remote/MyData" "C:/Local/MyData"
```

This works using 2.0.5 on server:
```
rdiff-backup-21.exe --remote-schema "C:\Path\To\plink.exe %s -P 1234 -l Roman -C C:\Remote\Path\rdiff-backup-20.exe --server" backup "11.22.33.44::C:/Remote/MyData" "C:/Local/MyData"
```

## What happened and what did you expect?

Log with -v9:

```Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 38, in main_run_and_exit
  File "rdiff_backup\Main.py", line 77, in _main_run
  File "rdiffbackup\actions\backup.py", line 59, in connect
  File "rdiffbackup\actions\__init__.py", line 435, in connect
  File "rdiff_backup\SetConnections.py", line 100, in get_connected_rpath
  File "rdiff_backup\SetConnections.py", line 295, in _init_connection
  File "rdiff_backup\SetConnections.py", line 312, in _validate_connection_version
  File "rdiff_backup\connection.py", line 531, in __call__
  File "rdiff_backup\connection.py", line 408, in reval
TypeError: argument of type 'NoneType' is not iterable
[37420] Failed to execute script rdiff-backup
2021-04-15 22:45:14.834015 +0100  <CLIENT-37420>  Executing C:\Path\To\plink.exe 11.22.33.44 -P 1234 -l Roman -C C:\Remote\Path\rdiff-backup-21.exe server
2021-04-15 22:45:14.834988 +0100  <CLIENT-37420>  Client sending (0): ConnectionRequest: Globals.get with 1 arguments
2021-04-15 22:45:14.834988 +0100  <CLIENT-37420>  Client sending (0): version
2021-04-15 22:45:16.478926 +0100  <CLIENT-37420>  Client received (0): argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 38, in main_run_and_exit
  File "rdiff_backup\Main.py", line 95, in _main_run
  File "rdiffbackup\actions\server.py", line 39, in run
  File "rdiff_backup\connection.py", line 389, in Server
  File "rdiff_backup\connection.py", line 435, in _get_response
  File "rdiff_backup\connection.py", line 291, in _get
rdiff_backup.connection.ConnectionReadError: Truncated header string (problem probably originated remotely)
[3028] Failed to execute script rdiff-backup
```

**Comment by ericzolf** [comment]
That's more than interesting. Calling:

```
rdiff-backup -v9 --remote-schema "ssh %s -C c:\Users\vagrant\rdiff-backup-2.1.0a1-64\rdiff-backup.exe server" backup localhost::C:\Users\vagrant\Desktop \temp\bak12
```

fails like you, but calling the same command with `--server` succeeds. So it must be a small glitch somewhere, I'll look into it, but at least there is a simple workaround.
