### ISSUE TITLE
rdiff-backup-statistics assertion

### ISSUE THREAD

**Issue by lostboy7** [rdiff-backup/rdiff-backup#650]
Rdiff-backup-statistics crashes with an assertion when run on a particular backup.

Can re-produce on demand but not sure what details the team would like to see about the specific backup repo.

Example output for backup stored in "backups/array1":

[root@rdiff-backup storage]# rdiff-backup-statistics backups/array1
Traceback (most recent call last):
  File "/usr/bin/rdiff-backup-statistics", line 566, in <module>
    error_check_Main()
  File "/usr/bin/rdiff-backup-statistics", line 553, in error_check_Main
    Main()
  File "/usr/bin/rdiff-backup-statistics", line 535, in Main
    set_chars_to_quote()
  File "/usr/bin/rdiff-backup-statistics", line 520, in set_chars_to_quote
    FilenameMapping.set_init_quote_vals()
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/FilenameMapping.py", line 62, in set_init_quote_vals
    conn.FilenameMapping.set_init_quote_vals_local()
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/FilenameMapping.py", line 73, in set_init_quote_vals_local
    init_quoting_regexps()
  File "/usr/lib64/python3.6/site-packages/rdiff_backup/FilenameMapping.py", line 80, in init_quoting_regexps
    "Chars to quote are wrong: '%s'." % _safe_str(chars_to_quote)
AssertionError: Chars to quote are wrong: '-"*/:<>?\\|;'.

**Comment by ericzolf** [comment]
Sorry for the delay,  holiday came in-between. What does `ls -la backups/array1` show? Did you move the backup or manipulate it somehow? And how does the original directory look like, does it also contain this file with a strange name?

**Comment by ericzolf** [comment]
Sorry, I misinterpreted the error I think. Additional questions: can you attach the file `backups/array1/chars_to_quote`? And what was the command with which you created this repo?

**Comment by ericzolf** [comment]
No answer, closing.
