### ISSUE TITLE
[BUG] Exception AttributeError: type object 'ErrorLog' has no attribute 'write'

### ISSUE THREAD

**Issue by desseim** [rdiff-backup/rdiff-backup#686]
## Bug summary

An exception occurs in `log.py` trying to log an error on Windows with version `2.1.1a0`.
This doesn't happen with version `2.1.0.a1` and seems like a refactoring artifact.

## Version, Python, Operating System

```yaml
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - C:\Program Files\rdiff-backup-2.1.1a0-64\rdiff-backup.exe
  - info
  parsed: null
  version: 2.1.1a0
python:
  executable: C:\Program Files\rdiff-backup-2.1.1a0-64\rdiff-backup.exe
  name: cpython
  version: 3.9.1
system:
  fs_encoding: utf-8
  platform: Windows-10-10.0.19041-SP0
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
> rdiff-backup.exe backup --exclude-symbolic-links --no-acls 'C:/' 'D:/Backup'
```

## What happened and what did you expect?

This is the output from the above command, the `AttributeError` seems quite explicit:

```
WARNING: ListError: 'C:/$Recycle.Bin/S-0-0-00' [WinError 5] Access is denied: b'C:/$Recycle.Bin/S-1-5-18'
WARNING: ListError: 'C:/$Recycle.Bin/S-0-0-00-0000000000-0000000000-0000000000-1000' [WinError 5] Access is denied: b'C:/$Recycle.Bin/S-0-0-00-0000000000-0000000000-0000000000-1000'
WARNING: ListError: 'C:/$Recycle.Bin/S-0-0-00-0000000000-0000000000-0000000000-1001' [WinError 5] Access is denied: b'C:/$Recycle.Bin/S-0-0-00-0000000000-0000000000-0000000000-1001'
Traceback (most recent call last):
  File "rdiff_backup\rorpiter.py", line 351, in Collate2Iters
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rdiff_backup\robust.py", line 94, in check_common_error
  File "rdiff_backup\rpath.py", line 804, in listdir
PermissionError: [WinError 5] Access is denied: b'C:/$Recycle.Bin/S-0-0-00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 37, in main_run_and_exit
  File "rdiff_backup\Main.py", line 103, in _main_run
  File "rdiffbackup\actions\backup.py", line 161, in run
  File "rdiff_backup\backup.py", line 39, in mirror_compat200
  File "rdiff_backup\backup.py", line 196, in patch
  File "rdiff_backup\rorpiter.py", line 393, in FillInIter
  File "rdiff_backup\backup.py", line 116, in get_diffs
  File "rdiff_backup\backup.py", line 172, in get_sigs
  File "rdiff_backup\backup.py", line 363, in __next__
  File "rdiff_backup\rorpiter.py", line 355, in Collate2Iters
  File "rdiff_backup\rorpiter.py", line 251, in __next__
  File "rdiff_backup\selection.py", line 243, in _Iterate_fast
  File "rdiff_backup\selection.py", line 225, in diryield
  File "rdiff_backup\selection.py", line 279, in _listdir_sorted
  File "rdiff_backup\robust.py", line 102, in check_common_error
  File "rdiff_backup\selection.py", line 276, in error_handler
  File "rdiff_backup\log.py", line 352, in write_if_open
AttributeError: type object 'ErrorLog' has no attribute 'write'
[7356] Failed to execute script 'rdiff-backup' due to unhandled exception!
NOTE: Symbolic links excluded by default on Windows
NOTE: Starting mirror from source path C:/ to destination path D:/Backup
```

Running the same command with version `2.1.0a1`, the same `ListError`s occur but they don't interrupt the process.

**Comment by ericzolf** [comment]
Thanks for the report. I can reproduce it also under Linux:

```
mkdir /tmp/from
date > /tmp/from/a
date > /tmp/from/b
sudo chown root.root /tmp/from/a
sudo chmod go-rwx /tmp/from/a
PYTHONPATH=$PWD/build/lib.linux-x86_64-3.10 PATH=$PWD/build/scripts-3.10:$PATH \
    python build/scripts-3.10/rdiff-backup backup /tmp/from /tmp/bak
```
