### ISSUE TITLE
[BUG] EOFError: Compressed file ended before the end-of-stream marker was reached when running --check-destination-dir

### ISSUE THREAD

**Issue by pronego-mls** [rdiff-backup/rdiff-backup#699]
## Bug summary

An unexpected error is thrown when verifying a repository to which the last backup has failed.
The backup is stored on a partition with NTFS file system.

## Version, Python, Operating System

The OS is Debian 11.3.

```yaml
# rdiff-backup -v9
2022-04-27 07:53:55.288010 +0200  <CLIENT-10525>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.
2022-04-27 07:53:55.277944 +0200  <CLIENT-10525>  Using rdiff-backup version 2.0.5
2022-04-27 07:53:55.278293 +0200  <CLIENT-10525>        with cpython /usr/bin/python3 version 3.9.2
2022-04-27 07:53:55.287670 +0200  <CLIENT-10525>        on Linux-5.10.0-13-686-pae-i686-with-glibc2.31, fs encoding utf-8

```

## rdiff-backup call

```
rdiff-backup --check-destination-dir /backup/rdiff
```

## What happened and what did you expect?

I expected the command to verify and hopefully fix the backup directory such that I can access and restore the latest valid backup (because my hard disk failed).

Restoring results in:
```
# rdiff-backup --force --restore-as-of 2022-04-22 /backup/rdiff/ /data/
Fatal Error: Previous backup to /backup/rdiff seems to have failed.
Rerun rdiff-backup with --check-destination-dir option to revert directory to state before unsuccessful session.
```

Running 'check-destination-dir' as suggested leads me to a dead end with the following final error:
```
Warning: Access Control List file not found
Exception 'Compressed file ended before the end-of-stream marker was reached' raised of class '<class 'EOFError'>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/robust.py", line 35, in check_common_error
    return function(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 528, in get_fp
    current_fp = self.get_first_fp()
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 570, in get_first_fp
    rpath.copyfileobj(fp, current_fp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 79, in copyfileobj
    inbuf = inputfp.read(blocksize)
  File "/usr/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "

Exception 'Compressed file ended before the end-of-stream marker was reached' raised of class '<class 'EOFError'>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 417, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 357, in take_action
    CheckDest(rps[0])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 1075, in CheckDest
    dest_rp.conn.regress.Regress(dest_rp) 
  File "/usr/lib/python3/dist-packages/rdiff_backup/regress.py", line 71, in Regress
    ITR(rf.index, rf)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 313, in __call__
    last_branch.fast_process(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/regress.py", line 295, in fast_process
    self.restore_orig_regfile(rf)
  File "/usr/lib/python3/dist-packages/rdiff_backup/regress.py", line 319, in restore_orig_regfile
    tf.write_from_fileobj(rf.get_restore_fp())
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 558, in get_restore_fp
    return robust.check_common_error(error_handler, get_fp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/robust.py", line 35, in check_common_error
    return function(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 528, in get_fp
    current_fp = self.get_first_fp()
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 570, in get_first_fp
    rpath.copyfileobj(fp, current_fp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 79, in copyfileobj
    inbuf = inputfp.read(blocksize)
  File "/usr/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 417, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 357, in take_action
    CheckDest(rps[0])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 1075, in CheckDest
    dest_rp.conn.regress.Regress(dest_rp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/regress.py", line 71, in Regress
    ITR(rf.index, rf)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 313, in __call__
    last_branch.fast_process(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/regress.py", line 295, in fast_process
    self.restore_orig_regfile(rf)
  File "/usr/lib/python3/dist-packages/rdiff_backup/regress.py", line 319, in restore_orig_regfile
    tf.write_from_fileobj(rf.get_restore_fp())
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 558, in get_restore_fp
    return robust.check_common_error(error_handler, get_fp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/robust.py", line 35, in check_common_error
    return function(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 528, in get_fp
    current_fp = self.get_first_fp()
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 570, in get_first_fp
    rpath.copyfileobj(fp, current_fp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 79, in copyfileobj
    inbuf = inputfp.read(blocksize)
  File "/usr/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

## More information

Any help appreciated.

```
# rdiff-backup -v9 --check-destination-dir /backup/rdiff
2022-04-27 07:59:23.995057 +0200  <CLIENT-10658>  Using rdiff-backup version 2.0.5
2022-04-27 07:59:23.995367 +0200  <CLIENT-10658>        with cpython /usr/bin/python3 version 3.9.2
2022-04-27 07:59:24.004424 +0200  <CLIENT-10658>        on Linux-5.10.0-13-686-pae-i686-with-glibc2.31, fs encoding utf-8
2022-04-27 07:59:25.241826 +0200  <CLIENT-10658>  Using mirror root directory /backup/rdiff
2022-04-27 07:59:25.244294 +0200  <CLIENT-10658>  Making directory /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1
2022-04-27 07:59:26.487205 +0200  <CLIENT-10658>  Touching /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/5-_ a.snapshot.gz
2022-04-27 07:59:27.487811 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/5-_ a.snapshot.gz
2022-04-27 07:59:27.489538 +0200  <CLIENT-10658>  Touching /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/uniá

2022-04-27 07:59:28.593035 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/uniá

2022-04-27 07:59:28.594274 +0200  <CLIENT-10658>  Touching /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/:\"
2022-04-27 07:59:29.432423 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/:\"
2022-04-27 07:59:29.433626 +0200  <CLIENT-10658>  Touching /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/A
2022-04-27 07:59:30.845601 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/A
2022-04-27 07:59:30.846848 +0200  <CLIENT-10658>  Touching /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/foo
2022-04-27 07:59:31.899510 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/foo
2022-04-27 07:59:31.901046 +0200  <CLIENT-10658>  Making directory /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/hl
2022-04-27 07:59:32.912964 +0200  <CLIENT-10658>  Touching /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/hardlinked_file1
2022-04-27 07:59:33.803832 +0200  <CLIENT-10658>  Hard linking /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/hl/hardlinked_file2 to /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/hardlinked_file1
2022-04-27 07:59:35.124232 +0200  <CLIENT-10658>  Unable to import win32security module. Windows ACLs
not supported by filesystem at /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1
2022-04-27 07:59:35.124852 +0200  <CLIENT-10658>  Touching /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/dir_inc_check
2022-04-27 07:59:36.187470 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/dir_inc_check
2022-04-27 07:59:36.188771 +0200  <CLIENT-10658>  Touching /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/regfile
2022-04-27 07:59:37.254795 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/regfile
2022-04-27 07:59:37.257519 +0200  <CLIENT-10658>  Touching /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/high_perms_file
2022-04-27 07:59:38.227200 +0200  <CLIENT-10658>  Touching /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/high_perms_dir
2022-04-27 07:59:39.118953 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/high_perms_file
2022-04-27 07:59:39.119957 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/high_perms_dir
2022-04-27 07:59:39.121233 +0200  <CLIENT-10658>  Touching /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/symlinked_file1
2022-04-27 07:59:41.238642 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/symlinked_file2
2022-04-27 07:59:41.239684 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/symlinked_file1
2022-04-27 07:59:41.241698 +0200  <CLIENT-10658>  Touching /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/foo
2022-04-27 07:59:41.324840 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1/foo
2022-04-27 07:59:41.325793 +0200  <CLIENT-10658>  Deleting /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1
2022-04-27 07:59:41.327224 +0200  <CLIENT-10658>  Removing directory /backup/rdiff/rdiff-backup-data/rdiff-backup.tmp.1
2022-04-27 07:59:41.332383 +0200  <CLIENT-10658>  -----------------------------------------------------------------
Detected abilities for b'/backup/rdiff/rdiff-backup-data' (read/write) file system:
  Ownership changing                           On
  Hard linking                                 On
  fsync() directories                          On
  Directory inc permissions                    Off
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   Off
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
2022-04-27 07:59:47.144178 +0200  <CLIENT-10658>  Warning: Access Control List file not found
2022-04-27 15:09:44.392158 +0200  <CLIENT-10658>  Exception 'Compressed file ended before the end-of-stream marker was reached' raised of class '<class 'EOFError'
>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/robust.py", line 35, in check_common_error
    return function(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 528, in get_fp
    current_fp = self.get_first_fp()
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 570, in get_first_fp
    rpath.copyfileobj(fp, current_fp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 79, in copyfileobj
    inbuf = inputfp.read(blocksize)
  File "/usr/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "

2022-04-27 15:09:44.921791 +0200  <CLIENT-10658>  Exception 'Compressed file ended before the end-of-stream marker was reached' raised of class '<class 'EOFError'
>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 417, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 357, in take_action
    CheckDest(rps[0])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 1075, in CheckDest
    dest_rp.conn.regress.Regress(dest_rp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/regress.py", line 71, in Regress
    ITR(rf.index, rf)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 313, in __call__
    last_branch.fast_process(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/regress.py", line 295, in fast_process
    self.restore_orig_regfile(rf)
  File "/usr/lib/python3/dist-packages/rdiff_backup/regress.py", line 319, in restore_orig_regfile
    tf.write_from_fileobj(rf.get_restore_fp())
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 558, in get_restore_fp
    return robust.check_common_error(error_handler, get_fp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/robust.py", line 35, in check_common_error
    return function(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 528, in get_fp
    current_fp = self.get_first_fp()
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 570, in get_first_fp
    rpath.copyfileobj(fp, current_fp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 79, in copyfileobj
    inbuf = inputfp.read(blocksize)
  File "/usr/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "

2022-04-27 07:59:41.338988 +0200  <CLIENT-10658>  Backup: escape_dos_devices = 0
2022-04-27 07:59:41.339213 +0200  <CLIENT-10658>  Backup: escape_trailing_spaces = 0
2022-04-27 07:59:45.690851 +0200  <CLIENT-10658>  Regressing to Mon Apr 25 03:08:31 2022
2022-04-27 07:59:51.645086 +0200  <CLIENT-10658>  Regressing file Agata_Work
Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 417, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 357, in take_action
    CheckDest(rps[0])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 1075, in CheckDest
    dest_rp.conn.regress.Regress(dest_rp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/regress.py", line 71, in Regress
    ITR(rf.index, rf)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 313, in __call__
    last_branch.fast_process(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/regress.py", line 295, in fast_process
    self.restore_orig_regfile(rf)
  File "/usr/lib/python3/dist-packages/rdiff_backup/regress.py", line 319, in restore_orig_regfile
    tf.write_from_fileobj(rf.get_restore_fp())
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 558, in get_restore_fp
    return robust.check_common_error(error_handler, get_fp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/robust.py", line 35, in check_common_error
    return function(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 528, in get_fp
    current_fp = self.get_first_fp()
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 570, in get_first_fp
    rpath.copyfileobj(fp, current_fp)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 79, in copyfileobj
    inbuf = inputfp.read(blocksize)
  File "/usr/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by ericzolf** [comment]
Can you run `rdiff-backup -v9 --check-destination-dir /backup/rdiff >/tmp/regress.txt 2>&1` and attach the resulting logfile to this issue?

**Comment by pronego-mls** [comment]
Thank you for the quick response.
The command is running again as suggested, I'll post the resulting file when it's completed (it takes a while).

Concerning your second question: When I tried to restore data, it told me first that another instance of rdiff-backup is still running. Therefore, I killed it (hard) not knowing about any side effects this might cause. Then, I came across the other issues mentioned above.

**Comment by ericzolf** [comment]
Killing hard means that the application has no chance to handle gracefully the interruption, so anything bad can happen. Don't do this unless you know what you're doing (and it's not specific to rdiff-backup). Anyway, waiting for the logs...

**Comment by pronego-mls** [comment]
[regress.txt](https://github.com/rdiff-backup/rdiff-backup/files/8588482/regress.txt)

Here is the requrested file but it doesn't contain anything else than the information provided in section "More information" as far I can tell.

**Comment by ericzolf** [comment]
Just to be sure, I'm first trying to save your backup repository, after that I can try to look on how to handle the error perhaps better in the future (not sure it's possible but I can try). My questions are now related to saving your repo, it will be fiddly, if you're not interested, let me know, we'll spare a lot of back and forth.

What does `ls -la /backup/rdiff/rdiff-backup-data/` resp. `ls -la /backup/rdiff/rdiff-backup-data/Agata_Work*` show? Is Agata_Work the first file in alphabetical order? What is the file just after Agata_Work in alphabetical order? Call it XXX and provide the output of `ls -la /backup/rdiff/rdiff-backup-data/XXX*`.

**Comment by pronego-mls** [comment]
/backup is my external ntfs-formatted usb drive.
[output1.txt](https://github.com/rdiff-backup/rdiff-backup/files/8597193/output1.txt)

```ls -la /backup/rdiff/rdiff-backup-data/Agata_Work*``` returns "File or directory not found."
The file Agata_Work is located in ```/backup/rdiff/Agata_Work```
The other requested output is attached (-> output1.txt).

I would be happy to help improving the product.

If it helps investigating the problem, we can setup a meeting and talk on the phone, and even do a Teamviewer/Anydesk remote control session to save both of our time.
I'm from Germany (GMT+2). Please email me to mls@pronego.com to schedule a meeting.

**Comment by ericzolf** [comment]
I'm doing this in my (little) free time, so I don't really want (can) block time for this, but thanks for the offer. Asynchronous communication is the way to go for me.

Sorry, I messed up the later commands, it should have been: `ls -la /backup/rdiff/rdiff-backup-data/increments/Agata_Work*` resp. `ls -la /backup/rdiff/rdiff-backup-data/increments/XXX*`.

**Comment by pronego-mls** [comment]
Hi,
sorry for the delay, I had to replace the broken HDDs first. The resync took some time and I had some trouble with GRUB...
But back to your questions, here are the answers:

```
# ls -la /backup/rdiff/rdiff-backup-data/increments/Agata_Work*
-rwxrwxrwx 1 root root 159519475689 26. Apr 20:36 /backup/rdiff/rdiff-backup-data/increments/Agata_Work.2022-04-25T03:08:31+02:00.snapshot.gz
```
```
# ls -la | less
drwxrwxrwx 1 root root        12288 26. Apr 06:05 .
drwxrwxrwx 1 root root       258048 28. Apr 09:18 ..
-rwxrwxrwx 1 root root 159519475689 26. Apr 20:36 Agata_Work.2022-04-25T03:08:31+02:00.snapshot.gz
drwxrwxrwx 1 root root         4096 16. Dez 14:39 httpd
drwxrwxrwx 1 root root        24576 23. Apr 07:28 private
-rwxrwxrwx 1 root root            0 14. Dez 10:43 private.2021-12-17T05:31:33+01:00.dir
-rwxrwxrwx 1 root root            0 14. Dez 10:43 private.2021-12-19T05:24:12+01:00.dir
-rwxrwxrwx 1 root root            0 19. Dez 20:25 private.2021-12-20T05:29:16+01:00.dir
-rwxrwxrwx 1 root root            0 20. Dez 14:11 private.2021-12-21T05:41:19+01:00.dir
-rwxrwxrwx 1 root root            0 21. Dez 08:30 private.2021-12-22T05:13:30+01:00.dir
-rwxrwxrwx 1 root root            0 22. Dez 09:52 private.2021-12-23T05:45:24+01:00.dir
[...]
```

**Comment by ericzolf** [comment]
Mmh, I'm somewhat confused on what exactly happened because from the 26th of April, there seems to be only the current_mirror and it isn't compressed. It seems I'm overseeing something...
Could you call `find /backup/rdiff/rdiff-backup-data -name '*2022-04-2[56]*.gz' | xargs gzip -vt` so that we can find which file might be corrupt. If you don't find any then extend the search pattern to something like `*2022-04-2*.gz` but that would really surprise me.

**Comment by pronego-mls** [comment]
Here's the requested output:
```
# find /backup/rdiff/rdiff-backup-data -name '*2022-04-2[56]*.gz' | xargs gzip -vt
/backup/rdiff/rdiff-backup-data/increments/Agata_Work.2022-04-25T03:08:31+02:00.snapshot.gz:
gzip: /backup/rdiff/rdiff-backup-data/increments/Agata_Work.2022-04-25T03:08:31+02:00.snapshot.gz: unexpected end of file
```

**Comment by ericzolf** [comment]
Then simply move away the faulty file and try again to regress the last backup using `--check-destination-dir `.

**Comment by pronego-mls** [comment]
Done...I have deleted all files with timestamp *2022-04-25* like you suggested.
Then, I called ```rdiff-backup --check-destination-dir``` again with the result ```Destination dir /backup/rdiff does not need checking.```
Finally, I successfully called the restore command again.
```
# rdiff-backup --force --restore-as-of 2022-04-24 /backup/rdiff/ /data/
Warning: Access Control List file not found
```
What does the warning mean?

**Comment by ericzolf** [comment]
That the file containing the saved ACLs couldn't be found. My suggestion was never to delete all files but only the faulty one. Anyway, if a recovery was possible, even without ACLs, it should be OK. I would still recommend to start a new repository with the next backup, so as to avoid any risk.

**Comment by pronego-mls** [comment]
OK. I'm happy that I could finally restore my files.
Thank you very much for your help!
