### ISSUE TITLE
[BUG] -r now --exclude app/log.txt always overwrites the file that is expected to be excluded

### ISSUE THREAD

**Issue by xi-business** [rdiff-backup/rdiff-backup#700]
## Bug summary

When I combined `--exclude 'app/log.txt'` with `-r now`, the the excluded file is always restored - even when there are no changes. It should be never restored, instead. `--exclude '**/log.txt'` seems to work. I checked the path to be correct and if the path was not correct the file would be restored only when there are changes, not always. The same seems to be true for all other files in my restored location, also in subdirectories. For some reason it seems to treat such excludes of single files as includes. Note that it only works incorrectly for files, not directories.

I was able to reproduce this on a freshly created backup using the same globbing filelist that contained files from multiple places in /, some excluded, created using `rdiff-backup -v5 --exclude /root/test --include-globbing-filelist .scripts/rdiff-files --exclude / / /root/test` in `/root`. and then restored with `rdiff-backup -v5 --force -r now --exclude app/log.txt test/home/app/app/ app` a couple of times, each time overwriting the file.

The globbing filelist, amongst other things, included
```
- /home/app/app/cache
/home/app
```

I was unable to reproduce this issue on a simpler backup with two files. I suspect that it might have something to do with directory app and its subdirectory app having the same name or maybe with the fact that I am restoring just a part of the whole backup and some relative paths are not computed correctly. Permissions were not an issue, as this was ran as root (although on files of a different user).

## Version, Python, Operating System

Call `rdiff-backup info` (version >= 2.1) or `rdiff-backup -v9` and replace the following line with the output, repeat for each environment impacted:

```yaml
2022-04-29 02:29:10.111193 +0200  <CLIENT-3576958>  Fatal Error: No arguments given
See the rdiff-backup manual page for more information.
2022-04-29 02:29:10.107091 +0200  <CLIENT-3576958>  Using rdiff-backup version 2.0.5
2022-04-29 02:29:10.107261 +0200  <CLIENT-3576958>      with cpython /usr/bin/python3 version 3.9.2
2022-04-29 02:29:10.111050 +0200  <CLIENT-3576958>      on Linux-5.10.0-8-amd64-x86_64-with-glibc2.31, fs encoding utf-8
```

It is Debian 11.2 version.

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup -v9 -r now --force --exclude 'app/log.txt' --exclude app /home/haruka/backup/daily/home/app/app/ app/
rdiff-backup -v9 -r now --force --exclude 'app/log.txt' /home/haruka/backup/daily/home/app/app/ app/
```

## What happened and what did you expect?

In the first example, there was an error where I expected the directory to not be restored. In the second example, a file that was in `--exclude app/log.txt` was still restored, overwriting previous contents.
Incidentially, `--exclude '**/log.txt'` works as expected and `--exclude 'app/log.txt'` causes the file to be always restored, even when there are no changes. Without `--exclude 'app/log.txt'`, the file is restored only if the contents change.

## More information

```
[1] root@host:/home/app# rdiff-backup -v9 -r now --force --exclude 'app/log.txt' --exclude app /home/haruka/backup/daily/home/app/app/ app/
2022-04-29 02:26:48.222605 +0200  <CLIENT-3570187>  Using rdiff-backup version 2.0.5
2022-04-29 02:26:48.222810 +0200  <CLIENT-3570187>      with cpython /usr/bin/python3 version 3.9.2
2022-04-29 02:26:48.226630 +0200  <CLIENT-3570187>      on Linux-5.10.0-8-amd64-x86_64-with-glibc2.31, fs encoding utf-8
2022-04-29 02:26:48.230881 +0200  <CLIENT-3570187>  Using mirror root directory /home/haruka/backup/daily
2022-04-29 02:26:48.231671 +0200  <CLIENT-3570187>  Unable to import win32security module. Windows ACLs
not supported by filesystem at /home/haruka/backup/daily/rdiff-backup-data
2022-04-29 02:26:48.232797 +0200  <CLIENT-3570187>  -----------------------------------------------------------------
Detected abilities for rdiff-backup repository (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
2022-04-29 02:26:48.233524 +0200  <CLIENT-3570187>  Making directory app/rdiff-backup.tmp.0
2022-04-29 02:26:48.233833 +0200  <CLIENT-3570187>  Touching app/rdiff-backup.tmp.0/5-_ a.snapshot.gz
2022-04-29 02:26:48.234068 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0/5-_ a.snapshot.gz
2022-04-29 02:26:48.234219 +0200  <CLIENT-3570187>  Touching app/rdiff-backup.tmp.0/uniá
2022-04-29 02:26:48.235097 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0/uniá
2022-04-29 02:26:48.235297 +0200  <CLIENT-3570187>  Touching app/rdiff-backup.tmp.0/:\"
2022-04-29 02:26:48.235437 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0/:\"
2022-04-29 02:26:48.235599 +0200  <CLIENT-3570187>  Touching app/rdiff-backup.tmp.0/A
2022-04-29 02:26:48.235804 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0/A
2022-04-29 02:26:48.235935 +0200  <CLIENT-3570187>  Touching app/rdiff-backup.tmp.0/foo
2022-04-29 02:26:48.236141 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0/foo
2022-04-29 02:26:48.236308 +0200  <CLIENT-3570187>  Making directory app/rdiff-backup.tmp.0/hl
2022-04-29 02:26:48.236469 +0200  <CLIENT-3570187>  Touching app/rdiff-backup.tmp.0/hardlinked_file1
2022-04-29 02:26:48.236609 +0200  <CLIENT-3570187>  Hard linking app/rdiff-backup.tmp.0/hl/hardlinked_file2 to app/rdiff-backup.tmp.0/hardlinked_file1
2022-04-29 02:26:48.238538 +0200  <CLIENT-3570187>  Unable to import win32security module. Windows ACLs
not supported by filesystem at app/rdiff-backup.tmp.0
2022-04-29 02:26:48.238665 +0200  <CLIENT-3570187>  Touching app/rdiff-backup.tmp.0/dir_inc_check
2022-04-29 02:26:48.238980 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0/dir_inc_check
2022-04-29 02:26:48.239138 +0200  <CLIENT-3570187>  Touching app/rdiff-backup.tmp.0/regfile
2022-04-29 02:26:48.239334 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0/regfile
2022-04-29 02:26:48.239873 +0200  <CLIENT-3570187>  Touching app/rdiff-backup.tmp.0/high_perms_file
2022-04-29 02:26:48.240069 +0200  <CLIENT-3570187>  Touching app/rdiff-backup.tmp.0/high_perms_dir
2022-04-29 02:26:48.240313 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0/high_perms_file
2022-04-29 02:26:48.240981 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0/high_perms_dir
2022-04-29 02:26:48.241156 +0200  <CLIENT-3570187>  Touching app/rdiff-backup.tmp.0/symlinked_file1
2022-04-29 02:26:48.241415 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0/symlinked_file2
2022-04-29 02:26:48.241499 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0/symlinked_file1
2022-04-29 02:26:48.241675 +0200  <CLIENT-3570187>  Touching app/rdiff-backup.tmp.0/foo
2022-04-29 02:26:48.241816 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0/foo
2022-04-29 02:26:48.241963 +0200  <CLIENT-3570187>  Deleting app/rdiff-backup.tmp.0
2022-04-29 02:26:48.242018 +0200  <CLIENT-3570187>  Removing directory app/rdiff-backup.tmp.0
2022-04-29 02:26:48.242565 +0200  <CLIENT-3570187>  -----------------------------------------------------------------
Detected abilities for restore target (read/write) file system:
  Ownership changing                           On
  Hard linking                                 On
  fsync() directories                          On
  Directory inc permissions                    On
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   Off
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
2022-04-29 02:26:48.562971 +0200  <CLIENT-3570187>  Exception '[Errno 39] Directory not empty: b'app'' raised of class '<class 'OSError'>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 417, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 373, in take_action
    Restore(rps[0], rps[1], 1)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 720, in Restore
    restore.Restore(
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 42, in Restore
    TargetS.patch(target, diff_iter)
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 337, in patch
    ITR.Finish()
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 277, in Finish
    to_be_finished.end_process()
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 762, in end_process
    self.base_rp.rmdir()
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1222, in rmdir
    self.conn.os.rmdir(self.path)

2022-04-29 02:26:48.244765 +0200  <CLIENT-3570187>  Backup: escape_dos_devices = 0
2022-04-29 02:26:48.244827 +0200  <CLIENT-3570187>  Backup: escape_trailing_spaces = 0
2022-04-29 02:26:48.246673 +0200  <CLIENT-3570187>  Starting restore of /home/haruka/backup/daily/home/app/app to app as it was as of Fri Apr 29 02:26:48 2022.
2022-04-29 02:26:48.553545 +0200  <CLIENT-3570187>  Processing changed file .
2022-04-29 02:26:48.554824 +0200  <CLIENT-3570187>  Regular copying () to ./rdiff-backup.tmp.1
2022-04-29 02:26:48.557684 +0200  <CLIENT-3570187>  Removing directory app
Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 417, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 373, in take_action
    Restore(rps[0], rps[1], 1)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 720, in Restore
    restore.Restore(
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 42, in Restore
    TargetS.patch(target, diff_iter)
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 337, in patch
    ITR.Finish()
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 277, in Finish
    to_be_finished.end_process()
  File "/usr/lib/python3/dist-packages/rdiff_backup/restore.py", line 762, in end_process
    self.base_rp.rmdir()
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1222, in rmdir
    self.conn.os.rmdir(self.path)
OSError: [Errno 39] Directory not empty: b'app'
```

```
root@host:/home/app# rdiff-backup -v9 -r now --force --exclude 'app/log.txt' /home/haruka/backup/daily/home/app/app/ app/
2022-04-29 02:26:53.325792 +0200  <CLIENT-3570448>  Using rdiff-backup version 2.0.5
2022-04-29 02:26:53.325995 +0200  <CLIENT-3570448>      with cpython /usr/bin/python3 version 3.9.2
2022-04-29 02:26:53.329514 +0200  <CLIENT-3570448>      on Linux-5.10.0-8-amd64-x86_64-with-glibc2.31, fs encoding utf-8
2022-04-29 02:26:53.334036 +0200  <CLIENT-3570448>  Using mirror root directory /home/haruka/backup/daily
2022-04-29 02:26:53.334685 +0200  <CLIENT-3570448>  Unable to import win32security module. Windows ACLs
not supported by filesystem at /home/haruka/backup/daily/rdiff-backup-data
2022-04-29 02:26:53.335450 +0200  <CLIENT-3570448>  -----------------------------------------------------------------
Detected abilities for rdiff-backup repository (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
2022-04-29 02:26:53.336181 +0200  <CLIENT-3570448>  Making directory app/rdiff-backup.tmp.0
2022-04-29 02:26:53.336388 +0200  <CLIENT-3570448>  Touching app/rdiff-backup.tmp.0/5-_ a.snapshot.gz
2022-04-29 02:26:53.336523 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0/5-_ a.snapshot.gz
2022-04-29 02:26:53.336653 +0200  <CLIENT-3570448>  Touching app/rdiff-backup.tmp.0/uniá
2022-04-29 02:26:53.337491 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0/uniá
2022-04-29 02:26:53.337625 +0200  <CLIENT-3570448>  Touching app/rdiff-backup.tmp.0/:\"
2022-04-29 02:26:53.337735 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0/:\"
2022-04-29 02:26:53.337936 +0200  <CLIENT-3570448>  Touching app/rdiff-backup.tmp.0/A
2022-04-29 02:26:53.338081 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0/A
2022-04-29 02:26:53.338232 +0200  <CLIENT-3570448>  Touching app/rdiff-backup.tmp.0/foo
2022-04-29 02:26:53.338381 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0/foo
2022-04-29 02:26:53.338516 +0200  <CLIENT-3570448>  Making directory app/rdiff-backup.tmp.0/hl
2022-04-29 02:26:53.338716 +0200  <CLIENT-3570448>  Touching app/rdiff-backup.tmp.0/hardlinked_file1
2022-04-29 02:26:53.338912 +0200  <CLIENT-3570448>  Hard linking app/rdiff-backup.tmp.0/hl/hardlinked_file2 to app/rdiff-backup.tmp.0/hardlinked_file1
2022-04-29 02:26:53.340986 +0200  <CLIENT-3570448>  Unable to import win32security module. Windows ACLs
not supported by filesystem at app/rdiff-backup.tmp.0
2022-04-29 02:26:53.341083 +0200  <CLIENT-3570448>  Touching app/rdiff-backup.tmp.0/dir_inc_check
2022-04-29 02:26:53.341275 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0/dir_inc_check
2022-04-29 02:26:53.341398 +0200  <CLIENT-3570448>  Touching app/rdiff-backup.tmp.0/regfile
2022-04-29 02:26:53.341527 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0/regfile
2022-04-29 02:26:53.341826 +0200  <CLIENT-3570448>  Touching app/rdiff-backup.tmp.0/high_perms_file
2022-04-29 02:26:53.342020 +0200  <CLIENT-3570448>  Touching app/rdiff-backup.tmp.0/high_perms_dir
2022-04-29 02:26:53.342179 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0/high_perms_file
2022-04-29 02:26:53.342720 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0/high_perms_dir
2022-04-29 02:26:53.342866 +0200  <CLIENT-3570448>  Touching app/rdiff-backup.tmp.0/symlinked_file1
2022-04-29 02:26:53.343091 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0/symlinked_file2
2022-04-29 02:26:53.343169 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0/symlinked_file1
2022-04-29 02:26:53.343336 +0200  <CLIENT-3570448>  Touching app/rdiff-backup.tmp.0/foo
2022-04-29 02:26:53.343453 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0/foo
2022-04-29 02:26:53.343527 +0200  <CLIENT-3570448>  Deleting app/rdiff-backup.tmp.0
2022-04-29 02:26:53.343557 +0200  <CLIENT-3570448>  Removing directory app/rdiff-backup.tmp.0
2022-04-29 02:26:53.344003 +0200  <CLIENT-3570448>  -----------------------------------------------------------------
Detected abilities for restore target (read/write) file system:
  Ownership changing                           On
  Hard linking                                 On
  fsync() directories                          On
  Directory inc permissions                    On
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   Off
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
2022-04-29 02:26:53.345947 +0200  <CLIENT-3570448>  Backup: escape_dos_devices = 0
2022-04-29 02:26:53.345991 +0200  <CLIENT-3570448>  Backup: escape_trailing_spaces = 0
2022-04-29 02:26:53.347434 +0200  <CLIENT-3570448>  Starting restore of /home/haruka/backup/daily/home/app/app to app as it was as of Fri Apr 29 02:26:53 2022.
2022-04-29 02:26:53.359961 +0200  <CLIENT-3570448>  Processing changed file .
2022-04-29 02:26:53.932576 +0200  <CLIENT-3570448>  Processing changed file log.txt
2022-04-29 02:26:53.932949 +0200  <CLIENT-3570448>  Regular copying (b'log.txt',) to app/rdiff-backup.tmp.1
2022-04-29 02:26:53.933031 +0200  <CLIENT-3570448>  Writing file object to app/rdiff-backup.tmp.1
2022-04-29 02:26:54.047202 +0200  <CLIENT-3570448>  Hash 7e264831453b946727ebd24e4929fb887c08e3f4 of log.txt verified
2022-04-29 02:26:54.047340 +0200  <CLIENT-3570448>  Copying attributes from (b'log.txt',) to app/rdiff-backup.tmp.1
2022-04-29 02:26:54.047898 +0200  <CLIENT-3570448>  Setting time of app/rdiff-backup.tmp.1 to 1651185242
2022-04-29 02:26:54.049234 +0200  <CLIENT-3570448>  Renaming app/rdiff-backup.tmp.1 to app/log.txt
2022-04-29 02:26:54.208934 +0200  <CLIENT-3570448>  Copying attributes from () to app
2022-04-29 02:26:54.209129 +0200  <CLIENT-3570448>  Setting time of app to 1651185782
2022-04-29 02:26:54.209320 +0200  <CLIENT-3570448>  Restore finished
2022-04-29 02:26:54.209380 +0200  <CLIENT-3570448>  Cleaning up
```

**Comment by ericzolf** [comment]
There was an issue with selecting _and_ restoring a sub-path at the same time, it is now forbidden and a workaround has been documented, see PR #694 (the workaround can be used in older versions of rdiff-backup). Please close the issue if the workaround... works.

The workaround reads:

Since rdiff-backup 2.1+, a command like `rdiff-backup restore --include myrestore/subdir/somefile --exclude '**' myrepo/subdir myrestore/subdir` isn't possible anymore, because it could lead to [data loss](https://github.com/rdiff-backup/rdiff-backup/issues/463)
Such calls are anyway equivalent to something like `rdiff-backup restore --include myrestore/subdir/somefile --exclude '**' myrepo myrestore`.
This means that the new limitation doesn't imply a loss in feature, it only enforces a new approach without risk of losing data.

**Comment by ericzolf** [comment]
No reaction, closing. Feel free to re-open if you see the need.
