### ISSUE TITLE
[BUG] test utils_simpleps_test fails with OverflowError on Windows if psutil is installed

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#744]
## Bug summary

See title, this only happens if psutil is installed

## Version, Python, Operating System

Latest development version...

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
tox -c tox_win.ini -e py
```

## What happened and what did you expect?

```
py run-test: commands[6] | python testing/utils_simpleps_test.py --verbose --buf
fer
test_utils_simpleps (__main__.UtilsPsutilTest) 
verify that hardlinked files can be rotated, see issue #272 ... ERROR 

Stdout:
testing/utils_simpleps_test.py
 
======================================================================
ERROR: test_utils_simpleps (__main__.UtilsPsutilTest)
verify that hardlinked files can be rotated, see issue #272
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vagrant\Develop\rdiff-backup\testing\utils_simpleps_test.py", line 26, in test_utils_simpleps
    self.assertIsNone(simpleps.get_pid_name(sys.maxsize))
  File "C:\Users\vagrant\Develop\rdiff-backup\.tox\py\lib\site-packages\rdiffbackup\utils\simpleps.py", line 34, in _get_pid_name_psutil
    proc = psutil.Process(int(pid))
  File "C:\Users\vagrant\Develop\rdiff-backup\.tox\py\lib\site-packages\psutil\__init__.py", line 332, in __init__
    self._init(pid)
  File "C:\Users\vagrant\Develop\rdiff-backup\.tox\py\lib\site-packages\psutil\__init__.py", line 361, in _init
    self.create_time()
  File "C:\Users\vagrant\Develop\rdiff-backup\.tox\py\lib\site-packages\psutil\__init__.py", line 714, in create_time
    self._create_time = self._proc.create_time()
  File "C:\Users\vagrant\Develop\rdiff-backup\.tox\py\lib\site-packages\psutil\_pswindows.py", line 688, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\vagrant\Develop\rdiff-backup\.tox\py\lib\site-packages\psutil\_pswindows.py", line 942, in create_time
    user, system, created = cext.proc_times(self.pid)
OverflowError: Python int too large to convert to C long

Stdout:
testing/utils_simpleps_test.py

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (errors=1)
ERROR: InvocationError for command 'C:\Users\vagrant\Develop\rdiff-backup\.tox\p
y\Scripts\python.EXE' testing/utils_simpleps_test.py --verbose --buffer (exited 
with code 1)
```

## More information

Can be repeated at any time if psutil is installed

**Comment by ericzolf** [comment]
It's probably not that bad: I use sys.maxsize as surely non-existing PID and Windows/psutil finds it too big. I need to find another PID which doesn't probably exist.
