### ISSUE TITLE
[BUG] Further Regression with Permissions in 2.1.3b3

### ISSUE THREAD

**Issue by frankcrawford** [rdiff-backup/rdiff-backup#765]
## Bug summary

When running `rdiff-backup --force remove increments` it fails with a Permission error on a file in a directory without write permission:
```
PermissionError: [Errno 13] Permission denied: b'/srv/archive/safekeep-client/backup/boot/efi'
```
Also during handling of the first exception a second exception occurs.

## Version, Python, Operating System

```yaml
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.1.3b3
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.10.7
system:
  fs_encoding: utf-8
  platform: Linux-5.19.15-201.fc36.x86_64-x86_64-with-glibc2.35

```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
rdiff-backup --force remove increments --older-than 9D /srv/archive/safekeep-client/backup
```

## What happened and what did you expect?

Expected normal cleanup of old increments.

## More information

Traceback of call was
```
NOTE: Deleting increments at dates/times:
Mon Sep  5 03:39:39 2022
Tue Sep  6 03:17:43 2022
Wed Sep  7 03:24:35 2022
Thu Sep  8 03:16:42 2022
Fri Sep  9 03:31:00 2022
Sat Sep 10 03:24:10 2022
Sun Sep 11 03:41:36 2022
Mon Sep 12 03:47:12 2022
Tue Sep 13 03:13:21 2022
Wed Sep 14 03:15:13 2022
Thu Sep 15 03:52:27 2022
Fri Sep 16 03:33:33 2022
Sat Sep 17 03:47:44 2022
Sun Sep 18 03:40:15 2022
Mon Sep 19 03:50:46 2022
Tue Sep 20 03:32:51 2022
Wed Sep 21 03:19:49 2022
Thu Sep 22 03:22:38 2022
Fri Sep 23 03:32:30 2022
Sat Sep 24 03:16:02 2022
Sun Sep 25 03:33:02 2022
Mon Sep 26 03:49:47 2022
Tue Sep 27 03:51:18 2022
Wed Sep 28 03:29:37 2022
Thu Sep 29 03:30:56 2022
Fri Sep 30 03:13:20 2022
Sat Oct  1 03:26:04 2022
Sun Oct  2 03:37:33 2022
Mon Oct  3 03:39:34 2022
Tue Oct  4 03:33:58 2022
Wed Oct  5 03:24:50 2022
Thu Oct  6 03:20:30 2022
Fri Oct  7 03:32:16 2022
Sat Oct  8 03:27:46 2022
Sun Oct  9 03:31:25 2022
Mon Oct 10 03:26:32 2022
Tue Oct 11 03:23:46 2022
Thu Oct 13 04:05:08 2022
Fri Oct 14 03:11:45 2022
Sat Oct 15 03:15:06 2022
Sun Oct 16 03:50:41 2022
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/rpath.py", line 898, in delete
    self.rmdir()
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/rpath.py", line 804, in rmdir
    self.conn.os.rmdir(self.path)
PermissionError: [Errno 13] Permission denied: b'/srv/archive/safekeep-client/backup/boot/efi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 33, in <module>
    sys.exit(load_entry_point('rdiff-backup==2.1.3b3', 'console_scripts', 'rdiff-backup')())
  File "/usr/lib64/python3.10/site-packages/rdiffbackup/run.py", line 37, in main
    sys.exit(main_run(sys.argv[1:]))
  File "/usr/lib64/python3.10/site-packages/rdiffbackup/run.py", line 105, in main_run
    ret_val |= conn_act.run()
  File "/usr/lib64/python3.10/site-packages/rdiffbackup/actions/remove.py", line 117, in run
    manage.delete_earlier_than(self.repo.base_dir, self.action_time)
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/manage.py", line 32, in delete_earlier_than
    baserp.conn.manage.delete_earlier_than_local(baserp, time)
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/manage.py", line 53, in delete_earlier_than_local
    rp.delete()
  File "/usr/lib64/python3.10/site-packages/rdiff_backup/rpath.py", line 902, in delete
    self.conn.shutil.rmtree(self.path)
  File "/usr/lib64/python3.10/shutil.py", line 730, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib64/python3.10/shutil.py", line 728, in rmtree
    os.rmdir(path)
PermissionError: [Errno 13] Permission denied: '/srv/archive/safekeep-client/backup/boot/efi'
```
Permission on failed directory:
```
ls -la /srv/archive/safekeep-client/backup/boot/efi
total 8
drwx------. 2 safekeep safekeep 4096 Oct 25 03:57 .
dr-xr-xr-x. 6 safekeep safekeep 4096 Oct 20 06:09 ..
```
Note lack of write permissions on parent directory.

**Comment by ericzolf** [comment]
Forget it, after some changes to the source directory, and a 2nd call, the directory looses it's write access (so only after 1st increment, also not very correct).

**Comment by ericzolf** [comment]
OK, I got it after all: the directory within the read0only directory must be _empty_ else the issue doesn't appear. Here the repeater:
[test_mkdir.txt](https://github.com/rdiff-backup/rdiff-backup/files/9871147/test_mkdir.txt)

**Comment by frankcrawford** [comment]
Some very limited background, it is a VM install and the permissions are pretty much from the standard Fedora setup.  As a VM it doesn't have any EFI component, but does have the efi directory, for mounting the partition, if required.

Strangely on the original server there is another directory within that one that is not being backed up.  I will need to look at that later.

I'll try the patch and see how it goes.

**Comment by ericzolf** [comment]
From your previous bug report, you are doing your backup as safekeep user. The efi directory is only readable by root, hence its content can't get backed-up.

**Comment by frankcrawford** [comment]
No, the backup on the remote host is run as root, the local part of rdiff-backup is run as safekeep and hence the backup is owned by safekeep.  However, I'll look at the issue a bit closer, because it is a bit of a surprise that I hadn't noticed before.

**Comment by frankcrawford** [comment]
Also, the remote host is running v2.0.5.
