### ISSUE TITLE
[BUG] rdiff-backup crashes on EAs when backing up to an nfs share

### ISSUE THREAD

**Issue by l3u** [rdiff-backup/rdiff-backup#789]
## Bug summary

Let's get one thing out of the way, this does **not** happen when I do the exact same thing on my Gentoo machine, but both on a fresh installation of Devuan Chimaera and Debian Bullseye. So possibly, this is (at least partly) Debian-specific; anyway, rdiff-backup should not crash.

When I try to backup something to an nfs share, rdiff-backup crashes:

    # rdiff-backup foo/ /nas/backup/test/
    Exception '[Errno 22] Invalid argument' raised of class '<class 'OSError'>':
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
        Main(arglist)
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 417, in Main
        take_action(rps)
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 353, in take_action
        Backup(rps[0], rps[1])
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 442, in Backup
        backup.Mirror(rpin, rpout)
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 39, in Mirror
        DestS.patch(dest_rpath, source_diffiter)
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 269, in patch
        ITR(diff.index, diff)
    File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 313, in __call__
        last_branch.fast_process(*args)
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 587, in fast_process
        if self.patch_to_temp(mirror_rp, diff_rorp, tf):
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 636, in patch_to_temp
        rpath.copy_attribs(diff_rorp, new)
    File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 238, in copy_attribs
        rpout.write_ea(rpin.get_ea())
    File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1664, in write_ea
        ea.write_to_rp(self)
    File "/usr/lib/python3/dist-packages/rdiff_backup/eas_acls.py", line 131, in write_to_rp
        self.clear_rp(rp)
    File "/usr/lib/python3/dist-packages/rdiff_backup/eas_acls.py", line 106, in clear_rp
        rp.conn.xattr.remove(rp.path, name, rp.issym())

    Traceback (most recent call last):
    File "/usr/bin/rdiff-backup", line 32, in <module>
        rdiff_backup.Main.error_check_Main(sys.argv[1:])
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
        Main(arglist)
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 417, in Main
        take_action(rps)
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 353, in take_action
        Backup(rps[0], rps[1])
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 442, in Backup
        backup.Mirror(rpin, rpout)
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 39, in Mirror
        DestS.patch(dest_rpath, source_diffiter)
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 269, in patch
        ITR(diff.index, diff)
    File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 313, in __call__
        last_branch.fast_process(*args)
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 587, in fast_process
        if self.patch_to_temp(mirror_rp, diff_rorp, tf):
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 636, in patch_to_temp
        rpath.copy_attribs(diff_rorp, new)
    File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 238, in copy_attribs
        rpout.write_ea(rpin.get_ea())
    File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1664, in write_ea
        ea.write_to_rp(self)
    File "/usr/lib/python3/dist-packages/rdiff_backup/eas_acls.py", line 131, in write_to_rp
        self.clear_rp(rp)
    File "/usr/lib/python3/dist-packages/rdiff_backup/eas_acls.py", line 106, in clear_rp
        rp.conn.xattr.remove(rp.path, name, rp.issym())
    OSError: [Errno 22] Invalid argument

Looking at this with more verbosity shows that it's caused by settings attributes. The copying works, but the crash happens as soon as rdiff-backup tries to set the attributes.

As far as I can grasp it, this is caused by rdiff-backup trying to set xattrs. I neither use xattrs for the source fs, nor have I set the respective flags in `/etc/fstab`. Nevertheless, rdiff-backup thinks that both the source and the target would support xattrs:

    ------------------------------------------------------------------
    Detected abilities for source (read only) file system:
    Access control lists                         On
    Extended attributes                          On
    Windows access control lists                 Off
    Case sensitivity                             On
    Escape DOS devices                           Off
    Escape trailing spaces                       Off
    Mac OS X style resource forks                Off
    Mac OS X Finder information                  Off
    -----------------------------------------------------------------
    Detected abilities for destination (read/write) file system:
    Ownership changing                           On
    Hard linking                                 On
    fsync() directories                          On
    Directory inc permissions                    On
    High-bit permissions                         On
    Symlink permissions                          Off
    Extended filenames                           On
    Windows reserved filenames                   Off
    Access control lists                         Off
    Extended attributes                          On
    Windows access control lists                 Off
    Case sensitivity                             On
    Escape DOS devices                           Off
    Escape trailing spaces                       Off
    Mac OS X style resource forks                Off
    Mac OS X Finder information                  Off
    -----------------------------------------------------------------

## Version, Python, Operating System

This does happen with rdiff-backup 2.0.5 and Python 3.9.2 on both Devuan Chimaera and Debian Bullseye, using the above command (no command line parameters except for the source and the target). This can e.g. be relibaly reproduced using a fresh minimalist Debian Bullseye netinst installation with only `nfs-common` and `rdiff-backup` being installed additionally.

This does however interestingly **not** happen using rdiff-backup 2.0.5 and Python 3.10.8 on Gentoo, using the same command. Maybe because the kernel I use there doesn't have xattrs enabled, whereas the Devuan and Debian kernels provide the respective module.

No file system uses xattrs on any machine.

Explicitely disabling xattr usage on the Devuan/Debian machines via the `--no-eas` command line switch makes it work.

However I think rdiff-backup should not assume that xattrs are in use when neither the source nor the target support them and even if so not crash but display some error message.

**Comment by l3u** [comment]
Using the said fresh Debian installation, `pip` is not even installed … according to `apt search`, `python3-pyxattr/stable,now 0.7.2-1+b1 amd64` is installed however.

My test dataset consists only of one single regular empty file. I created it like that:

    # mkdir foo
    # touch foo/bar

and that's it. Here's the complete verbose output of `rdiff-backup -v9 foo/ /mnt/test/`:

    2022-11-22 07:45:53.544753 +0100  <CLIENT-483>  Using rdiff-backup version 2.0.5
    2022-11-22 07:45:53.544879 +0100  <CLIENT-483>          with cpython /usr/bin/python3 version 3.9.2
    2022-11-22 07:45:53.546094 +0100  <CLIENT-483>          on Linux-5.10.0-19-amd64-x86_64-with-glibc2.31, fs encoding utf-8
    2022-11-22 07:45:53.567299 +0100  <CLIENT-483>  Making directory /mnt/test/rdiff-backup-data
    2022-11-22 07:45:53.590208 +0100  <CLIENT-483>  Unable to import win32security module. Windows ACLs
    not supported by filesystem at foo
    2022-11-22 07:45:53.590550 +0100  <CLIENT-483>  -----------------------------------------------------------------
    Detected abilities for source (read only) file system:
    Access control lists                         On
    Extended attributes                          On
    Windows access control lists                 Off
    Case sensitivity                             On
    Escape DOS devices                           Off
    Escape trailing spaces                       Off
    Mac OS X style resource forks                Off
    Mac OS X Finder information                  Off
    -----------------------------------------------------------------
    2022-11-22 07:45:53.591626 +0100  <CLIENT-483>  Making directory /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0
    2022-11-22 07:45:53.613391 +0100  <CLIENT-483>  Touching /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/5-_ a.snapshot.gz
    2022-11-22 07:45:53.635118 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/5-_ a.snapshot.gz
    2022-11-22 07:45:53.658429 +0100  <CLIENT-483>  Touching /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/uniá
    2022-11-22 07:45:53.680222 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/uniá
    2022-11-22 07:45:53.703090 +0100  <CLIENT-483>  Touching /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/:\"
    2022-11-22 07:45:53.724698 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/:\"
    2022-11-22 07:45:53.747873 +0100  <CLIENT-483>  Touching /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/A
    2022-11-22 07:45:53.771010 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/A
    2022-11-22 07:45:53.792523 +0100  <CLIENT-483>  Touching /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/foo
    2022-11-22 07:45:53.858761 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/foo
    2022-11-22 07:45:53.883220 +0100  <CLIENT-483>  Making directory /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/hl
    2022-11-22 07:45:53.904747 +0100  <CLIENT-483>  Touching /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/hardlinked_file1
    2022-11-22 07:45:53.927585 +0100  <CLIENT-483>  Hard linking /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/hl/hardlinked_file2 to /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/hardlinked_file1
    2022-11-22 07:45:53.950591 +0100  <CLIENT-483>  POSIX ACLs not supported by filesystem at /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0
    2022-11-22 07:45:53.950716 +0100  <CLIENT-483>  Unable to import win32security module. Windows ACLs
    not supported by filesystem at /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0
    2022-11-22 07:45:53.951367 +0100  <CLIENT-483>  Touching /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/dir_inc_check
    2022-11-22 07:45:53.992320 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/dir_inc_check
    2022-11-22 07:45:54.017296 +0100  <CLIENT-483>  Touching /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/regfile
    2022-11-22 07:45:54.040383 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/regfile
    2022-11-22 07:45:54.061957 +0100  <CLIENT-483>  Touching /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_file
    2022-11-22 07:45:54.084236 +0100  <CLIENT-483>  Touching /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir
    2022-11-22 07:45:54.194794 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_file
    2022-11-22 07:45:54.217293 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/high_perms_dir
    2022-11-22 07:45:54.240267 +0100  <CLIENT-483>  Touching /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/symlinked_file1
    2022-11-22 07:45:54.319523 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/symlinked_file2
    2022-11-22 07:45:54.351514 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/symlinked_file1
    2022-11-22 07:45:54.374978 +0100  <CLIENT-483>  Touching /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/foo
    2022-11-22 07:45:54.396223 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0/foo
    2022-11-22 07:45:54.419521 +0100  <CLIENT-483>  Deleting /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0
    2022-11-22 07:45:54.419582 +0100  <CLIENT-483>  Removing directory /mnt/test/rdiff-backup-data/rdiff-backup.tmp.0
    2022-11-22 07:45:54.531591 +0100  <CLIENT-483>  -----------------------------------------------------------------
    Detected abilities for destination (read/write) file system:
    Ownership changing                           On
    Hard linking                                 On
    fsync() directories                          On
    Directory inc permissions                    On
    High-bit permissions                         On
    Symlink permissions                          Off
    Extended filenames                           On
    Windows reserved filenames                   Off
    Access control lists                         Off
    Extended attributes                          On
    Windows access control lists                 Off
    Case sensitivity                             On
    Escape DOS devices                           Off
    Escape trailing spaces                       Off
    Mac OS X style resource forks                Off
    Mac OS X Finder information                  Off
    -----------------------------------------------------------------
    2022-11-22 07:45:54.744193 +0100  <CLIENT-483>  Exception '[Errno 22] Invalid argument' raised of class '<class 'OSError'>':
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
        Main(arglist)
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 417, in Main
        take_action(rps)
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 353, in take_action
        Backup(rps[0], rps[1])
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 442, in Backup
        backup.Mirror(rpin, rpout)
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 39, in Mirror
        DestS.patch(dest_rpath, source_diffiter)
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 269, in patch
        ITR(diff.index, diff)
    File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 313, in __call__
        last_branch.fast_process(*args)
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 587, in fast_process
        if self.patch_to_temp(mirror_rp, diff_rorp, tf):
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 636, in patch_to_temp
        rpath.copy_attribs(diff_rorp, new)
    File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 238, in copy_attribs
        rpout.write_ea(rpin.get_ea())
    File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1664, in write_ea
        ea.write_to_rp(self)
    File "/usr/lib/python3/dist-packages/rdiff_backup/eas_acls.py", line 131, in write_to_rp
        self.clear_rp(rp)
    File "/usr/lib/python3/dist-packages/rdiff_backup/eas_acls.py", line 106, in clear_rp
        rp.conn.xattr.remove(rp.path, name, rp.issym())

    2022-11-22 07:45:54.575864 +0100  <CLIENT-483>  Backup: escape_dos_devices = 0
    2022-11-22 07:45:54.575920 +0100  <CLIENT-483>  Backup: escape_trailing_spaces = 0
    2022-11-22 07:45:54.602292 +0100  <CLIENT-483>  Making directory /mnt/test/rdiff-backup-data/increments
    2022-11-22 07:45:54.619981 +0100  <CLIENT-483>  Starting mirror foo to /mnt/test
    2022-11-22 07:45:54.690670 +0100  <CLIENT-483>  Processing changed file .
    2022-11-22 07:45:54.692309 +0100  <CLIENT-483>  Processing changed file bar
    2022-11-22 07:45:54.695841 +0100  <CLIENT-483>  Regular copying (b'bar',) to /mnt/test/rdiff-backup.tmp.1
    2022-11-22 07:45:54.695863 +0100  <CLIENT-483>  Writing file object to /mnt/test/rdiff-backup.tmp.1
    2022-11-22 07:45:54.721580 +0100  <CLIENT-483>  Copying attributes from (b'bar',) to /mnt/test/rdiff-backup.tmp.1
    Traceback (most recent call last):
    File "/usr/bin/rdiff-backup", line 32, in <module>
        rdiff_backup.Main.error_check_Main(sys.argv[1:])
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
        Main(arglist)
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 417, in Main
        take_action(rps)
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 353, in take_action
        Backup(rps[0], rps[1])
    File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 442, in Backup
        backup.Mirror(rpin, rpout)
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 39, in Mirror
        DestS.patch(dest_rpath, source_diffiter)
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 269, in patch
        ITR(diff.index, diff)
    File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 313, in __call__
        last_branch.fast_process(*args)
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 587, in fast_process
        if self.patch_to_temp(mirror_rp, diff_rorp, tf):
    File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 636, in patch_to_temp
        rpath.copy_attribs(diff_rorp, new)
    File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 238, in copy_attribs
        rpout.write_ea(rpin.get_ea())
    File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1664, in write_ea
        ea.write_to_rp(self)
    File "/usr/lib/python3/dist-packages/rdiff_backup/eas_acls.py", line 131, in write_to_rp
        self.clear_rp(rp)
    File "/usr/lib/python3/dist-packages/rdiff_backup/eas_acls.py", line 106, in clear_rp
        rp.conn.xattr.remove(rp.path, name, rp.issym())
    OSError: [Errno 22] Invalid argument

I'll try to test the beat version, although I have to see how to install it first ;-)

**Comment by l3u** [comment]
Here's the output for `foo/bar`:

    >>> import xattr
    >>> mypath = b'foo/bar'
    >>> xattr.list(mypath)
    []
    >>> xattr.set(mypath, b"user.test", b'some data')
    >>> xattr.get(mypath, b"user.test")
    b'some data'
    >>> xattr.list(mypath)
    [b'user.test']
    >>> xattr.remove(mypath, b"user.test", False)

and here's the output for `/mnt/test/rdiff-backup.tmp.1`:

    >>> import xattr
    >>> mypath = b'/mnt/test/rdiff-backup.tmp.1'
    >>> xattr.list(mypath)
    [b'system.nfs4_acl']
    >>> xattr.set(mypath, b"user.test", b'some data')
    >>> xattr.get(mypath, b"user.test")
    b'some data'
    >>> xattr.list(mypath)
    [b'system.nfs4_acl', b'user.test']
    >>> xattr.remove(mypath, b"user.test", False)

**Comment by ericzolf** [comment]
What I guessed: extended attributes are supported on both sides, and so rdiff-backup tries to use them, and then the NFS file system reacts in an unexpected manner.

Could you try to remove the system EA? i.e. call `xattr.remove(b'/mnt/test/rdiff-backup.tmp.1', b'system.nfs4_acl', False)`. I would expect that you'll get a nice Errno 22/Invalid argument. If it's the case, we're good and I can fix this for the next version. If not, I'll be surprised...

**Comment by l3u** [comment]
But how are extended attributes supported when I didn't enable them in fstab? And does it work on Gentoo because the xattr support is not compiled into the kernel?

However this is the output of the command you posted:

    >>> xattr.remove(b'/mnt/test/rdiff-backup.tmp.1', b'system.nfs4_acl', False)
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    OSError: [Errno 22] Invalid argument

**Comment by ericzolf** [comment]
> But how are extended attributes supported when I didn't enable them in fstab? And does it work on Gentoo because the xattr support is not compiled into the kernel?

Your guess is probably as good as mine, but I checked https://man7.org/linux/man-pages/man7/xattr.7.html and it states:

       Some filesystems, such as Reiserfs (and, historically, ext2 and
       ext3), require the filesystem to be mounted with the user_xattr
       mount option in order for user extended attributes to be used.

It means for me that newer file systems don't need this option to support xattr. And, of course, if the support is removed from the kernel, it isn't supported either and rdiff-backup would recognize it and act accordingly. And from the top of my mind, NFS does only reflect the underlying file system.

> However this is the output of the command you posted:
> 
> ```
> >>> xattr.remove(b'/mnt/test/rdiff-backup.tmp.1', b'system.nfs4_acl', False)
> Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
> OSError: [Errno 22] Invalid argument
> ```

OK, so your NFS implementation doesn't want us to remove this specific attribute. Fair enough, we already have a similar case with SELinux, so I'll add this case to the acceptable exceptions. Thanls for the report.

**Comment by ericzolf** [comment]
Just for the sake of completeness, what's serving your NFS share? Hardware, OS, parameters, underlying file system?

**Comment by clintar** [comment]
I'd just like to give some info related to this. I have been using rdiff-backup on a machine that mounts an NFS of a ZFS pool from trunas and only after updating the machine from focal 20.04 to jammy 22.04 I started getting these oserrors. Same version of rdiff-backup from the rdiff-backup 2.0 backports it looks like between them, too. I assume something changed in the way jammy mounts nfs that triggers this. That was a while to find this issue, but https://dev1galaxy.org/viewtopic.php?id=5361 lead me here. the --no-eas worked for me. Just putting a note here in case it can help someone else. Which version would this be fixed in btw?

**Comment by ericzolf** [comment]
Version 3.0 which hasn't yet a due date (because of massive on-going refactoring).
