### ISSUE TITLE
Support backup of files changing during backup time

### ISSUE THREAD

**Issue by honzasram** [rdiff-backup/rdiff-backup#8]
Hi! 
For first, thank you for this tool. Saved my ass many times.

I'm facing "Bad index order:" assert exception since last interrupted backup. Since that moment, i cannot run backup correctly and end on this assertion. When I looked around, it seems like there is no clear statement how to fix this except delete backup and rerun it from scratch.

I'm running this on Synology DMS linux with Python 2.7.11 (default, Mar 11 2016, 02:18:13)
`admin@Backup03:~$ rdiff-backup-2.6 --version
rdiff-backup 1.2.8`

Can you help me?

`Previous backup seems to have failed, regressing destination now.
Exception 'Bad index order: ('long_filename_data', '16') >= ('1_firma', '2010', '04_org\xc3\xa1ny spole\xc4\x8dnosti', 'Dozor\xc4\x8dn\xc3\xad                                                                    rada', 'Volba \xc4\x8dlenky DR', 'RE Datumy do z\xc3\xa1pisu p\xc5\x99estavenstva.msg')' raised of class '<type 'exceptions.AssertionError'>':
  File "/opt/lib/python2.5/site-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/opt/lib/python2.5/site-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/opt/lib/python2.5/site-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/opt/lib/python2.5/site-packages/rdiff_backup/Main.py", line 337, in Backup
    backup_final_init(rpout)
  File "/opt/lib/python2.5/site-packages/rdiff_backup/Main.py", line 501, in backup_final_init
    checkdest_if_necessary(rpout)
  File "/opt/lib/python2.5/site-packages/rdiff_backup/Main.py", line 920, in checkdest_if_necessary
    dest_rp.conn.regress.Regress(dest_rp)
  File "/opt/lib/python2.5/site-packages/rdiff_backup/regress.py", line 71, in Regress
    for rf in iterate_meta_rfs(mirror_rp, inc_rpath): ITR(rf.index, rf)
  File "/opt/lib/python2.5/site-packages/rdiff_backup/rorpiter.py", line 275, in **call**
    assert 0, "Bad index order: %s >= %s" % (self.index, index)

Traceback (most recent call last):
  File "/bin/rdiff-backup", line 30, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/opt/lib/python2.5/site-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/opt/lib/python2.5/site-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/opt/lib/python2.5/site-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/opt/lib/python2.5/site-packages/rdiff_backup/Main.py", line 337, in Backup
    backup_final_init(rpout)
  File "/opt/lib/python2.5/site-packages/rdiff_backup/Main.py", line 501, in backup_final_init
    checkdest_if_necessary(rpout)
  File "/opt/lib/python2.5/site-packages/rdiff_backup/Main.py", line 920, in checkdest_if_necessary
    dest_rp.conn.regress.Regress(dest_rp)
  File "/opt/lib/python2.5/site-packages/rdiff_backup/regress.py", line 71, in Regress
    for rf in iterate_meta_rfs(mirror_rp, inc_rpath): ITR(rf.index, rf)
  File "/opt/lib/python2.5/site-packages/rdiff_backup/rorpiter.py", line 275, in **call**
    assert 0, "Bad index order: %s >= %s" % (self.index, index)
AssertionError: Bad index order: ('long_filename_data', '16') >= ('1_firma', '2010', '04_org\xc3\xa1ny spole\xc4\x8dnosti', 'Dozor\xc4\x8dn\xc3                                                                   \xad rada', 'Volba \xc4\x8dlenky DR', 'RE Datumy do z\xc3\xa1pisu p\xc5\x99estavenstva.msg')
`

**Comment by afoster** [comment]
Hi @honzasram 

According to the [rdiff-backup FAQ](http://www.nongnu.org/rdiff-backup/FAQ.html#badindex):

> If rdiff-backup fails with the message "AssertionError: Bad index order," it could be because the files in a directory have changed while rdiff-backup is running. Possible ways of dealing with this situation include implementing filesystem snapshots using the volume manager, excluding the offending directory, or suspending the process that is changing the directory. After the text "Bad index order", the error messge will indicate which files have caused the problem.

I've also heard that it may be an indication of a failing disk or partially corrupted filesystem.

I think the best approach is probably to post on the [mailing list](https://lists.nongnu.org/mailman/listinfo/rdiff-backup-users) until we can determine if it's a bug. I'll keep this issue open for a bit.

- Andy

**Comment by ericzolf** [comment]
This is a current limitation of rdiff-backup that it can't handle well files changing while they are backed-up. We can look into this but that might not be trivial and I would consider this as an enhancement.

**Comment by ottok** [comment]
Hello @honzasram!

The code base has been rewritten for Python 3 and there will be no further releases for the 1.x series in Python 2 anymore. Could you please help out and test again with the latest development version (https://github.com/rdiff-backup/rdiff-backup#installing-the-latest-development-version) if you can still reproduce this?

With your help, the upcoming 2.0.0 release could be improved and this reported issue eventually solved in future 2.x releases.

**Comment by honzasram** [comment]
Hi @ottok,

Unfortunately I abandon that solution and resolved it different way. 
Exact setup was backup server with mounted SMB disk and running locally. That way, users could easily change data during backup. Since it was order of TB, it took long time to process and users could interfere with backup process. At least that was my understanding of problem. 

Cheers.

**Comment by ericzolf** [comment]
OK, then let's close this bug as we wouldn't solve it any time soon anyway.
