### ISSUE TITLE
Make testing/resourceforktest.py work on OS/X

### ISSUE THREAD

**Issue by ericzolf** [rdiff-backup/rdiff-backup#82]
<a href="https://github.com/ericzolf"><img src="https://avatars3.githubusercontent.com/u/3105685?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ericzolf](https://github.com/ericzolf)**
_Sunday Jun 02, 2019 at 08:57 GMT_
_Originally opened as https://github.com/ericzolf/rdiff-backup/issues/28_

----

The test script can only work on OS/X hence of little interest for me personally. I can make it formally work by adding the right `skipIf/Unless` statements and fixing the most obvious flaws in the code (e.g. use absolute paths in variables, and use test files with letters in their names to avoid case sensitivity warnings), but I can't really test it, so if someone else volunteers, feel free to fix and test.

**Comment by ericzolf** [comment]
I remove this issue from the 2.0.0 milestone has nobody volunteered to take responsibility for MacOS X.

**Comment by PeterUpfold** [comment]
I'm happy to try and look at this for macOS, but contributing to this project is new for me.

It looks like `make test` will run the tests in a Docker image, so seems not to be helpful for testing this macOS-specific feature.

So, in my clone of the repo, I've uncommented the line in `tox.ini` for `coverage run testing/resourceforktest.py` and run:

`python3 -m tox -c tox.ini -e flake8`

on macOS directly, and the test seems to pass.

    % python3 -m tox -c tox.ini -e flake8                                                                          master
    GLOB sdist-make: /Users/Peter/Devel/Python3/rdiff-backup/setup.py
    flake8 inst-nodeps: /Users/Peter/Devel/Python3/rdiff-backup/.tox/.tmp/package/1/rdiff-backup-2.0.6.dev18+g71056ca.d20200816.zip
    flake8 installed: flake8==3.8.3,mccabe==0.6.1,pycodestyle==2.6.0,pyflakes==2.2.0,rdiff-backup @ file:///Users/Peter/Devel/Python3/rdiff-backup/.tox/.tmp/package/1/rdiff-backup-2.0.6.dev18%2Bg71056ca.d20200816.zip
    flake8 run-test-pre: PYTHONHASHSEED='4260428395'
    flake8 run-test: commands[0] | flake8 setup.py src testing tools
    ___________________________________________________________________ summary ___________________________________________________________________
    flake8: commands succeeded
    congratulations :)


Where should I go from here? Do you just need someone on macOS to run this test at a later point to verify there hasn't been a regression?

**Comment by ericzolf** [comment]
Aaaand, we have a winner! Welcome in the team and thanks for the offer, Peter. I'm happy to help and be patient with you if you're happy to cope with my blissful ignorance of MacOS :smile: 

OK, back to serious:

* `tox ... -e flake8` runs only the static code validation (formatting, style, etc) so none of the actual tests has run yet, especially not resourceforktest, but at least we know that Python and Tox are properly installed.
* calling `python3 -m tox -c tox.ini` optionally with `-e py3X` (X being one of 5, 6, 7 or 8) will tell you if the tests run under the given version of Python. We can then start the serious discussion from there.
* have a look at #347 - @t9t is basically doing the same exercise for Windows as you're starting for MacOS, I'm sure there is plenty you'll learn from each other even if the system pre-requisites are quite different. The approach can be very similar.
* as you progress in your understanding of developing resp. testing rdiff-backup under MacOS, it would be super-cool if you could document your learnings in a document `docs/MacOS-DEVELOP.md` (like we already have `docs/Windows-DEVELOP.md`), and provide it later on as merge request.
* I would recommend reading `docs/DEVELOP.md`. Some is specific to Linux (perhaps we should split) but most is generic and relevant to all platforms.
* pylibacl: if you tell me more about the error message, I'll do my best to help you further. In the mean time, as documented in DEVELOP.md, you need to have something like `libacl-devel` to have the necessary C-headers available. Don't ask me how to install it on MacOS.

Regarding your question about the target of the exercise: the idea would be to have the tests running, then we can introduce them in our pipeline for MacOS (like we'll introduce them for Windows), as it is [supported by Travis-CI](https://docs.travis-ci.com/user/reference/osx). After that, we need someone who is able to reproduce and troubleshoot user and pipeline issues under OSX, because I can't. I can do the actual code fixing (even though you're welcome to do it yourself) once the root cause is identified, but, even if I can help with advices, the troubleshooting itself needs hands on a MacOS system, and unless someone sponsors me one, it ain't going to happen any time.

All clear? If not, feel free to ask more specific questions.

**Comment by ericzolf** [comment]
BTW I found an old note stating "Mac OS X users need a different pyxattr module, which can be downloaded from
https://pypi.org/project/xattr/" but I don't know if it's still relevant (it's the same as under SuSE Linux, so it still exists and works).

**Comment by PeterUpfold** [comment]
`pyxattr` seems to be OK, but the build for `pylibacl` fails as follows (for each of the Python versions it would appear — here is the output for the first, Python 3.5):

    % python3 -m tox                                                                                               master
    GLOB sdist-make: /Users/Peter/Devel/Python3/rdiff-backup/setup.py
    py35 create: /Users/Peter/Devel/Python3/rdiff-backup/.tox/py35
    py35 installdeps: importlib-metadata ~= 1.0 ; python_version < "3.8", pyxattr, pylibacl, coverage
    ERROR: invocation failed (exit code 1), logfile: /Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/log/py35-1.log
    ================================================================== log start ==================================================================
    Collecting importlib-metadata~=1.0
    Using cached importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
    Collecting pyxattr
    Using cached pyxattr-0.7.1.tar.gz (30 kB)
    Collecting pylibacl
    Using cached pylibacl-0.5.4.tar.gz (37 kB)
    Collecting coverage
    Downloading coverage-5.2.1-cp35-cp35m-macosx_10_13_x86_64.whl (205 kB)
    Collecting zipp>=0.5
    Downloading zipp-1.2.0-py2.py3-none-any.whl (4.8 kB)
    Building wheels for collected packages: pyxattr, pylibacl
    Building wheel for pyxattr (setup.py): started
    Building wheel for pyxattr (setup.py): finished with status 'done'
    Created wheel for pyxattr: filename=pyxattr-0.7.1-cp35-cp35m-macosx_10_15_x86_64.whl size=19272 sha256=435b397f84c08d3dda6c1316bf5986c18469db69618291028b523ffb4cafd28e
    Stored in directory: /Users/Peter/Library/Caches/pip/wheels/c6/e6/1a/686a26aaa15f8445ba53baa17183f8dd9b4115a25495d0bfed
    Building wheel for pylibacl (setup.py): started
    Building wheel for pylibacl (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
    command: /Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/97/21m9znz12pl4r2v37nx1g2_c0000gp/T/pip-install-br8xjue7/pylibacl/setup.py'"'"'; __file__='"'"'/private/var/folders/97/21m9znz12pl4r2v37nx1g2_c0000gp/T/pip-install-br8xjue7/pylibacl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/97/21m9znz12pl4r2v37nx1g2_c0000gp/T/pip-wheel-idoc7yhc
        cwd: /private/var/folders/97/21m9znz12pl4r2v37nx1g2_c0000gp/T/pip-install-br8xjue7/pylibacl/
    Complete output (15 lines):
    running bdist_wheel
    running build
    running build_ext
    building 'posix1e' extension
    creating build
    creating build/temp.macosx-10.15-x86_64-3.5
    /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c acl.c -o build/temp.macosx-10.15-x86_64-3.5/acl.o
    acl.c:103:37: error: use of undeclared identifier 'ACL_READ'
    static acl_perm_t holder_ACL_READ = ACL_READ;
                                        ^
    acl.c:104:38: error: use of undeclared identifier 'ACL_WRITE'
    static acl_perm_t holder_ACL_WRITE = ACL_WRITE;
                                        ^
    2 errors generated.
    error: command '/usr/bin/clang' failed with exit status 1
    ----------------------------------------
    ERROR: Failed building wheel for pylibacl
    Running setup.py clean for pylibacl
    Successfully built pyxattr
    Failed to build pylibacl

Clearly I need some headers I don't have.

I think I'm right in saying that macOS supports POSIX ACLs, and there's an `acl.h` file at `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/acl.h`, but it doesn't define `ACL_READ` or `ACL_WRITE`.

A [bit of research](https://man7.org/linux/man-pages/man5/acl.5.html) suggests that `Linux-specific extensions to these functions are declared in the <acl/libacl.h> header.`, so this might explain the lack of `libacl` packages in either the  Homebrew or MacPorts repositories. I wonder if these `libacl` based tests are appropriate to try and run at all on macOS if they're for Linux-specific ACL extensions?

**Comment by ericzolf** [comment]
OK, pylibacl itself doesn't claim support for MacOS, then get rid of it for now.

I would suggest then that you take the same approach as for Windows: copy tox.ini to tox_macos.ini and do your changes there, so that it doesn't impact the Linux tests. You can even get rid of the whole coverage thingy (replace `coverage run` with `python` or `python3`, and remove all other instances of coverage), it'll make your life easier and we don't need it on all platforms (tox_win is without it).

**Comment by ericzolf** [comment]
And, last but not least, ACLs looks very different under MacOS to under Linux, so it probably couldn't work in a compatible manner: http://ahaack.net/technology/OS-X-Access-Control-Lists-ACL.html

**Comment by PeterUpfold** [comment]
Here's where I've got to:

The `testing/resourceforktest.py` test runs, albeit not successfully yet.

Initially it seemed to have issues similar to #321, so I switched over to byte strings:

https://github.com/PeterUpfold/rdiff-backup/commit/a792436064669fb783a7f781705f321432ea842f

I had to create the `testfiles` directory. It looks like this test doesn't work quite the same way as the others, which seem to be content with test files in `build/testfiles`? Perhaps this test isn't currently like the others?

Now I am here (this output just from the first Python 3.5 tests, but similar in the other versions):

    % python3 -m tox -c tox_mac.ini                                    [snip]                            
    py35 run-test: commands[0] | python3 testing/resourceforktest.py
    .ERemote schema option ignored - no remote file descriptions.
    Warning: could not determine case sensitivity of source directory at
    testfiles/resource_fork_test1
    because we can't find any files with letters in them.
    It will be treated as case sensitive.
    Remote schema option ignored - no remote file descriptions.
    Fatal Error: Source directory testfiles/empty does not exist
    ERemote schema option ignored - no remote file descriptions.
    Warning: could not determine case sensitivity of source directory at
    testfiles/resource_fork_test1
    because we can't find any files with letters in them.
    It will be treated as case sensitive.
    Remote schema option ignored - no remote file descriptions.
    Warning: could not determine case sensitivity of source directory at
    testfiles/resource_fork_test2
    because we can't find any files with letters in them.
    It will be treated as case sensitive.
    Remote schema option ignored - no remote file descriptions.
    Fatal Error: Source directory testfiles/empty does not exist
    E
    ======================================================================
    ERROR: testRecord (__main__.ResourceForkTest)
    Test reading, writing, and comparing of records with rforks
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "testing/resourceforktest.py", line 50, in testRecord
        record = metadata.RORP2Record(rp)
    AttributeError: module 'rdiff_backup.metadata' has no attribute 'RORP2Record'

    ======================================================================
    ERROR: testSeriesLocal (__main__.ResourceForkTest)
    Test backing up and restoring directories with ACLs locally
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "testing/resourceforktest.py", line 92, in testSeriesLocal
        BackupRestoreSeries(1, 1, dirlist)
    File "/Users/Peter/Devel/Python3/rdiff-backup/testing/commontest.py", line 449, in BackupRestoreSeries
        acls=compare_acls)
    File "/Users/Peter/Devel/Python3/rdiff-backup/testing/commontest.py", line 169, in InternalBackup
        Main._action_backup(rpin, rpout)
    File "/Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/lib/python3.5/site-packages/rdiff_backup/Main.py", line 433, in _action_backup
        _backup_check_dirs(rpin, rpout)
    File "/Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/lib/python3.5/site-packages/rdiff_backup/Main.py", line 492, in _backup_check_dirs
        "Source directory %s does not exist" % rpin.get_safepath())
    File "/Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/lib/python3.5/site-packages/rdiff_backup/log.py", line 206, in FatalError
        sys.exit(errlevel)
    SystemExit: 1

    ======================================================================
    ERROR: testSeriesRemote (__main__.ResourceForkTest)
    Test backing up and restoring directories with ACLs locally
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "testing/resourceforktest.py", line 103, in testSeriesRemote
        BackupRestoreSeries(1, 1, dirlist)
    File "/Users/Peter/Devel/Python3/rdiff-backup/testing/commontest.py", line 449, in BackupRestoreSeries
        acls=compare_acls)
    File "/Users/Peter/Devel/Python3/rdiff-backup/testing/commontest.py", line 169, in InternalBackup
        Main._action_backup(rpin, rpout)
    File "/Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/lib/python3.5/site-packages/rdiff_backup/Main.py", line 433, in _action_backup
        _backup_check_dirs(rpin, rpout)
    File "/Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/lib/python3.5/site-packages/rdiff_backup/Main.py", line 492, in _backup_check_dirs
        "Source directory %s does not exist" % rpin.get_safepath())
    File "/Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/lib/python3.5/site-packages/rdiff_backup/log.py", line 206, in FatalError
        sys.exit(errlevel)
    SystemExit: 1

    ----------------------------------------------------------------------
    Ran 4 tests in 0.371s

    FAILED (errors=3)
    Comparing testfiles/resource_fork_test1 and /Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/testfiles/output, hardlinks 1, eas 0, acls 0
    Comparing testfiles/resource_fork_test1 and /Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/testfiles/output, hardlinks 1, eas 0, acls 0
    Comparing testfiles/resource_fork_test2 and /Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/testfiles/output, hardlinks 1, eas 0, acls 0
    ERROR: InvocationError for command /Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/bin/python3 testing/resourceforktest.py (exited with code 1)

Spinning back a little, I wondered if I have a working environment for tests that we know should be working. I built and ran on a Linux system side-by-side, so I could be sure what _should_ be working right.

I don't think my testing environment is quite right yet, somehow.

For example, `testing/librsynctest.py`, which runs fine on my Debian 10 x86-64 system, gives me the following:

    librsync: ERROR: (rs_loadsig_s_magic) wrong magic number 0x72730147 for signature
    librsync: ERROR: (rs_job_complete) loadsig job failed: bad magic number at start of stream
    E/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py:633: ResourceWarning: unclosed file <_io.BufferedReader name=b'/Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/testfiles/new'>
    outcome.errors.clear()
    ....
    ======================================================================
    ERROR: testDelta (__main__.LibrsyncTest)
    Test delta generation by making sure rdiff can process output
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/lib/python3.5/site-packages/rdiff_backup/librsync.py", line 153, in __init__
        self.maker = _librsync.new_deltamaker(sig_string)
    _librsync.librsyncError: librsync error 104 while in delta rs_signature_t builder

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "testing/librsynctest.py", line 127, in testDelta
        df = librsync.DeltaFile(self.sig.open("rb"), self.new.open("rb"))
    File "/Users/Peter/Devel/Python3/rdiff-backup/.tox/py35/lib/python3.5/site-packages/rdiff_backup/librsync.py", line 155, in __init__
        raise librsyncError(str(e))
    rdiff_backup.librsync.librsyncError: librsync error 104 while in delta rs_signature_t builder

    ----------------------------------------------------------------------
    Ran 5 tests in 0.745s

    FAILED (errors=1)



Any ideas where I should go next? Thanks for your patience!

**Comment by ericzolf** [comment]
So, you've met multiple issues here, I see:

== Test directories

1. if you haven't yet done so, you need to have unpacked the test files from https://github.com/rdiff-backup/rdiff-backup-filesrepo in the same directory where you have cloned your Git repository. Check the readme for details.
2. The module `commontest.py` refers this directory as `old_test_dir` and an empty test directory as `abs_test_dir` (it also defines `abs_output_dir` and `abs_restore_dir` but they are less important).
3. You should always use those two variables to reference test files, `old_test_dir` is for _read-only_ access to the test files, `abs_test_dir` is to be used if you need to write things.
4. Any test module should import `commontest.py` to have access to those variables and further help functions.

== module 'rdiff_backup.metadata' has no attribute 'RORP2Record'

Yep, function has been renamed, it's now the class method `MetadataFile._object_to_record`, you need to change the test code accordingly; I don't think the function signature has changed to it should be easy.

== librsync error

That sounds tougher to solve... Perhaps it's simply because you haven't yet the testfiles, I would wait for the results of the first 2 points before continuing the analysis.

In the mean time, how did you install/compile librsync/librsync-devel and which version?

**Comment by PeterUpfold** [comment]
The test files appeared to install correctly when I ran this script the first time. Now I get:


    % tools/setup-testfiles.sh      
    Test files found, not re-installing them...

    Verify a normal user for tests exist:
    RDIFF_TEST_UID: 
    RDIFF_TEST_USER: 
    RDIFF_TEST_GROUP: 


(Perhaps I need to define those environment variables?)

And the test files appear to be there:

    % ls -lah ../rdiff-backup_testfiles                                                    
    total 8
    drwxr-xr-x    43 Peter  staff   1.3K 17 Aug 08:29 .
    drwxr-xr-x    22 Peter  staff   704B 17 Aug 08:17 ..
    drwxr-xr-x     6 Peter  staff   192B 17 Feb  2002 bigdir
    drwxr-xr-x    13 Peter  staff   416B  5 Sep  2002 corrupt_dest1
    drwxr-xr-x    13 Peter  staff   416B  5 Sep  2002 corrupt_dest2
    drwxr-xr-x     4 Peter  staff   128B 30 Apr  2002 corruptbackup
    drwxr-xr-x     3 Peter  staff    96B 30 Apr  2002 corruptbackup_source
    drwxr-xr-x     4 Peter  staff   128B  5 Sep  2002 dircomptest
    drwxr-xr-x     2 Peter  staff    64B 15 Mar  2002 empty
    drwxr-xr-x     3 Peter  staff    96B 10 May  2002 filemappingtest1
    drwxr-xr-x     4 Peter  staff   128B 10 May  2002 filemappingtest2
    [snip]

librsync is version 2.3.1 installed using the Homebrew package manager system and I've done `export LIBRSYNC_DIR=/usr/local` before running `tox`.

**Comment by ericzolf** [comment]
Sorry for the delay, I was in holiday (not sorry for this though :smirk: ).

I think something went wrong when unpacking the files, it should read `total 128` or `total 132K` instead of `total 8`, but I'm not sure how this fits with the 9 files I see. Is MacOS here having a different behaviour?

Anyway I would remove the whole directory and try again manually, noting down any strange message.

It should look as follows (assuming you start from the rdiff-backup repository):

```
cd ..
git clone git@github.com:rdiff-backup/rdiff-backup-filesrepo.git  # only if the directory rdiff-backup-filesrepo doesn't yet exist
sudo tar xf rdiff-backup-filesrepo/rdiff-backup_testfiles.tar
sudo rdiff-backup-filesrepo/rdiff-backup_testfiles.fix.sh
```

The usage of `sudo` will make sure that most files will belong to your normal user, which is generally what you want. If you want them to belong to another user, you may call instead the fix-script with explicit UID and GID:

```
sudo rdiff-backup-filesrepo/rdiff-backup_testfiles.fix.sh <UID> <GID>
```

Regarding the librsync, you need also the headers to be able to compile rdiff-backup. I don't know anything of homebrew to help much but the content of librsync-devel is the following, which you should have, or similar, under /usr/local/include:

```
/usr/include/librsync.h
/usr/include/librsync_export.h
/usr/lib64/librsync.so
```
