### ISSUE TITLE
[BUG] Failing with error "AttributeError: 'str' object has no attribute 'lstat'"

### ISSUE THREAD

**Issue by wizzardx** [rdiff-backup/rdiff-backup#850]
## Bug summary

rdiff-backup version 2.2.2 on Debian (Testing) is failing because of using a string variable incorrectly.

Over in line 1119 of rpath.py, a string variable is created:

```
tf = os.path.join(tempdir, _tf)
```

And then on line 1121, a none-existant lstat method is called against the string object:

```
if not tf.lstat():
```

This causes the following exception to be raised:

```
AttributeError: 'str' object has no attribute 'lstat'
```

## Version, Python, Operating System
Version: 2.2.2
Python: 3.11.1
Operating System: Debian Testing

How did you call rdiff-backup, with which parameters:

```
ionice -c 3 -t rdiff-backup \
    --preserve-numerical-ids \
    --exclude-other-filesystems \
    --exclude=/home/david/.cache/google-chrome \
    --force \
    --no-compression \
    -v9 \
    / /mnt/myext/home_backups/linux/files
```

Also, this path on my system:

/mnt/myext/home_backups/linux/files

Has had it's 'rdiff-backup-data' subdirectory removed, but with command-line options added so that rdiff-backup will re-create the directory.

## What happened and what did you expect?

I expect the rdiff-backup command to run for a while and then complete, like it has in the past, with minimal problems.

## More information

Here's the output (including -v9 as given in my example command-line) on my terminal:

```
WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.
2023-02-13 21:39:37.261464 +0200  <CLIENT-109177>  DEBUG: Runtime information =>{'exec': {'version': '2.2.2', 'api_version': {'default': 200, 'min': 200, 'max': 201, 'actual': 0}, 'argv': ['/usr/bin/rdiff-backup', '--preserve-numerical-ids', '--exclude-other-filesystems', '--exclude=/home/david/.cache/google-chrome', '--force', '--no-compression', '-v9', '/', '/mnt/myext/home_backups/linux/files'], 'parsed': {'api_version': None, 'current_time': None, 'force': True, 'fsync': True, 'null_separator': False, 'new': False, 'chars_to_quote': None, 'parsable_output': False, 'remote_schema': None, 'remote_tempdir': None, 'ssh_compression': True, 'tempdir': None, 'terminal_verbosity': None, 'use_compatible_timestamps': False, 'verbosity': 9, 'restrict': None, 'restrict_read_only': None, 'restrict_update_only': None, 'ssh_no_compression': False, 'create_full_path': False, 'compression': False, 'not_compressed_regexp': '(?i).*\\.(7z|aac|arj|asc|avi|bik|bz|bz2|deb|docx|flac|flv|gif|gpg|gz|jp2|jpeg|jpg|jsonlz4|lharc|lz4|lzh|lzma|lzo|m4a|m4v|mdf|mkv|mov|mozlz4|mp3|mp4|mpeg|mpg|oga|ogg|ogm|ogv|opus|pgp|pk3|png|rar|rm|rpm|rz|shn|tgz|tzst|vob|webm|webp|wma|wmv|xlsx|xz|z|zip|zoo|zst)$', 'selections': [('exclude-other-filesystems', True), ('exclude', '/home/david/.cache/google-chrome')], 'acls': True, 'carbonfile': True, 'compare_inode': True, 'eas': True, 'hard_links': True, 'resource_forks': True, 'never_drop_acls': False, 'group_mapping_file': None, 'preserve_numerical_ids': True, 'user_mapping_file': None, 'file_statistics': True, 'print_statistics': False, 'allow_duplicate_timestamps': False, 'restrict_path': None, 'restrict_mode': 'read-write', 'action': 'backup', 'compare_at_time': None, 'compare_hash_at_time': None, 'compare_full_at_time': None, 'list_at_time': None, 'list_changed_since': None, 'remove_older_than': None, 'restore_as_of': None, 'verify_at_time': None, 'locations': ['/', '/mnt/myext/home_backups/linux/files']}}, 'python': {'name': 'cpython', 'executable': '/usr/bin/python3', 'version': '3.11.1'}, 'system': {'platform': 'Linux-6.1.0-2-amd64-x86_64-with-glibc2.36', 'fs_encoding': 'utf-8'}}<=
2023-02-13 21:39:37.263184 +0200  <CLIENT-109177>  * Using repository '/mnt/myext/home_backups/linux/files'
2023-02-13 21:39:37.263285 +0200  <CLIENT-109177>  WARNING: Target path '/mnt/myext/home_backups/linux/files' does not look like a rdiff-backup repository but will be force overwritten
2023-02-13 21:39:37.263776 +0200  <CLIENT-109177>  DEBUG: Making directory /mnt/myext/home_backups/linux/files/rdiff-backup-data
2023-02-13 21:39:37.263917 +0200  <CLIENT-109177>  DEBUG: Making directory /mnt/myext/home_backups/linux/files/rdiff-backup-data/increments
2023-02-13 21:39:37.264248 +0200  <CLIENT-109177>  * Unable to import win32security module. Windows ACLs not supported by filesystem at path /
2023-02-13 21:39:37.265134 +0200  <CLIENT-109177>  * Could not determine if source directory / permits trailing spaces or periods in filenames because we can't find any files with trailing dot/period. It will be treated as permitting such files, but none will exist if it doesn't, so it doesn't really matter and is harmless
2023-02-13 21:39:37.265225 +0200  <CLIENT-109177>  * -----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
2023-02-13 21:39:37.265340 +0200  <CLIENT-109177>  * Cleaning up
Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 33, in <module>
    sys.exit(load_entry_point('rdiff-backup==2.2.2', 'console_scripts', 'rdiff-backup')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/rdiffbackup/run.py", line 37, in main
    sys.exit(main_run(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/rdiffbackup/run.py", line 99, in main_run
    ret_val |= conn_act.setup()
               ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/rdiffbackup/actions/backup.py", line 112, in setup
    self.repo.base_dir.conn.fs_abilities.backup_set_globals(
  File "/usr/lib/python3/dist-packages/rdiff_backup/fs_abilities.py", line 1078, in backup_set_globals
    dest_fsa = FSAbilities('destination', Globals.rbdir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/rdiff_backup/fs_abilities.py", line 72, in __init__
    self._init_readwrite()
  File "/usr/lib/python3/dist-packages/rdiff_backup/fs_abilities.py", line 159, in _init_readwrite
    subdir = self.root_rp.get_temp_rpath()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1121, in get_temp_rpath
    if not tf.lstat():
           ^^^^^^^^
AttributeError: 'str' object has no attribute 'lstat'
```

**Comment by ericzolf** [comment]
Congratulation, you've discovered a two years old bug! This said, it appears only when the target file system is full, so you have another issue.
