### ISSUE TITLE
backup failed by "PermissionError: [WinError 5] Access is denied: b'W:/.WDSyncHistory/.WD Hidden Files'"

### ISSUE THREAD

**Issue by aisnote** [rdiff-backup/rdiff-backup#855]
## Bug summary

rdiff-backup.exe --force  -v5 --print-statistics D:/imagebk W:/
failed by access denied on hidden files.

## Version, Python, Operating System
```yaml
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - *****/rdiff-backup/rdiff-backup.exe
  - info
  parsed: null
  version: 2.2.3
python:
  executable: *****\rdiff-backup\rdiff-backup.exe
  name: cpython
  version: 3.10.7
system:
  fs_encoding: utf-8
  platform: Windows-10-10.0.22000-SP0
```

## rdiff-backup call
```
rdiff-backup.exe --force  -v5 --print-statistics D:/imagebk W:/
```

## What happened and what did you expect?

copy the folder from D:/imagebk to W:/

## More information

```
WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.
* Using repository 'W:/'
WARNING: Target path 'W:/' does not look like a rdiff-backup repository but will be force overwritten
* Hardlinks disabled by default on Windows
* Unable to import module (py)xattr. Extended attributes not supported on filesystem at path D:/imagebk
* Unable to import module posix1e from pylibacl package. POSIX ACLs not supported on filesystem at path D:/imagebk
* -----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         Off
  Extended attributes                          Off
  Windows access control lists                 On
  Case sensitivity                             Off
  Escape DOS devices                           On
  Escape trailing spaces                       On
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
* Directories on file system at path W:/rdiff-backup-data/rdiff-backup.tmp.0 are not fsyncable. Assuming it's unnecessary.
* Unable to import module (py)xattr. Extended attributes not supported on filesystem at path W:/rdiff-backup-data/rdiff-backup.tmp.0
* Unable to import module posix1e from pylibacl package. POSIX ACLs not supported on filesystem at path W:/rdiff-backup-data/rdiff-backup.tmp.0
* -----------------------------------------------------------------
Detected abilities for destination (read/write) file system:
  Ownership changing                           Off
  Hard linking                                 On
  fsync() directories                          Off
  Directory inc permissions                    Off
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   On
  Access control lists                         Off
  Extended attributes                          Off
  Windows access control lists                 On
  Case sensitivity                             Off
  Escape DOS devices                           On
  Escape trailing spaces                       On
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
* Backup: escape_dos_devices = False
* Backup: escape_trailing_spaces = False
* Enabled use_compatible_timestamps
NOTE: Symbolic links excluded by default on Windows
* Given repository doesn't need to be regressed
NOTE: Starting mirror from source path D:/imagebk to destination path W:/
* Processing file .
* Processing file .WDSyncHistory
* Processing file .WDSyncHistory/.WD Hidden Files
* Processing file Garbage Dispenser2.mp4
* Cleaning up
Traceback (most recent call last):
  File "rdiffbackup\run.py", line 170, in <module>
  File "rdiffbackup\run.py", line 37, in main
  File "rdiffbackup\run.py", line 105, in main_run
  File "rdiffbackup\actions\backup.py", line 159, in run
  File "rdiff_backup\backup.py", line 39, in mirror_compat200
  File "rdiff_backup\backup.py", line 197, in patch
  File "rdiff_backup\rorpiter.py", line 142, in __call__
  File "rdiff_backup\rorpiter.py", line 179, in _finish_branches
  File "rdiff_backup\backup.py", line 641, in end_process_directory
  File "rdiff_backup\rpath.py", line 807, in rmdir
PermissionError: [WinError 5] Access is denied: b'W:/.WDSyncHistory/.WD Hidden Files'
[16948] Failed to execute script 'run' due to unhandled exception!
```

**Comment by ericzolf** [comment]
Were the three files listed before the "cleaning up" message existing on W: before you started the first backup?  What does `dir /s w:` show? You're aware that you're going to lose everything previously present on this drive?

**Comment by aisnote** [comment]
what do you mean? 
The 2 of 3 files are not actually files. They are dot and one folder begin with dot

**Comment by ericzolf** [comment]
You want to be picky about words or get some help?

**Comment by aisnote** [comment]
Definitely, I want to get help. 
 The W:\ disk is map from network disk. And I do did some backup before. But now I just want to copy from  **D:/imagebk to  W:/**, and meet the issue as I posted.

![image](https://user-images.githubusercontent.com/1201634/220989753-a6ceb78a-86fd-438c-bbe7-aea6e5a1115d.png)


There is one hidden folder:

![image](https://user-images.githubusercontent.com/1201634/220989861-c6128d30-924b-4650-b476-4f4556f4c502.png)


Could you help to check?  thanks.

**Comment by ericzolf** [comment]
The issue is that rdiff-backup expects the target directory to it alone. A system directory like this `.WD...` directory can only create issues. Either remove it or backup to some sub- directory of W:.

At this stage, I don't see any other short term solution. Longer term would be the implementation of #790 or a new enhancement to simply ignore certain files.

**Comment by aisnote** [comment]
thanks for your information.👍
