### ISSUE TITLE
[BUG] Fail gracefully when connection(s) can't be setup e.g. due to network error

### ISSUE THREAD

**Issue by frankcrawford** [rdiff-backup/rdiff-backup#868]
## Bug summary

[abrt] rdiff-backup: __init__(): repository.py:70:__init__:AttributeError: 'NoneType' object has no attribute 'append_path'

## Version, Python, Operating System

This report is from Fedora Bugzilla Bug 2188385 (see https://bugzilla.redhat.com/show_bug.cgi?id=2188385)

```
Version-Release number of selected component:
rdiff-backup-2.2.4-2.fc38

Additional info:
reporter:       libreport-2.17.9
cmdline:        /usr/bin/python3 /bin/rdiff-backup --new backup /etc [backup@taster.fl.shaftnet.org](mailto:backup@taster.fl.shaftnet.org)::flapjack/etc
exception_type: AttributeError
type:           Python3
interpreter:    python3-3.11.2-1.fc38.x86_64
cgroup:         0::/system.slice/crond.service
runlevel:       N 5
package:        rdiff-backup-2.2.4-2.fc38
executable:     /bin/rdiff-backup
kernel:         6.2.11-300.fc38.x86_64
reason:         repository.py:70:__init__:AttributeError: 'NoneType' object has no attribute 'append_path'
crash_function: __init__
uid:            0
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

```
/usr/bin/python3 /bin/rdiff-backup --new backup /etc backup@taster.fl.shaftnet.org::flapjack/etc
```

## What happened and what did you expect?

```
Truncated backtrace:
repository.py:70:__init__:AttributeError: 'NoneType' object has no attribute 'append_path'

Traceback (most recent call last):
  File "/bin/rdiff-backup", line 33, in <module>
    sys.exit(load_entry_point('rdiff-backup==2.2.4', 'console_scripts', 'rdiff-backup')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/run.py", line 37, in main
    sys.exit(main_run(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/run.py", line 85, in main_run
    with action.connect() as conn_act:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/actions/backup.py", line 63, in connect
    self.repo = repository.Repo(
                ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/locations/repository.py", line 70, in __init__
    self.data_dir = self.base_dir.append_path(b"rdiff-backup-data")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append_path'

Local variables in innermost frame:
self: <rdiffbackup.locations.repository.Repo object at 0x7fa92a13d250>
base_dir: None
force: False
must_be_writable: True
must_exist: False
create_full_path: False
can_be_sub_path: False
__class__: <class 'rdiffbackup.locations.repository.Repo'>
```

## More information

This occurred after upgrading the client to Fedora 38, while the server is Fedora 37.  However, following runs seem to have worked.

I suspect a network issue, but just looking for any other ideas why this may have occurred, and/or what we should look at.

**Comment by ericzolf** [comment]
Without the whole backtrace, it's a bit difficult, but could it be that the backup was called _while_ the update took place and there was a mix of libraries?

**Comment by ericzolf** [comment]
Actually, it might very much have been a network issue, I did a very simple test and get the following error:

```
$ rdiff-backup backup . doesnotexist::/tmp/bak
ssh: Could not resolve hostname doesnotexist: Name or service not known
ERROR: Couldn't start up the remote connection by executing 'ssh -C doesnotexist rdiff-backup --terminal-verbosity 3 --server'
due to exception 'Truncated header <b''> (problem probably originated remotely)'.

Remember that, under the default settings, rdiff-backup must be
installed in the PATH on the remote system.  See the man page for more
information on this.  This message may also be displayed if the remote
version of rdiff-backup is quite different from the local version (2.2.4)

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 33, in <module>
    sys.exit(load_entry_point('rdiff-backup==2.2.4', 'console_scripts', 'rdiff-backup')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/run.py", line 37, in main
    sys.exit(main_run(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/run.py", line 85, in main_run
    with action.connect() as conn_act:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/actions/backup.py", line 63, in connect
    self.repo = repository.Repo(
                ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/locations/repository.py", line 70, in __init__
    self.data_dir = self.base_dir.append_path(b"rdiff-backup-data")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append_path'
```

Still, I don't quite understand the final traceback and we should get rid of it to fail more gracefully, but that should be simple enough.

**Comment by frankcrawford** [comment]
Eric, thanks for that.

Backups appear to now be running fine and the submitter is happy to close the issue.  He feels similar to you that that the only change would be to trap the message and handle it more gracefully.

**Comment by ericzolf** [comment]
I already have a fix, just need to fine tune and add a test.
