### ISSUE TITLE
[BUG] local 2.0.5 can not backup remote host running 2.2.4

### ISSUE THREAD

**Issue by HRio** [rdiff-backup/rdiff-backup#872]
## Bug summary

rdiff-backup `2.0.5` fails to backup remote host with `2.2.4` using safekeep (https://github.com/dimipaun/safekeep)

## Version, Python, Operating System

local
```
2023-05-02 10:14:10.025983 +0200  <CLIENT-26136>  Fatal Error: No
arguments given
See the rdiff-backup manual page for more information.
2023-05-02 10:14:10.022639 +0200  <CLIENT-26136>  Using rdiff-backup
version 2.0.5
2023-05-02 10:14:10.022691 +0200  <CLIENT-26136>        with cpython
/usr/bin/python3 version 3.9.16
2023-05-02 10:14:10.025910 +0200  <CLIENT-26136>        on Linux-
5.15.106-0-virt-x86_64-with, fs encoding utf-8
```
remote
```yaml
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.4
python:
  executable: /usr/bin/python3
  name: cpython
  version: 3.11.3
system:
  fs_encoding: utf-8
  platform: Linux-6.1.27-0-virt-x86_64-with
```

## rdiff-backup call

How did you call rdiff-backup, with which parameters:

From safekeep dbg log
```
DBG: Run [nice -n10 ionice -c3 -t rdiff-backup --remote-schema ssh -
oStrictHostKeyChecking=yes -vvv -i /var/lib/safekeep/.ssh/safekeep-
server-data-key %s rdiff-backup --server --exclude-sockets --exclude-
fifos --include /etc --include /home --include /root --include /srv --
include /usr/local --include /var/lib --include /var/log --include
/var/spool/cron --exclude-regexp /.* root@MASKED::/
/var/lib/safekeep/MASKED] 
```

## What happened and what did you expect?

Backup fails immediately with `Exception ''restrict_path'' raised of class '<class 'KeyError'>'`

## More information

Error log from `safekeep`

```
INFO: WARNING: this command line interface is deprecated and will
disappear, start using the new one as described with '--new --help'.
INFO: Warning: Local version 2.0.5 does not match remote version 2.2.4.
INFO: Exception ''restrict_path'' raised of class '<class 'KeyError'>':
INFO:   File "/usr/lib/python3.9/site-packages/rdiff_backup/Main.py",
line 395, in error_check_Main
INFO:     Main(arglist)
INFO:   File "/usr/lib/python3.9/site-packages/rdiff_backup/Main.py",
line 415, in Main
INFO:     final_set_action(rps)
INFO:   File "/usr/lib/python3.9/site-packages/rdiff_backup/Main.py",
line 301, in final_set_action
INFO:     if restore_set_root(rps[0]):
INFO:   File "/usr/lib/python3.9/site-packages/rdiff_backup/Main.py",
line 855, in restore_set_root
INFO:     if parent_dir.path == rpin.conn.Globals.get('restrict_path'):
INFO:   File "/usr/lib/python3.9/site-
packages/rdiff_backup/connection.py", line 526, in __call__
INFO:     return self.connection.reval(*(self.name, ) + args)
INFO:   File "/usr/lib/python3.9/site-
packages/rdiff_backup/connection.py", line 439, in reval
INFO:     raise result
INFO: 
INFO: Traceback (most recent call last):
INFO:   File "/usr/bin/rdiff-backup", line 32, in <module>
INFO:     rdiff_backup.Main.error_check_Main(sys.argv[1:])
INFO:   File "/usr/lib/python3.9/site-packages/rdiff_backup/Main.py",
line 395, in error_check_Main
INFO:     Main(arglist)
INFO:   File "/usr/lib/python3.9/site-packages/rdiff_backup/Main.py",
line 415, in Main
INFO:     final_set_action(rps)
INFO:   File "/usr/lib/python3.9/site-packages/rdiff_backup/Main.py",
line 301, in final_set_action
INFO:     if restore_set_root(rps[0]):
INFO:   File "/usr/lib/python3.9/site-packages/rdiff_backup/Main.py",
line 855, in restore_set_root
INFO:     if parent_dir.path == rpin.conn.Globals.get('restrict_path'):
INFO:   File "/usr/lib/python3.9/site-
packages/rdiff_backup/connection.py", line 526, in __call__
INFO:     return self.connection.reval(*(self.name, ) + args)
INFO:   File "/usr/lib/python3.9/site-
packages/rdiff_backup/connection.py", line 439, in reval
INFO:     raise result
INFO: KeyError: 'restrict_path'
INFO: Traceback (most recent call last):
INFO:   File "/usr/bin/rdiff-backup", line 33, in <module>
INFO:     sys.exit(load_entry_point('rdiff-backup==2.2.4',
'console_scripts', 'rdiff-backup')())
INFO:             
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^
INFO:   File "/usr/lib/python3.11/site-packages/rdiffbackup/run.py",
line 37, in main
INFO:     sys.exit(main_run(sys.argv[1:]))
INFO:              ^^^^^^^^^^^^^^^^^^^^^^
INFO:   File "/usr/lib/python3.11/site-packages/rdiffbackup/run.py",
line 105, in main_run
INFO:     ret_val |= conn_act.run()
INFO:                ^^^^^^^^^^^^^^
INFO:   File "/usr/lib/python3.11/site-
packages/rdiffbackup/actions/server.py", line 66, in run
INFO:     sys.stdout.buffer).Server()
INFO:                        ^^^^^^^^
INFO:   File "/usr/lib/python3.11/site-
packages/rdiff_backup/connection.py", line 416, in Server
INFO:     self._get_response(-1)
INFO:   File "/usr/lib/python3.11/site-
packages/rdiff_backup/connection.py", line 484, in _get_response
INFO:     req_num, object = self._get()
INFO:                       ^^^^^^^^^^^
INFO:   File "/usr/lib/python3.11/site-
packages/rdiff_backup/connection.py", line 298, in _get
INFO:     raise ConnectionReadError(
INFO: rdiff_backup.connection.ConnectionReadError: Truncated header
<b''> (problem probably originated remotely)
ERR: nice failed: exited with non zero status: 1
```

**Comment by ericzolf** [comment]
if you edit the code on the 2.2.4 side it should fix the issue and I could more quickly provide a final fix:
rdiff_backup/Security.py: modify
`_restrict_path = rp.normalize().path` => `Globals.restrict_path = _restrict_path = rp.normalize().path`
rdiff_backup/Globals.py: add
`restrict_path = None`

**Comment by HRio** [comment]
thanks, applying this diff to `2.2.4` makes the backup work
```diff
--- a/Globals.py
+++ b/Globals.py
@@ -291,6 +291,7 @@
 # Protocol 4 is understood since Python 3.4, protocol 5 since 3.8.
 PICKLE_PROTOCOL = 4
 
+restrict_path = None
 
 # @API(get, 200)
 def get(name):
--- a/Security.py
+++ b/Security.py
@@ -113,7 +113,7 @@
     assert rp.conn is Globals.local_connection, (
         "Function works locally not over '{conn}'.".format(conn=rp.conn))
     global _restrict_path, _restrict_path_list
-    _restrict_path = rp.normalize().path
+    Globals.restrict_path = _restrict_path = rp.normalize().path
     _restrict_path_list = _restrict_path.split(b"/")
```

**Comment by ericzolf** [comment]
> For people finding this. got it working like this
> 
> ```
> apt remove rdiff-backup
> apt install python3-pip librsync-dev
> pip install --break-system-packages rdiff-backup
> ```

I would not recommend this solution,  it can work,  but it can also break your system python. https://rdiff-backup.net/migration.html#side_by_side_installation is for 1.x but can be adapted for other means.
