### ISSUE TITLE
[BUG] Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by frankcrawford** [rdiff-backup/rdiff-backup#900]
## Bug summary

[abrt] rdiff-backup: Collate2Iters(): gzip.py:518:read:EOFError: Compressed file ended before the end-of-stream marker was reached

## Version, Python, Operating System

This report is from Fedora Bugzilla Bug 2219479 (see https://bugzilla.redhat.com/show_bug.cgi?id=2219479)

```
Version-Release number of selected component:
rdiff-backup-2.2.5-2.fc38

Additional info:
reporter:       libreport-2.17.10
cgroup:         0::/user.slice/user-13013.slice/[user@13013.service](mailto:user@13013.service)/app.slice/mytmux.service
exception_type: StopIteration
package:        rdiff-backup-2.2.5-2.fc38
crash_function: Collate2Iters
type:           Python3
interpreter:    python3-3.11.4-1.fc38.i686
executable:     /usr/bin/rdiff-backup
reason:         gzip.py:518:read:EOFError: Compressed file ended before the end-of-stream marker was reached
runlevel:       N 5
kernel:         6.3.8-200.fc38.x86_64
```

## rdiff-backup call

NA

## What happened and what did you expect?

```
Truncated backtrace:
gzip.py:518:read:EOFError: Compressed file ended before the end-of-stream marker was reached

Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/rdiff_backup/rorpiter.py", line 364, in Collate2Iters
    relem2 = next(riter2)
             ^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 33, in <module>
    sys.exit(load_entry_point('rdiff-backup==2.2.5', 'console_scripts', 'rdiff-backup')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/run.py", line 37, in main
    sys.exit(main_run(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/run.py", line 110, in main_run
    ret_val |= conn_act.run()
               ^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/actions/verify.py", line 100, in run
    return self.repo.base_dir.conn.compare.Verify(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiff_backup/compare.py", line 218, in Verify
    for repo_rorp in repo_iter:
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/meta/ea.py", line 248, in join_iter
    for rorp, ea in rorpiter.CollateIterators(rorp_iter, ea_iter):
  File "/usr/lib64/python3.11/site-packages/rdiff_backup/rorpiter.py", line 354, in Collate2Iters
    relem1 = next(riter1)
             ^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/meta/acl_posix.py", line 301, in join_iter
    for rorp, acl in rorpiter.CollateIterators(rorp_iter, acl_iter):
  File "/usr/lib64/python3.11/site-packages/rdiff_backup/rorpiter.py", line 368, in Collate2Iters
    for relem1 in riter1:
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/meta/__init__.py", line 61, in iterate
    for record in self._iterate_records():
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/meta/__init__.py", line 75, in _iterate_records
    next_pos = self._get_next_pos()
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/rdiffbackup/meta/__init__.py", line 139, in _get_next_pos
    newbuf = self.fileobj.read(self.blocksize)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/gzip.py", line 301, in read
    return self._buffer.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/gzip.py", line 518, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

Local variables in innermost frame:
self: <gzip._GzipReader object at 0x7f15fd7d6e90>
size: 24576
buf: b''
uncompress: b''
```

## More information

There was a problem with a backup in progress, FS was marked ro, but backup didn't terminate.  I rebooted and ran
verify. That produced this exception quite quickly.

**Comment by ericzolf** [comment]
It's a difficult one and I don't have a good answer: rdiff-backup can't recover from a corrupt compressed file. You could try to remove it and see if rdiff-backup can then successfully regress. But no guarantee that it'll work.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ikus060** [comment]
@frankcrawford 

You should regress your backup. Rdiff-backup should do it on it own if you run the backup process again.

**Comment by ericzolf** [comment]
Do you need more help or can I close?

**Comment by ericzolf** [comment]
I close, feel free to re-open if there is more to it.
