### ISSUE TITLE
Understanding permission error[?] 

### ISSUE THREAD

**Issue by exuvo** [rdiff-backup/rdiff-backup#933]
## What is it about?

I recreated my destination server backup directory on a different filesystem (zfs instead of btrfs) but i am now getting a permission error after a few hours of backup (600GB written) so it clearly has write permissions.
What operation is it trying to do here that is failing? What permission is it lacking?

## Version, Python, Operating System

Client:
```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.5
python:
  executable: /usr/bin/python
  name: cpython
  version: 3.11.5
system:
  fs_encoding: utf-8
  platform: Linux-6.5.7-zen1-1-zen-x86_64-with-glibc2.38
...
```
Server
```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.5
python:
  executable: /usr/bin/python
  name: cpython
  version: 3.11.5
system:
  fs_encoding: utf-8
  platform: Linux-6.1.50-1-lts-x86_64-with-glibc2.38
...
```
ZFS filesystem has acltype=posixacl xattr=sa, so i dont think it is an acl error.
/backup is a symlink to /yuki/priv/backup
User backup has group rx on /yuki and /yuki/priv.
User backup has group rwx on /yuki/priv/backup, /yuki/priv/backup/exuv-desktop and /yuki/priv/backup/exuv-desktop/root.

## rdiff-backup call

If you tried something already, how did you call rdiff-backup, with which parameters:

```
rdiff-backup --remote-schema "ssh -c aes128-ctr %s rdiff-backup --server" backup --exclude-device-files --exclude-fifos --exclude-sockets --exclude-other-filesystems --exclude /dev --exclude /proc --exclude /sys --exclude /tmp --exclude /mnt --exclude "/home/exuvo/games/" --exclude "/home/exuvo/.cache/" / m::/backup/exuvo-desktop/root
```
ssh config selects user backup.

Server ssh_authorised as user backup
`command="rdiff-backup server --restrict-path /backup/exuvo-desktop",no-port-forwarding,no-X11-forwarding,no-pty`

And what was the result?

```
Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/run.py", line 37, in main
    sys.exit(main_run(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/run.py", line 110, in main_run
    ret_val |= conn_act.run()
               ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/actions/backup.py", line 159, in run
    backup.mirror_compat200(
  File "/usr/lib/python3.11/site-packages/rdiff_backup/backup.py", line 39, in mirror_compat200
    DestS.patch(dest_rpath, source_diffiter)
  File "/usr/lib/python3.11/site-packages/rdiff_backup/connection.py", line 579, in __call__
    return self.connection.reval(*(self.call_name, ) + args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiff_backup/connection.py", line 434, in reval
    raise result
PermissionError: [Errno 1] Operation not permitted: b'/backup/exuvo-desktop/root'
```

**Comment by exuvo** [comment]
Oh it needs user permissions as it wants to change it to 755.
