### ISSUE TITLE
[?] Is backup to a samba share supported?

### ISSUE THREAD

**Issue by fantauzzi** [rdiff-backup/rdiff-backup#955]
## What is it about?

Backup from Ext4 file system to NTFS file system **mounted via samba** fails with error `Extended attributes not supported`

## Version, Python, Operating System
```
⮕ rdiff-backup --version
rdiff-backup 2.0.5
```

```
⮕ python --version
Python 3.11.3
```
```
⮕ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

Call `rdiff-backup info` and replace the following line with the output,
repeat for each environment impacted, especially if using remote operations:

```yaml
Fatal Error: Switches missing or wrong number of arguments
See the rdiff-backup manual page for more information.
```

## rdiff-backup call

If you tried something already, how did you call rdiff-backup, with which parameters:

```
-v5 /home/fanta/workspace /media/fanta/wd/rdiff_backup/
```

And what was the result?

```
Extended attributes not supported by filesystem at /media/fanta/wd/rdiff_backup/rdiff-backup-data/rdiff-backup.tmp.0
```

I am trying to use rdiff-backup to backup a directory in an Ext4 file system to a NFS mounted via samba. The NFS disk is formatted as NTFS (as I also use it with Windows), and is mounted with this command:

```sudo mount -t cifs -o username=fanta,uid=fanta,gid=fanta //mycloudex2ultra/public /media/fanta/wd```

Here below the command I run and its output. Note that if I instead use a local directory (Ext4) as the target, the backup completes successfully. Issue seems related to having a target directory on a file system mounted with samba. 

```
⮕ rdiff-backup -v5 /home/fanta/workspace /media/fanta/wd/rdiff_backup/
Using rdiff-backup version 2.0.5
	with cpython /usr/bin/python3 version 3.10.12
	on Linux-6.2.0-37-generic-x86_64-with-glibc2.35, fs encoding utf-8
Unable to import win32security module. Windows ACLs
not supported by filesystem at /home/fanta/workspace
-----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Extended attributes not supported by filesystem at /media/fanta/wd/rdiff_backup/rdiff-backup-data/rdiff-backup.tmp.1
Found interrupted initial backup. Removing...
Exception '[Errno 2] No such file or directory: 'A'' raised of class '<class 'FileNotFoundError'>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 417, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 353, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 429, in Backup
    rpout.conn.fs_abilities.backup_set_globals(rpin, force)
  File "/usr/lib/python3/dist-packages/rdiff_backup/fs_abilities.py", line 1051, in backup_set_globals
    dest_fsa = FSAbilities('destination').init_readwrite(Globals.rbdir)
  File "/usr/lib/python3/dist-packages/rdiff_backup/fs_abilities.py", line 174, in init_readwrite
    subdir.delete()
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1313, in delete
    self.conn.shutil.rmtree(self.path)
  File "/usr/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)

POSIX ACLs not supported by filesystem at /media/fanta/wd/rdiff_backup/rdiff-backup-data/rdiff-backup.tmp.1
Unable to import win32security module. Windows ACLs
not supported by filesystem at /media/fanta/wd/rdiff_backup/rdiff-backup-data/rdiff-backup.tmp.1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1309, in delete
    self.rmdir()
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1222, in rmdir
    self.conn.os.rmdir(self.path)
OSError: [Errno 39] Directory not empty: b'/media/fanta/wd/rdiff_backup/rdiff-backup-data/rdiff-backup.tmp.1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 395, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 417, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 353, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 429, in Backup
    rpout.conn.fs_abilities.backup_set_globals(rpin, force)
  File "/usr/lib/python3/dist-packages/rdiff_backup/fs_abilities.py", line 1051, in backup_set_globals
    dest_fsa = FSAbilities('destination').init_readwrite(Globals.rbdir)
  File "/usr/lib/python3/dist-packages/rdiff_backup/fs_abilities.py", line 174, in init_readwrite
    subdir.delete()
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1313, in delete
    self.conn.shutil.rmtree(self.path)
  File "/usr/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'A'
```

**Comment by ericzolf** [comment]
Few comments before I close this issue, in case someone comes back to it:
1. rdiff-backup can normally handle the fact that the target file system is case insensitive even though the source file system is case sensitive,
2. this said, a network file system on top of top of such an exotic (for Linux) file system has already been reported to cause issues.
3. and yes, FUSE file systems have repeatedly been reported to cause issues. Those drivers generally don't seem to be as stable or feature complete as normal file system drivers. Speed BTW is also an issue.
