### ISSUE TITLE
Test suite fails out of the box

### ISSUE THREAD

**Issue by ottok** [rdiff-backup/rdiff-backup#97]
I am unable to get the Tox test suite passing. What step am I missing? Is are the tests really broken? Please help @ericzolf 

```
root@d7ab342f33a1:/build# tox -e py37
GLOB sdist-make: /build/setup.py
py37 inst-nodeps: /build/.tox/.tmp/package/1/rdiff-backup-1.3.4.zip
py37 installed: pkg-resources==0.0.0,pylibacl==0.5.3,pyxattr==0.6.1,rdiff-backup==1.3.4
py37 run-test-pre: PYTHONHASHSEED='1263765405'
py37 run-test-pre: commands[0] | python testing/commontest.py
py37 runtests: commands[0] | python testing/ctest.py
.....
----------------------------------------------------------------------
Ran 5 tests in 0.168s

OK
py37 runtests: commands[1] | python testing/timetest.py
...........
----------------------------------------------------------------------
Ran 11 tests in 2.109s

OK
py37 runtests: commands[2] | python testing/librsynctest.py
librsync: ERROR: (rs_file_open) File exists "/build/.tox/py37/testfiles/new2", aborting!
Flibrsync: ERROR: (rs_file_open) File exists "/build/.tox/py37/testfiles/signature", aborting!
Flibrsync: ERROR: (rs_file_open) File exists "/build/.tox/py37/testfiles/signature", aborting!
Flibrsync: ERROR: (rs_file_open) File exists "/build/.tox/py37/testfiles/signature", aborting!
F.
======================================================================
FAIL: testDelta (__main__.LibrsyncTest)
Test delta generation by making sure rdiff can process output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/librsynctest.py", line 120, in testDelta
    self.new2.path))
AssertionError

======================================================================
FAIL: testPatch (__main__.LibrsyncTest)
Test patching against Rdiff
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/librsynctest.py", line 135, in testPatch
    (self.basis.path, self.sig.path))
AssertionError

======================================================================
FAIL: testSigFile (__main__.LibrsyncTest)
Make sure SigFile generates same data as rdiff, blocksize 512
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/librsynctest.py", line 49, in testSigFile
    self.sig_file_test_helper(512, 5)
  File "testing/librsynctest.py", line 36, in sig_file_test_helper
    (blocksize, self.basis.path, self.sig.path))
AssertionError

======================================================================
FAIL: testSigFile2 (__main__.LibrsyncTest)
Test SigFile like above, but try various blocksize
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/librsynctest.py", line 53, in testSigFile2
    self.sig_file_test_helper(2048, 1, 60000)
  File "testing/librsynctest.py", line 36, in sig_file_test_helper
    (blocksize, self.basis.path, self.sig.path))
AssertionError

----------------------------------------------------------------------
Ran 5 tests in 0.028s

FAILED (failures=4)
ERROR: InvocationError for command '/build/.tox/py37/bin/python testing/librsynctest.py' (exited with code 1)
_____________________________________________________________________________________________________ summary _____________________________________________________________________________________________________
ERROR:   py37: commands failed
```

I am using steps and environment defined in https://github.com/rdiff-backup/rdiff-backup/pull/94

**Comment by ottok** [comment]
Status with current master:
```
py37 runtests: commands[3] | python testing/statisticstest.py
Remote schema option ignored - no remote file descriptions.
Fatal Error: Source directory /build_testfiles/stattest1 does not exist
E.......
======================================================================
ERROR: testStatistics (__main__.IncStatTest)
Test the writing of statistics
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/statisticstest.py", line 182, in testStatistics
    InternalBackup(1, 1, os.path.join(old_test_dir, b"stattest1"), abs_output_dir)
  File "/build/testing/commontest.py", line 140, in InternalBackup
    Main.Backup(rpin, rpout)
  File "/build/.tox/py37/lib/python3.7/site-packages/rdiff_backup/Main.py", line 333, in Backup
    backup_check_dirs(rpin, rpout)
  File "/build/.tox/py37/lib/python3.7/site-packages/rdiff_backup/Main.py", line 383, in backup_check_dirs
    Log.FatalError("Source directory %s does not exist" % rpin.get_safepath())
  File "/build/.tox/py37/lib/python3.7/site-packages/rdiff_backup/log.py", line 171, in FatalError
    sys.exit(errlevel)
SystemExit: 1

----------------------------------------------------------------------
Ran 8 tests in 0.006s
```

**Comment by ericzolf** [comment]
I'm on my tablet but I guess that I did the equivalent of `${PWD}_testfiles` instead of `../rdiff-backup_testfiles` , and as your directory isn't called `rdiff-backup` it fails. The fix should be easy.

**Comment by ottok** [comment]
The reason I created #94 is that there should be an example of exact steps how to build and run test suite, so that any random contributor is capable of making small changes, building and testing them.

All steps are not fully automated yet (they are just as inline comments) but I will work on that once I figure out to get the Tox test run pass.
