### ISSUE TITLE
[BUG]  crash on date in the distant future

### ISSUE THREAD

**Issue by tomascharvat** [rdiff-backup/rdiff-backup#975]
## Bug summary

REPLACE THIS LINE - A clear and concise description of what the bug is
rdiffbackup always crash on file around this Modify time

Access: 2024-01-11 22:58:42.166940251 +0100
Modify: 2446-05-11 00:38:55.000000000 +0200
Change: 2024-01-09 15:01:05.060563875 +0100
 Birth: 2024-01-09 15:01:05.050563875 +0100

## Version, Python, Operating System

exec:
  api_version:
    actual: 0
    default: 201
    max: 201
    min: 201
  argv:
  - /usr/lib/python-exec/python3.11/rdiff-backup
  - info
  parsed: null
  version: 2.6.1.dev1+g1cdf7d3.d20240113
python:
  executable: /usr/bin/python3.11
  name: cpython
  version: 3.11.7
system:
  fs_encoding: utf-8
  platform: Linux-6.6.10-gentoo-x86_64-x86_64-AMD_EPYC_7282_16-Core_Processor-with-glibc2.38

version 2.2.6 has the same issue

## rdiff-backup call

rdiff-backup --api-version 201 --verbosity 9 --force backup /src/ntfs/over/samba /dst/ext4/over/ntf4

## What happened and what did you expect?

	Data={'type': 'reg', 'size': 231586, 'perms': 384, 'uid': 0, 'gid': 0, 'inode': 47972388, 'devloc': 33, 'nlink': 1, 'mtime': 1705229339, 'atime': 1705229339, 'ctime': 1705229339, 'uname': 'root', 'gname': 'root', 'ea': <rdiffbackup.meta.ea.ExtendedAttributes object at 0x7ff3350459d0>}>
2024-01-14 11:49:08.926036 +0100  <CLIENT-12316>  DEBUG: Setting time of path /mnt/Backup_1/daily/projects/patch_to_a_file_with_innvalid_date/rdiff-backup.tmp.1 to modified time 79870665600
2024-01-14 11:49:08.926318 +0100  <CLIENT-12316>  * Cleaning up
2024-01-14 11:49:08.926372 +0100  <CLIENT-12316>  DEBUG: Touching file /mnt/Backup_1/daily/projects/rdiff-backup-data/error_log.2024-01-14T11:47:54+01:00.data
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/rdiff-backup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/run.py", line 35, in main
    sys.exit(main_run(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/run.py", line 129, in main_run
    ret_val |= conn_act.run()
               ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/actions/backup.py", line 144, in run
    ret_code |= self._operate_backup(previous_time)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/actions/backup.py", line 164, in _operate_backup
    self.repo.apply(source_diffiter, previous_time)
  File "/usr/lib/python3.11/site-packages/rdiffbackup/locations/repository.py", line 382, in apply
    return self._shadow.apply(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/locations/_repo_shadow.py", line 139, in apply
    ITR(diff.index, diff)
  File "/usr/lib/python3.11/site-packages/rdiff_backup/rorpiter.py", line 150, in __call__
    last_branch.fast_process_file(*args)
  File "/usr/lib/python3.11/site-packages/rdiffbackup/locations/_repo_shadow.py", line 1604, in fast_process_file
    result = self._patch_to_temp(mirror_rp, diff_rorp, tf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/locations/_repo_shadow.py", line 1691, in _patch_to_temp
    rpath.copy_attribs(diff_rorp, new)
  File "/usr/lib/python3.11/site-packages/rdiff_backup/rpath.py", line 1782, in copy_attribs
    rpout.setmtime(rpin.getmtime())
  File "/usr/lib/python3.11/site-packages/rdiff_backup/rpath.py", line 810, in setmtime
    self.conn.os.utime(self.path, (int(time.time()), modtime))
OSError: [Errno 22] Invalid argument

I would expect, that this file would be skipped, rather that whole rdiff-backup failure

## More information
There is problem with Modify date corruption on source, however rdiff-backup shall deal with the situation. It is also possible that error is triggered on target filesystem, that refuse to set such attribute, I dont know how to test it. Anyway yet again rdiff-backup shall just skip this single error.

**Comment by ericzolf** [comment]
Do I need to care? I don't plan to be around at that time :smirk: 

Seriously, that's an interesting issue. It's beyond 2038 which might be part of the issue.
Depending on the OS (but perhaps also of the FS), calling `touch -d "2446-05-11 00:38:55.000000000 +0200" test`, I get either a file from 2446, or one from the 19th of January 2038 (the 32 bits limit).

I need to do more tests to see if I can reproduce the issue. Somehow, I have rdiff-backup only installed where I have the 2038 limit.

**Comment by tomascharvat** [comment]
So it really problem of destination mount/filesytem. It is ext4 over NFS4. Your test ends with
touch: setting times of 'test': Invalid argument
It works on source mountpoint/fs and also on all local mountpoints.

So if rdiff-backup stops on this condition by intention, this is not a bug report, but rather enhancement request. It would be better to throw warning and skip date set on target file.

**Comment by tomascharvat** [comment]
few more informations:
rdiff-backup source is fully 64bit, while destination is 32bit (old ARMv5 CPU).

So the problem is generally attempt to set 64 bit timestemp on 32bit destination.
