### ISSUE TITLE
backup to a pCloud mounted drive[?] 

### ISSUE THREAD

**Issue by zany130** [rdiff-backup/rdiff-backup#998]
## What is it about?

I would like to store my backups online with pCloud. There client mounts the cloud storage using FUSE to the user's home directory

## Version, Python, Operating System

Call `rdiff-backup info` and replace the following line with the output,
repeat for each environment impacted, especially if using remote operations:

```yaml
rdiff-backup info
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - /usr/bin/rdiff-backup
  - info
  parsed: null
  version: 2.2.6
python:
  executable: /usr/bin/python
  name: cpython
  version: 3.11.8
system:
  fs_encoding: utf-8
  platform: Linux-6.8.2-3-cachyos-x86_64-with-glibc2.39
...
```

## rdiff-backup call

If you tried something already, how did you call rdiff-backup, with which parameters:

```
rdiff-backup --verbosity 5 backup --print-statistics --include-special-files --include-globbing-filelist /home/zany130/.config/include-list.txt /home/zany130 /home/zany130/pCloudDrive/RdiffBak
```

And what was the result?

```
rdiff-backup --verbosity 5 backup --print-statistics --include-special-files --include-globbing-filelist /home/zany130/.config/include-list.txt /home/zany130 /home/zany130/pCloudDrive/RdiffBak
WARNING: Server will be called with deprecated command line interface to guarantee compatibility. It might lead to a deprecation warning from newer rdiff-backup versions. Use '--api-version 201' (or higher) to avoid it.
* Using repository '/home/zany130/pCloudDrive/RdiffBak'
NOTE: Found interrupted initial backup in data directory /home/zany130/pCloudDrive/RdiffBak/rdiff-backup-data. Removing...
* Unable to import win32security module. Windows ACLs not supported by filesystem at path /home/zany130
* Could not determine if source directory /home/zany130 permits trailing spaces or periods in filenames because we can't find any files with trailing dot/period. It will be treated as permitting such files, but none will exist if it doesn't, so it doesn't really matter and is harmless
* -----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
NOTE: Hard linking not supported by filesystem at path /home/zany130/pCloudDrive/RdiffBak/rdiff-backup-data, hard links will be copied instead
* Unable to import win32security module. Windows ACLs not supported by filesystem at path /home/zany130/pCloudDrive/RdiffBak/rdiff-backup-data/rdiff-backup.tmp.0
* -----------------------------------------------------------------
Detected abilities for destination (read/write) file system:
  Ownership changing                           On
  Hard linking                                 N/A
  fsync() directories                          On
  Directory inc permissions                    Off
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   Off
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
* Backup: escape_dos_devices = 0
* Backup: escape_trailing_spaces = 0
* Reading globbing filelist /home/zany130/.config/include-list.txt
WARNING: The target directory '/home/zany130/pCloudDrive/RdiffBak' may be contained in the source directory '/home/zany130'. This could cause an infinite recursion. You may need to use the --exclude option (which you might already have done).
* Given repository doesn't need to be regressed
NOTE: Starting mirror from source path /home/zany130 to destination path /home/zany130/pCloudDrive/RdiffBak
* Processing file .
* Processing file .Garuda-Linux.pacmanity.kate-swp
* Processing file .Xauthority
* Processing file .bash_history
* Processing file .bash_history-33628.tmp
* Processing file .byobu
* Processing file .byobu/bin
* Processing file .byobu/color
* Cleaning up
Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/run.py", line 35, in main
    sys.exit(main_run(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/run.py", line 108, in main_run
    ret_val |= conn_act.run()
               ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/actions/backup.py", line 159, in run
    backup.mirror_compat200(
  File "/usr/lib/python3.11/site-packages/rdiff_backup/backup.py", line 39, in mirror_compat200
    DestS.patch(dest_rpath, source_diffiter)
  File "/usr/lib/python3.11/site-packages/rdiff_backup/backup.py", line 197, in patch
    ITR(diff.index, diff)
  File "/usr/lib/python3.11/site-packages/rdiff_backup/rorpiter.py", line 142, in __call__
    if self._finish_branches(index):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiff_backup/rorpiter.py", line 179, in _finish_branches
    to_be_finished.end_process_directory()
  File "/usr/lib/python3.11/site-packages/rdiff_backup/backup.py", line 633, in end_process_directory
    rpath.copy_attribs(self.dir_update, self.base_rp)
  File "/usr/lib/python3.11/site-packages/rdiff_backup/rpath.py", line 1692, in copy_attribs
    rpout.write_acl(rpin.get_acl())
  File "/usr/lib/python3.11/site-packages/rdiff_backup/rpath.py", line 1329, in write_acl
    acl_meta.write_to_rp(self, map_names)
  File "/usr/lib/python3.11/site-packages/rdiffbackup/meta/acl_posix.py", line 123, in write_to_rp
    set_rp_acl(rp, self.entry_list, self.default_entry_list, map_names)
  File "/usr/lib/python3.11/site-packages/rdiffbackup/meta/acl_posix.py", line 347, in set_rp_acl
    def_acl.applyto(rp.path, posix1e.ACL_TYPE_DEFAULT)
OSError: [Errno 61] No data available: '/home/zany130/pCloudDrive/RdiffBak/.byobu/bin'

```

**Comment by ericzolf** [comment]
First, I assume that your selection file avoids an endless recursion as warned by rdiff-backup.

Second, FUSE drivers are known to be critical when it comes to a proper backup, they don't always are reliable or fast enough. Here I suspect with ACL support, which might be only imperfectly implemented, you should try to exclude ACLs (and extended attributes?) from your backup.

Sadly the posix1e/libacl library is compiled so there is not much I can do here. I could imagine that you'll get the same kind of error if you'd try something like:

```python
$ python
Python 3.12.2 (main, Feb 21 2024, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import posix1e
>>> def_acl = posix1e.ACL()
>>> def_acl.applyto(b'/home/zany130/pCloudDrive/RdiffBak/.byobu/bin', posix1e.ACL_TYPE_DEFAULT)
```

But the error could also more subtle. Without pCloud it's difficult for me to debug, if you'd know which FUSE technology/driver they are using, I could try to reproduce (as far as possible without pCloud).

**Comment by zany130** [comment]
```
systemctl --user status app-pcloud@autostart.service
● app-pcloud@autostart.service - pcloud
     Loaded: loaded (/home/zany130/.config/autostart/pcloud.desktop; generated)
     Active: active (running) since Fri 2024-04-05 11:27:21 EDT; 6min ago
       Docs: man:systemd-xdg-autostart-generator(8)
   Main PID: 10085 (binfmt-bypass)
      Tasks: 70 (limit: 38378)
     Memory: 428.5M (peak: 571.8M)
        CPU: 4.446s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/app-pcloud@autostart.service
             ├─10085 /usr/lib/appimagelauncher/binfmt-bypass /home/zany130/Applications/pcloud
             ├─11302 /tmp/.mount_pcloudGaJ743/pcloud
             ├─11317 /home/zany130/Applications/pcloud
             ├─11874 "/tmp/.mount_pcloudGaJ743/pcloud --type=zygote --no-sandbox"
             ├─13198 fusermount -o rw,nosuid,nodev,auto_unmount,fsname=pCloud.fs,nonempty -- /home/zany130/pCloudDrive
             └─13624 "/tmp/.mount_pcloudGaJ743/pcloud --type=renderer --no-sandbox --disable-gpu-compositing --service-pipe-token=5F6143926845B227A74F553F484C7CCD --lang=en-US --app-path=/tmp/.mount_pcloudGaJ743/>

Apr 05 11:29:43 Garuda-Linux pcloud[11302]: Down: Everything Downloaded| Up: Everything Uploaded, status is READY
Apr 05 11:29:43 Garuda-Linux pcloud[11302]: STATUS -------------> 0
Apr 05 11:29:44 Garuda-Linux pcloud[11302]: Down: Everything Downloaded| Up: Everything Uploaded, status is READY
Apr 05 11:29:44 Garuda-Linux pcloud[11302]: STATUS -------------> 0
Apr 05 11:29:45 Garuda-Linux pcloud[11302]: Down: Everything Downloaded| Up: Everything Uploaded, status is READY
Apr 05 11:29:45 Garuda-Linux pcloud[11302]: STATUS -------------> 0
Apr 05 11:29:46 Garuda-Linux pcloud[11302]: Down: Everything Downloaded| Up: Everything Uploaded, status is READY
Apr 05 11:29:46 Garuda-Linux pcloud[11302]: STATUS -------------> 0
Apr 05 11:29:47 Garuda-Linux pcloud[11302]: Down: Everything Downloaded| Up: Everything Uploaded, status is READY
Apr 05 11:29:47 Garuda-Linux pcloud[11302]: STATUS -------------> 0
```
not sure if this provides more insight into how pcloud mounts it's drive.



> Sadly the posix1e/libacl library is compiled so there is not much I can do here. I could imagine that you'll get the same kind of error if you'd try something like:

yup I get the exact same error running those python commands so it looks like an issue with libacl and fuse?

> Second, FUSE drivers are known to be critical when it comes to a proper backup, they don't always are reliable or fast enough. Here I suspect with ACL support, which might be only imperfectly implemented, you should try to exclude ACLs (and extended attributes?) from your backup.

Yeah, it sounds like this might not be the best way to go about this. Maybe I should keep backing up to my local drive and then maybe somehow back up a compressed zip of the `rdiff-backup` folder?

Originally, I was just backing up onto a secondary hard drive and then syncing the `rdiff-backup` folder to my pCloud drive using the Cloud app to create a sync, but that was giving me permission issues on pCloud.

**Comment by ericzolf** [comment]
> not sure if this provides more insight into how pcloud mounts it's drive.

No, it doesn't but the following test makes it unnecessary anyway.
> 
> > Sadly the posix1e/libacl library is compiled so there is not much I can do here. I could imagine that you'll get the same kind of error if you'd try something like:
> 
> yup I get the exact same error running those python commands so it looks like an issue with libacl and fuse?

Correct, or at least ACL and the fuse driver used by pmount.
> 
> > Second, FUSE drivers are known to be critical when it comes to a proper backup, they don't always are reliable or fast enough. Here I suspect with ACL support, which might be only imperfectly implemented, you should try to exclude ACLs (and extended attributes?) from your backup.
> 
> Yeah, it sounds like this might not be the best way to go about this. Maybe I should keep backing up to my local drive and then maybe somehow back up a compressed zip of the `rdiff-backup` folder?

It doesn't sound very efficient, even though, it would possibly work. Why not rather try excluding ACLs? Do you really need them?

> 
> Originally, I was just backing up onto a secondary hard drive and then syncing the `rdiff-backup` folder to my pCloud drive using the Cloud app to create a sync, but that was giving me permission issues on pCloud.
> 
> Maybe pCloud is not the best solution for storing a backup of my .files ?
You could try contacting the support of pCloud and see what they say but I fear that I can't help more.

**Comment by zany130** [comment]
Really what I want is to have a backup of my rdiff-backup folder on an online storage like pCloud ( in case the disk I have rdiff on dies or whatever)

so that lead me to an idea : could I tar the Rdiff-backup folder?

I could then  do something like this
```
File: Scripts/tarRdiff-Bak.sh
#!/bin/bash
# Backup source
backsource=/mnt/GAMES/RdiffBak
# Backup destination
backdest=/home/zany130/pCloudDrive/RdiffBak/

# Labels for backup name
pc=${HOSTNAME}
date=$(date "+%F")
backupfile="$backdest/rdiff-bak-$pc-$date.tar.gz"

bsdtar  --acls --xattrs -cpvaf "$backupfile" "$backsource"
```

**Comment by ericzolf** [comment]
I already wrote it: that would work but that wouldn't be efficient in disk space (or even in time). You didn't answer to my suggestion to not save ACLs.

**Comment by zany130** [comment]
> You didn't answer to my suggestion to not save ACLs.

my bad, I forgot to mention this it fails with a different error

```
WARNING: Exception '[Errno 38] Function not implemented: b'gamecube' -> b'/home/zany130/pCloudDrive/RdiffBak2/.config/EmuDeck/backend/roms/rdiff-backup.tmp.8640'' raised of class '<class 'OSError'>':
  File "/usr/lib/python3.11/site-packages/rdiff_backup/robust.py", line 94, in check_common_error
    return function(*args)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiff_backup/rpath.py", line 1594, in copy
    rpout.symlink(rpin.readlink())
  File "/usr/lib/python3.11/site-packages/rdiff_backup/rpath.py", line 818, in symlink
    self.conn.os.symlink(linktext, self.path)

* Cleaning up
Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/run.py", line 35, in main
    sys.exit(main_run(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/run.py", line 108, in main_run
    ret_val |= conn_act.run()
               ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiffbackup/actions/backup.py", line 159, in run
    backup.mirror_compat200(
  File "/usr/lib/python3.11/site-packages/rdiff_backup/backup.py", line 39, in mirror_compat200
    DestS.patch(dest_rpath, source_diffiter)
  File "/usr/lib/python3.11/site-packages/rdiff_backup/backup.py", line 197, in patch
    ITR(diff.index, diff)
  File "/usr/lib/python3.11/site-packages/rdiff_backup/rorpiter.py", line 146, in __call__
    last_branch.fast_process_file(*args)
  File "/usr/lib/python3.11/site-packages/rdiff_backup/backup.py", line 600, in fast_process_file
    if self._patch_to_temp(mirror_rp, diff_rorp, tf):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiff_backup/backup.py", line 655, in _patch_to_temp
    result = self._patch_snapshot_to_temp(diff_rorp, new)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiff_backup/backup.py", line 697, in _patch_snapshot_to_temp
    self._write_special(diff_rorp, new)
  File "/usr/lib/python3.11/site-packages/rdiff_backup/backup.py", line 743, in _write_special
    if robust.check_common_error(eh, rpath.copy, (diff_rorp, new)) == 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiff_backup/robust.py", line 94, in check_common_error
    return function(*args)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/rdiff_backup/rpath.py", line 1594, in copy
    rpout.symlink(rpin.readlink())
  File "/usr/lib/python3.11/site-packages/rdiff_backup/rpath.py", line 818, in symlink
    self.conn.os.symlink(linktext, self.path)
OSError: [Errno 38] Function not implemented: b'gamecube' -> b'/home/zany130/pCloudDrive/RdiffBak2/.config/EmuDeck/backend/roms/rdiff-backup.tmp.8640'
```

I

**Comment by ericzolf** [comment]
Well, you can also exclude symlinks, and continue in the hope that it'll be good enough but that doesn't give much confidence.

**Comment by zany130** [comment]
Yeah, FWIW, pCloud support got back to me, and they say they do not support the storage of `.` and don't recommend it as permissions are not kept.. so best I can do it seems to backup to my local HDD as I was doing and then tar zip the whole thing and hope permissions don't get messed up if I extract it.


if anyone wants to see how I do that I have it in a gist here https://gist.github.com/zany130/9527b04b21ebe8555f11111629da84e1
